#
# Makefile for the BSP library routines
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#


obj-$(CONFIG_LONG_LONG_SUPPORT) += udivdi3.o
EXTRA_CFLAGS += -I $(TOPDIR)/include/asm-generic
