# CONFIG_KALLSYMS_ALL is not set
# CONFIG_PCI_DEBUG is not set
# CONFIG_DEBUG_DRIVER is not set
CONFIG_DETECT_SOFTLOCKUP=y
# CONFIG_SCHEDSTATS is not set
# CONFIG_DEBUG_SLAB is not set
# CONFIG_DEBUG_RT_MUTEXES is not set
# CONFIG_RT_MUTEX_TESTER is not set
# CONFIG_DEBUG_SPINLOCK is not set
# CONFIG_DEBUG_MUTEXES is not set
# CONFIG_DEBUG_RWSEMS is not set
# CONFIG_DEBUG_SPINLOCK_SLEEP is not set
# CONFIG_DEBUG_LOCKING_API_SELFTESTS is not set
# CONFIG_DEBUG_KOBJECT is not set
CONFIG_DEBUG_INFO=y
# CONFIG_DEBUG_VM is not set
CONFIG_FORCED_INLINING=y
# CONFIG_RCU_TORTURE_TEST is not set
CONFIG_WANT_EXTRA_DEBUG_INFORMATION=y
CONFIG_KGDB=y
# CONFIG_CONFIG_SMTC_IDLE_HOOK_DEBUG is not set
# CONFIG_KGDB_CONSOLE is not set
# CONFIG_KGDB_ONLY_MODULES is not set
# CONFIG_KGDB_8250_NOMODULE is not set
# CONFIG_KGDBOE_NOMODULE is not set
# CONFIG_KGDB_MPSC is not set
# CONFIG_KGDB_SIBYTE is not set
# CONFIG_KGDB_BRCM97XXX is not set
# CONFIG_DEBUG_STACK_USAGE is not set
# CONFIG_GDB_CONSOLE is not set
# CONFIG_RUNTIME_DEBUG is not set
# CONFIG_MIPS_UNCACHED is not set
# CONFIG_CACHE_STATS is not set
# CONFIG_KMALLOC_ACCOUNTING is not set
# CONFIG_VMALLOC_ACCOUNTING is not set
# CONFIG_WARN_UNINITIALIZED is not set
CONFIG_MIPS_BRCM_NOSIM=y
# CONFIG_MIPS_BRCM_SIM is not set
# CONFIG_MIPS_BRCM_IKOS is not set
# CONFIG_MIPS_BRCM_VELOCE is not set
