/***************************************************************************
 *     Copyright (c) 1999-2005, Broadcom Corporation
 *     
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 *
 *
 * $brcm_Workfile: bchp_common.h $
 * $brcm_Revision: Hydra_Software_Devel/4 $
 * $brcm_Date: 11/22/04 1:57p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Mon Nov 22 13:29:27 2004
 *                 MD5 Checksum         0d374a734a3ca6b767d69796fad30b1f
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.006
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7038/rdb/c0/bchp_common.h $
 * 
 * Hydra_Software_Devel/4   11/22/04 1:57p pntruong
 * PR12318: Synchonize basemodules/chp/7038 header files with RDB.
 *
 ***************************************************************************/

#ifndef BCHP_COMMON_H__
#define BCHP_COMMON_H__

/***************************************************************************
 *BCM7038_C0
 ***************************************************************************/
#define BCHP_PHYSICAL_OFFSET                               0x10000000

/***************************************************************************
 *AUD
 ***************************************************************************/
/***************************************************************************
 *ABSTRACT_01_SPECVERSION - Audio Specification Version
 ***************************************************************************/
/* AUD :: ABSTRACT_01_SPECVERSION :: Version [31:00] */
#define BCHP_AUD_ABSTRACT_01_SPECVERSION_Version_MASK              0xffffffff
#define BCHP_AUD_ABSTRACT_01_SPECVERSION_Version_SHIFT             0

/***************************************************************************
 *ABSTRACT_02_INTERRUPT_HANDLING - Interrupt Handling
 ***************************************************************************/
/* AUD :: ABSTRACT_02_INTERRUPT_HANDLING :: MORE_INFORMATION [31:00] */
#define BCHP_AUD_ABSTRACT_02_INTERRUPT_HANDLING_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_AUD_ABSTRACT_02_INTERRUPT_HANDLING_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *PROG_EX_01_TONE_TEST - Tone Test
 ***************************************************************************/
/* AUD :: PROG_EX_01_TONE_TEST :: MORE_INFORMATION [31:00] */
#define BCHP_AUD_PROG_EX_01_TONE_TEST_MORE_INFORMATION_MASK        0xffffffff
#define BCHP_AUD_PROG_EX_01_TONE_TEST_MORE_INFORMATION_SHIFT       0

/***************************************************************************
 *PROG_EX_02_DOLBY_DIGITAL_AUDIO_MODE - Dolby Digital Audio Mode
 ***************************************************************************/
/* AUD :: PROG_EX_02_DOLBY_DIGITAL_AUDIO_MODE :: MORE_INFORMATION [31:00] */
#define BCHP_AUD_PROG_EX_02_DOLBY_DIGITAL_AUDIO_MODE_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_AUD_PROG_EX_02_DOLBY_DIGITAL_AUDIO_MODE_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *PROG_EX_03_MPEG_AUDIO_MODE - MPEG Audio Mode
 ***************************************************************************/
/* AUD :: PROG_EX_03_MPEG_AUDIO_MODE :: MORE_INFORMATION [31:00] */
#define BCHP_AUD_PROG_EX_03_MPEG_AUDIO_MODE_MORE_INFORMATION_MASK  0xffffffff
#define BCHP_AUD_PROG_EX_03_MPEG_AUDIO_MODE_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *PROG_EX_04_SIMULTANEOUS_MODE - Simultaneous Mode
 ***************************************************************************/
/* AUD :: PROG_EX_04_SIMULTANEOUS_MODE :: MORE_INFORMATION [31:00] */
#define BCHP_AUD_PROG_EX_04_SIMULTANEOUS_MODE_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_AUD_PROG_EX_04_SIMULTANEOUS_MODE_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *PROG_EX_05_COMPRESSED_AUDIO_CLIP - Compressed Audio Clip
 ***************************************************************************/
/* AUD :: PROG_EX_05_COMPRESSED_AUDIO_CLIP :: MORE_INFORMATION [31:00] */
#define BCHP_AUD_PROG_EX_05_COMPRESSED_AUDIO_CLIP_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_AUD_PROG_EX_05_COMPRESSED_AUDIO_CLIP_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *PROG_EX_06_PES_PVR_PLAYBACK - PES PVR Playback
 ***************************************************************************/
/* AUD :: PROG_EX_06_PES_PVR_PLAYBACK :: MORE_INFORMATION [31:00] */
#define BCHP_AUD_PROG_EX_06_PES_PVR_PLAYBACK_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_AUD_PROG_EX_06_PES_PVR_PLAYBACK_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *PROG_EX_07_TRICK_MODE_PROGRAMMING - Trick Mode Programming
 ***************************************************************************/
/* AUD :: PROG_EX_07_TRICK_MODE_PROGRAMMING :: MORE_INFORMATION [31:00] */
#define BCHP_AUD_PROG_EX_07_TRICK_MODE_PROGRAMMING_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_AUD_PROG_EX_07_TRICK_MODE_PROGRAMMING_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *BVN_MFD
 ***************************************************************************/
/***************************************************************************
 *DRAM_DATA_STRUCTURE - DRAM Data Structure
 ***************************************************************************/
/* BVN_MFD :: DRAM_DATA_STRUCTURE :: DRAM_DATA_STRUCTURE [31:00] */
#define BCHP_BVN_MFD_DRAM_DATA_STRUCTURE_DRAM_DATA_STRUCTURE_MASK  0xffffffff
#define BCHP_BVN_MFD_DRAM_DATA_STRUCTURE_DRAM_DATA_STRUCTURE_SHIFT 0

/***************************************************************************
 *GFD
 ***************************************************************************/
/***************************************************************************
 *DRAM_DATA_STRUCTURE - DRAM Data Structure
 ***************************************************************************/
/* GFD :: DRAM_DATA_STRUCTURE :: DRAM_DATA_STRUCTURE [31:00] */
#define BCHP_GFD_DRAM_DATA_STRUCTURE_DRAM_DATA_STRUCTURE_MASK      0xffffffff
#define BCHP_GFD_DRAM_DATA_STRUCTURE_DRAM_DATA_STRUCTURE_SHIFT     0

/***************************************************************************
 *HIFIDAC_CTRL
 ***************************************************************************/
/***************************************************************************
 *ABSTRACT_01_COMING_OUT_OF_RESET - Process to come out of reset
 ***************************************************************************/
/* HIFIDAC_CTRL :: ABSTRACT_01_COMING_OUT_OF_RESET :: MORE_INFORMATION [31:00] */
#define BCHP_HIFIDAC_CTRL_ABSTRACT_01_COMING_OUT_OF_RESET_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_HIFIDAC_CTRL_ABSTRACT_01_COMING_OUT_OF_RESET_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *ABSTRACT_02_MUTE_USAGE - Mute usage
 ***************************************************************************/
/* HIFIDAC_CTRL :: ABSTRACT_02_MUTE_USAGE :: MORE_INFORMATION [31:00] */
#define BCHP_HIFIDAC_CTRL_ABSTRACT_02_MUTE_USAGE_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_HIFIDAC_CTRL_ABSTRACT_02_MUTE_USAGE_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *ABSTRACT_03_SAMPLE_RATE_CHANGE - Process to effect a sample rate change
 ***************************************************************************/
/* HIFIDAC_CTRL :: ABSTRACT_03_SAMPLE_RATE_CHANGE :: MORE_INFORMATION [31:00] */
#define BCHP_HIFIDAC_CTRL_ABSTRACT_03_SAMPLE_RATE_CHANGE_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_HIFIDAC_CTRL_ABSTRACT_03_SAMPLE_RATE_CHANGE_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *M2MC
 ***************************************************************************/
/***************************************************************************
 *LIST_PACKET_ABSTRACT - Linked-List Packet Abstract
 ***************************************************************************/
/* M2MC :: LIST_PACKET_ABSTRACT :: PACKET_FORMAT [31:00] */
#define BCHP_M2MC_LIST_PACKET_ABSTRACT_PACKET_FORMAT_MASK          0xffffffff
#define BCHP_M2MC_LIST_PACKET_ABSTRACT_PACKET_FORMAT_SHIFT         0

/***************************************************************************
 *LIST_PACKET_HEADER_0 - Linked-List Packet Header Word 0
 ***************************************************************************/
/* M2MC :: LIST_PACKET_HEADER_0 :: reserved0 [31:28] */
#define BCHP_M2MC_LIST_PACKET_HEADER_0_reserved0_MASK              0xf0000000
#define BCHP_M2MC_LIST_PACKET_HEADER_0_reserved0_SHIFT             28

/* M2MC :: LIST_PACKET_HEADER_0 :: NEXT_PKT_ADDR [27:05] */
#define BCHP_M2MC_LIST_PACKET_HEADER_0_NEXT_PKT_ADDR_MASK          0x0fffffe0
#define BCHP_M2MC_LIST_PACKET_HEADER_0_NEXT_PKT_ADDR_SHIFT         5

/* M2MC :: LIST_PACKET_HEADER_0 :: reserved1 [04:01] */
#define BCHP_M2MC_LIST_PACKET_HEADER_0_reserved1_MASK              0x0000001e
#define BCHP_M2MC_LIST_PACKET_HEADER_0_reserved1_SHIFT             1

/* M2MC :: LIST_PACKET_HEADER_0 :: LAST_PKT_IND [00:00] */
#define BCHP_M2MC_LIST_PACKET_HEADER_0_LAST_PKT_IND_MASK           0x00000001
#define BCHP_M2MC_LIST_PACKET_HEADER_0_LAST_PKT_IND_SHIFT          0
#define BCHP_M2MC_LIST_PACKET_HEADER_0_LAST_PKT_IND_NextPktValid   0
#define BCHP_M2MC_LIST_PACKET_HEADER_0_LAST_PKT_IND_NextPktInvalid 1

/***************************************************************************
 *LIST_PACKET_HEADER_1 - Linked-List Packet Header Word 1
 ***************************************************************************/
/* M2MC :: LIST_PACKET_HEADER_1 :: reserved0 [31:15] */
#define BCHP_M2MC_LIST_PACKET_HEADER_1_reserved0_MASK              0xffff8000
#define BCHP_M2MC_LIST_PACKET_HEADER_1_reserved0_SHIFT             15

/* M2MC :: LIST_PACKET_HEADER_1 :: SRC_FEEDER_GRP_CNTRL [14:14] */
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SRC_FEEDER_GRP_CNTRL_MASK   0x00004000
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SRC_FEEDER_GRP_CNTRL_SHIFT  14
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SRC_FEEDER_GRP_CNTRL_GRP_ENABLE 1
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SRC_FEEDER_GRP_CNTRL_GRP_DISABLE 0

/* M2MC :: LIST_PACKET_HEADER_1 :: DST_FEEDER_GRP_CNTRL [13:13] */
#define BCHP_M2MC_LIST_PACKET_HEADER_1_DST_FEEDER_GRP_CNTRL_MASK   0x00002000
#define BCHP_M2MC_LIST_PACKET_HEADER_1_DST_FEEDER_GRP_CNTRL_SHIFT  13
#define BCHP_M2MC_LIST_PACKET_HEADER_1_DST_FEEDER_GRP_CNTRL_GRP_ENABLE 1
#define BCHP_M2MC_LIST_PACKET_HEADER_1_DST_FEEDER_GRP_CNTRL_GRP_DISABLE 0

/* M2MC :: LIST_PACKET_HEADER_1 :: OUTPUT_FEEDER_GRP_CNTRL [12:12] */
#define BCHP_M2MC_LIST_PACKET_HEADER_1_OUTPUT_FEEDER_GRP_CNTRL_MASK 0x00001000
#define BCHP_M2MC_LIST_PACKET_HEADER_1_OUTPUT_FEEDER_GRP_CNTRL_SHIFT 12
#define BCHP_M2MC_LIST_PACKET_HEADER_1_OUTPUT_FEEDER_GRP_CNTRL_GRP_ENABLE 1
#define BCHP_M2MC_LIST_PACKET_HEADER_1_OUTPUT_FEEDER_GRP_CNTRL_GRP_DISABLE 0

/* M2MC :: LIST_PACKET_HEADER_1 :: BLIT_GRP_CNTRL [11:11] */
#define BCHP_M2MC_LIST_PACKET_HEADER_1_BLIT_GRP_CNTRL_MASK         0x00000800
#define BCHP_M2MC_LIST_PACKET_HEADER_1_BLIT_GRP_CNTRL_SHIFT        11
#define BCHP_M2MC_LIST_PACKET_HEADER_1_BLIT_GRP_CNTRL_GRP_ENABLE   1
#define BCHP_M2MC_LIST_PACKET_HEADER_1_BLIT_GRP_CNTRL_GRP_DISABLE  0

/* M2MC :: LIST_PACKET_HEADER_1 :: SCALE_PARAM_GRP_CNTRL [10:10] */
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SCALE_PARAM_GRP_CNTRL_MASK  0x00000400
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SCALE_PARAM_GRP_CNTRL_SHIFT 10
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SCALE_PARAM_GRP_CNTRL_GRP_ENABLE 1
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SCALE_PARAM_GRP_CNTRL_GRP_DISABLE 0

/* M2MC :: LIST_PACKET_HEADER_1 :: BLEND_PARAM_GRP_CNTRL [09:09] */
#define BCHP_M2MC_LIST_PACKET_HEADER_1_BLEND_PARAM_GRP_CNTRL_MASK  0x00000200
#define BCHP_M2MC_LIST_PACKET_HEADER_1_BLEND_PARAM_GRP_CNTRL_SHIFT 9
#define BCHP_M2MC_LIST_PACKET_HEADER_1_BLEND_PARAM_GRP_CNTRL_GRP_ENABLE 1
#define BCHP_M2MC_LIST_PACKET_HEADER_1_BLEND_PARAM_GRP_CNTRL_GRP_DISABLE 0

/* M2MC :: LIST_PACKET_HEADER_1 :: ROP_GRP_CNTRL [08:08] */
#define BCHP_M2MC_LIST_PACKET_HEADER_1_ROP_GRP_CNTRL_MASK          0x00000100
#define BCHP_M2MC_LIST_PACKET_HEADER_1_ROP_GRP_CNTRL_SHIFT         8
#define BCHP_M2MC_LIST_PACKET_HEADER_1_ROP_GRP_CNTRL_GRP_ENABLE    1
#define BCHP_M2MC_LIST_PACKET_HEADER_1_ROP_GRP_CNTRL_GRP_DISABLE   0

/* M2MC :: LIST_PACKET_HEADER_1 :: SRC_COLOR_KEY_GRP_CNTRL [07:07] */
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SRC_COLOR_KEY_GRP_CNTRL_MASK 0x00000080
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SRC_COLOR_KEY_GRP_CNTRL_SHIFT 7
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SRC_COLOR_KEY_GRP_CNTRL_GRP_ENABLE 1
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SRC_COLOR_KEY_GRP_CNTRL_GRP_DISABLE 0

/* M2MC :: LIST_PACKET_HEADER_1 :: DST_COLOR_KEY_GRP_CNTRL [06:06] */
#define BCHP_M2MC_LIST_PACKET_HEADER_1_DST_COLOR_KEY_GRP_CNTRL_MASK 0x00000040
#define BCHP_M2MC_LIST_PACKET_HEADER_1_DST_COLOR_KEY_GRP_CNTRL_SHIFT 6
#define BCHP_M2MC_LIST_PACKET_HEADER_1_DST_COLOR_KEY_GRP_CNTRL_GRP_ENABLE 1
#define BCHP_M2MC_LIST_PACKET_HEADER_1_DST_COLOR_KEY_GRP_CNTRL_GRP_DISABLE 0

/* M2MC :: LIST_PACKET_HEADER_1 :: SCALE_COEF_GRP_CNTRL [05:05] */
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SCALE_COEF_GRP_CNTRL_MASK   0x00000020
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SCALE_COEF_GRP_CNTRL_SHIFT  5
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SCALE_COEF_GRP_CNTRL_GRP_ENABLE 1
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SCALE_COEF_GRP_CNTRL_GRP_DISABLE 0

/* M2MC :: LIST_PACKET_HEADER_1 :: SRC_COLOR_MATRIX_GRP_CNTRL [04:04] */
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SRC_COLOR_MATRIX_GRP_CNTRL_MASK 0x00000010
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SRC_COLOR_MATRIX_GRP_CNTRL_SHIFT 4
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SRC_COLOR_MATRIX_GRP_CNTRL_GRP_ENABLE 1
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SRC_COLOR_MATRIX_GRP_CNTRL_GRP_DISABLE 0

/* M2MC :: LIST_PACKET_HEADER_1 :: DST_COLOR_MATRIX_GRP_CNTRL [03:03] */
#define BCHP_M2MC_LIST_PACKET_HEADER_1_DST_COLOR_MATRIX_GRP_CNTRL_MASK 0x00000008
#define BCHP_M2MC_LIST_PACKET_HEADER_1_DST_COLOR_MATRIX_GRP_CNTRL_SHIFT 3
#define BCHP_M2MC_LIST_PACKET_HEADER_1_DST_COLOR_MATRIX_GRP_CNTRL_GRP_ENABLE 1
#define BCHP_M2MC_LIST_PACKET_HEADER_1_DST_COLOR_MATRIX_GRP_CNTRL_GRP_DISABLE 0

/* M2MC :: LIST_PACKET_HEADER_1 :: OUTPUT_COLOR_MATRIX_GRP_CNTRL [02:02] */
#define BCHP_M2MC_LIST_PACKET_HEADER_1_OUTPUT_COLOR_MATRIX_GRP_CNTRL_MASK 0x00000004
#define BCHP_M2MC_LIST_PACKET_HEADER_1_OUTPUT_COLOR_MATRIX_GRP_CNTRL_SHIFT 2
#define BCHP_M2MC_LIST_PACKET_HEADER_1_OUTPUT_COLOR_MATRIX_GRP_CNTRL_GRP_ENABLE 1
#define BCHP_M2MC_LIST_PACKET_HEADER_1_OUTPUT_COLOR_MATRIX_GRP_CNTRL_GRP_DISABLE 0

/* M2MC :: LIST_PACKET_HEADER_1 :: SRC_CLUT_GRP_CNTRL [01:01] */
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SRC_CLUT_GRP_CNTRL_MASK     0x00000002
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SRC_CLUT_GRP_CNTRL_SHIFT    1
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SRC_CLUT_GRP_CNTRL_GRP_ENABLE 1
#define BCHP_M2MC_LIST_PACKET_HEADER_1_SRC_CLUT_GRP_CNTRL_GRP_DISABLE 0

/* M2MC :: LIST_PACKET_HEADER_1 :: DST_CLUT_GRP_CNTRL [00:00] */
#define BCHP_M2MC_LIST_PACKET_HEADER_1_DST_CLUT_GRP_CNTRL_MASK     0x00000001
#define BCHP_M2MC_LIST_PACKET_HEADER_1_DST_CLUT_GRP_CNTRL_SHIFT    0
#define BCHP_M2MC_LIST_PACKET_HEADER_1_DST_CLUT_GRP_CNTRL_GRP_ENABLE 1
#define BCHP_M2MC_LIST_PACKET_HEADER_1_DST_CLUT_GRP_CNTRL_GRP_DISABLE 0

/***************************************************************************
 *LIST_PKT_00_SRC_FEEDER_N - Linked-List Packet Word N for group SRC_FEEDER
 ***************************************************************************/
/* M2MC :: LIST_PKT_00_SRC_FEEDER_N :: REGISTER_CONTENTS [31:00] */
#define BCHP_M2MC_LIST_PKT_00_SRC_FEEDER_N_REGISTER_CONTENTS_MASK  0xffffffff
#define BCHP_M2MC_LIST_PKT_00_SRC_FEEDER_N_REGISTER_CONTENTS_SHIFT 0

/***************************************************************************
 *LIST_PKT_01_DST_FEEDER_N - Linked-List Packet Word N for group DST_FEEDER
 ***************************************************************************/
/* M2MC :: LIST_PKT_01_DST_FEEDER_N :: REGISTER_CONTENTS [31:00] */
#define BCHP_M2MC_LIST_PKT_01_DST_FEEDER_N_REGISTER_CONTENTS_MASK  0xffffffff
#define BCHP_M2MC_LIST_PKT_01_DST_FEEDER_N_REGISTER_CONTENTS_SHIFT 0

/***************************************************************************
 *LIST_PKT_02_OUTPUT_FEEDER_N - Linked-List Packet Word N for group OUTPUT_FEEDER
 ***************************************************************************/
/* M2MC :: LIST_PKT_02_OUTPUT_FEEDER_N :: REGISTER_CONTENTS [31:00] */
#define BCHP_M2MC_LIST_PKT_02_OUTPUT_FEEDER_N_REGISTER_CONTENTS_MASK 0xffffffff
#define BCHP_M2MC_LIST_PKT_02_OUTPUT_FEEDER_N_REGISTER_CONTENTS_SHIFT 0

/***************************************************************************
 *LIST_PKT_03_BLIT_N - Linked-List Packet Word N for group BLIT
 ***************************************************************************/
/* M2MC :: LIST_PKT_03_BLIT_N :: REGISTER_CONTENTS [31:00] */
#define BCHP_M2MC_LIST_PKT_03_BLIT_N_REGISTER_CONTENTS_MASK        0xffffffff
#define BCHP_M2MC_LIST_PKT_03_BLIT_N_REGISTER_CONTENTS_SHIFT       0

/***************************************************************************
 *LIST_PKT_04_SCALE_PARAM_N - Linked-List Packet Word N for group SCALE_PARAM
 ***************************************************************************/
/* M2MC :: LIST_PKT_04_SCALE_PARAM_N :: REGISTER_CONTENTS [31:00] */
#define BCHP_M2MC_LIST_PKT_04_SCALE_PARAM_N_REGISTER_CONTENTS_MASK 0xffffffff
#define BCHP_M2MC_LIST_PKT_04_SCALE_PARAM_N_REGISTER_CONTENTS_SHIFT 0

/***************************************************************************
 *LIST_PKT_05_BLEND_PARAM_N - Linked-List Packet Word N for group BLEND_PARAM
 ***************************************************************************/
/* M2MC :: LIST_PKT_05_BLEND_PARAM_N :: REGISTER_CONTENTS [31:00] */
#define BCHP_M2MC_LIST_PKT_05_BLEND_PARAM_N_REGISTER_CONTENTS_MASK 0xffffffff
#define BCHP_M2MC_LIST_PKT_05_BLEND_PARAM_N_REGISTER_CONTENTS_SHIFT 0

/***************************************************************************
 *LIST_PKT_06_ROP_N - Linked-List Packet Word N for group ROP
 ***************************************************************************/
/* M2MC :: LIST_PKT_06_ROP_N :: REGISTER_CONTENTS [31:00] */
#define BCHP_M2MC_LIST_PKT_06_ROP_N_REGISTER_CONTENTS_MASK         0xffffffff
#define BCHP_M2MC_LIST_PKT_06_ROP_N_REGISTER_CONTENTS_SHIFT        0

/***************************************************************************
 *LIST_PKT_07_SRC_COLOR_KEY_N - Linked-List Packet Word N for group SRC_COLOR_KEY
 ***************************************************************************/
/* M2MC :: LIST_PKT_07_SRC_COLOR_KEY_N :: REGISTER_CONTENTS [31:00] */
#define BCHP_M2MC_LIST_PKT_07_SRC_COLOR_KEY_N_REGISTER_CONTENTS_MASK 0xffffffff
#define BCHP_M2MC_LIST_PKT_07_SRC_COLOR_KEY_N_REGISTER_CONTENTS_SHIFT 0

/***************************************************************************
 *LIST_PKT_08_DST_COLOR_KEY_N - Linked-List Packet Word N for group DST_COLOR_KEY
 ***************************************************************************/
/* M2MC :: LIST_PKT_08_DST_COLOR_KEY_N :: REGISTER_CONTENTS [31:00] */
#define BCHP_M2MC_LIST_PKT_08_DST_COLOR_KEY_N_REGISTER_CONTENTS_MASK 0xffffffff
#define BCHP_M2MC_LIST_PKT_08_DST_COLOR_KEY_N_REGISTER_CONTENTS_SHIFT 0

/***************************************************************************
 *LIST_PKT_09_SCALE_COEF_N - Linked-List Packet Word N for group SCALE_COEF
 ***************************************************************************/
/* M2MC :: LIST_PKT_09_SCALE_COEF_N :: REGISTER_CONTENTS [31:00] */
#define BCHP_M2MC_LIST_PKT_09_SCALE_COEF_N_REGISTER_CONTENTS_MASK  0xffffffff
#define BCHP_M2MC_LIST_PKT_09_SCALE_COEF_N_REGISTER_CONTENTS_SHIFT 0

/***************************************************************************
 *LIST_PKT_10_SRC_COLOR_MATRIX_N - Linked-List Packet Word N for group SRC_COLOR_MATRIX
 ***************************************************************************/
/* M2MC :: LIST_PKT_10_SRC_COLOR_MATRIX_N :: REGISTER_CONTENTS [31:00] */
#define BCHP_M2MC_LIST_PKT_10_SRC_COLOR_MATRIX_N_REGISTER_CONTENTS_MASK 0xffffffff
#define BCHP_M2MC_LIST_PKT_10_SRC_COLOR_MATRIX_N_REGISTER_CONTENTS_SHIFT 0

/***************************************************************************
 *LIST_PKT_11_DST_COLOR_MATRIX_N - Linked-List Packet Word N for group DST_COLOR_MATRIX
 ***************************************************************************/
/* M2MC :: LIST_PKT_11_DST_COLOR_MATRIX_N :: REGISTER_CONTENTS [31:00] */
#define BCHP_M2MC_LIST_PKT_11_DST_COLOR_MATRIX_N_REGISTER_CONTENTS_MASK 0xffffffff
#define BCHP_M2MC_LIST_PKT_11_DST_COLOR_MATRIX_N_REGISTER_CONTENTS_SHIFT 0

/***************************************************************************
 *LIST_PKT_12_OUTPUT_COLOR_MATRIX_N - Linked-List Packet Word N for group OUTPUT_COLOR_MATRIX
 ***************************************************************************/
/* M2MC :: LIST_PKT_12_OUTPUT_COLOR_MATRIX_N :: REGISTER_CONTENTS [31:00] */
#define BCHP_M2MC_LIST_PKT_12_OUTPUT_COLOR_MATRIX_N_REGISTER_CONTENTS_MASK 0xffffffff
#define BCHP_M2MC_LIST_PKT_12_OUTPUT_COLOR_MATRIX_N_REGISTER_CONTENTS_SHIFT 0

/***************************************************************************
 *LIST_PKT_13_SRC_CLUT - Linked-List Packet Word for group SRC_CLUT
 ***************************************************************************/
/* M2MC :: LIST_PKT_13_SRC_CLUT :: reserved0 [31:29] */
#define BCHP_M2MC_LIST_PKT_13_SRC_CLUT_reserved0_MASK              0xe0000000
#define BCHP_M2MC_LIST_PKT_13_SRC_CLUT_reserved0_SHIFT             29

/* M2MC :: LIST_PKT_13_SRC_CLUT :: REGISTER_CONTENTS [28:00] */
#define BCHP_M2MC_LIST_PKT_13_SRC_CLUT_REGISTER_CONTENTS_MASK      0x1fffffff
#define BCHP_M2MC_LIST_PKT_13_SRC_CLUT_REGISTER_CONTENTS_SHIFT     0

/***************************************************************************
 *LIST_PKT_14_DST_CLUT - Linked-List Packet Word for group DST_CLUT
 ***************************************************************************/
/* M2MC :: LIST_PKT_14_DST_CLUT :: reserved0 [31:29] */
#define BCHP_M2MC_LIST_PKT_14_DST_CLUT_reserved0_MASK              0xe0000000
#define BCHP_M2MC_LIST_PKT_14_DST_CLUT_reserved0_SHIFT             29

/* M2MC :: LIST_PKT_14_DST_CLUT :: REGISTER_CONTENTS [28:00] */
#define BCHP_M2MC_LIST_PKT_14_DST_CLUT_REGISTER_CONTENTS_MASK      0x1fffffff
#define BCHP_M2MC_LIST_PKT_14_DST_CLUT_REGISTER_CONTENTS_SHIFT     0

/***************************************************************************
 *TYPE_CLUT_COLOR_DATA - color data for color look up table
 ***************************************************************************/
/* M2MC :: TYPE_CLUT_COLOR_DATA :: ALPHA [31:24] */
#define BCHP_M2MC_TYPE_CLUT_COLOR_DATA_ALPHA_MASK                  0xff000000
#define BCHP_M2MC_TYPE_CLUT_COLOR_DATA_ALPHA_SHIFT                 24

/* M2MC :: TYPE_CLUT_COLOR_DATA :: RED [23:16] */
#define BCHP_M2MC_TYPE_CLUT_COLOR_DATA_RED_MASK                    0x00ff0000
#define BCHP_M2MC_TYPE_CLUT_COLOR_DATA_RED_SHIFT                   16

/* M2MC :: TYPE_CLUT_COLOR_DATA :: GREEN [15:08] */
#define BCHP_M2MC_TYPE_CLUT_COLOR_DATA_GREEN_MASK                  0x0000ff00
#define BCHP_M2MC_TYPE_CLUT_COLOR_DATA_GREEN_SHIFT                 8

/* M2MC :: TYPE_CLUT_COLOR_DATA :: BLUE [07:00] */
#define BCHP_M2MC_TYPE_CLUT_COLOR_DATA_BLUE_MASK                   0x000000ff
#define BCHP_M2MC_TYPE_CLUT_COLOR_DATA_BLUE_SHIFT                  0

/***************************************************************************
 *MEM_DMA
 ***************************************************************************/
/***************************************************************************
 *DESC_WORD0 - MEM DMA Descriptor Word 0
 ***************************************************************************/
/* MEM_DMA :: DESC_WORD0 :: MODE_SEL [31:29] */
#define BCHP_MEM_DMA_DESC_WORD0_MODE_SEL_MASK                      0xe0000000
#define BCHP_MEM_DMA_DESC_WORD0_MODE_SEL_SHIFT                     29

/* MEM_DMA :: DESC_WORD0 :: ENC_DEC_INIT [28:28] */
#define BCHP_MEM_DMA_DESC_WORD0_ENC_DEC_INIT_MASK                  0x10000000
#define BCHP_MEM_DMA_DESC_WORD0_ENC_DEC_INIT_SHIFT                 28

/* MEM_DMA :: DESC_WORD0 :: READ_ADDR [27:00] */
#define BCHP_MEM_DMA_DESC_WORD0_READ_ADDR_MASK                     0x0fffffff
#define BCHP_MEM_DMA_DESC_WORD0_READ_ADDR_SHIFT                    0

/***************************************************************************
 *DESC_WORD1 - MEM DMA Descriptor Word 1
 ***************************************************************************/
/* MEM_DMA :: DESC_WORD1 :: ALOGRITHM_SEL [31:28] */
#define BCHP_MEM_DMA_DESC_WORD1_ALOGRITHM_SEL_MASK                 0xf0000000
#define BCHP_MEM_DMA_DESC_WORD1_ALOGRITHM_SEL_SHIFT                28

/* MEM_DMA :: DESC_WORD1 :: WRITE_ADDR [27:00] */
#define BCHP_MEM_DMA_DESC_WORD1_WRITE_ADDR_MASK                    0x0fffffff
#define BCHP_MEM_DMA_DESC_WORD1_WRITE_ADDR_SHIFT                   0

/***************************************************************************
 *DESC_WORD2 - MEM DMA Descriptor Word 2
 ***************************************************************************/
/* MEM_DMA :: DESC_WORD2 :: INTR_ENABLE [31:31] */
#define BCHP_MEM_DMA_DESC_WORD2_INTR_ENABLE_MASK                   0x80000000
#define BCHP_MEM_DMA_DESC_WORD2_INTR_ENABLE_SHIFT                  31

/* MEM_DMA :: DESC_WORD2 :: LAST [30:30] */
#define BCHP_MEM_DMA_DESC_WORD2_LAST_MASK                          0x40000000
#define BCHP_MEM_DMA_DESC_WORD2_LAST_SHIFT                         30

/* MEM_DMA :: DESC_WORD2 :: KEY_SELECT [29:26] */
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_MASK                    0x3c000000
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_SHIFT                   26
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_KEY0                    0
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_KEY1                    1
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_KEY2                    2
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_KEY3                    3
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_KEY4                    4
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_KEY5                    5
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_KEY6                    6
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_KEY7                    7
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_KEY8                    8
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_KEY9                    9
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_KEY10                   10
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_KEY11                   11
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_KEY12                   12
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_KEY13                   13
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_KEY14                   14
#define BCHP_MEM_DMA_DESC_WORD2_KEY_SELECT_KEY15                   15

/* MEM_DMA :: DESC_WORD2 :: reserved0 [25:25] */
#define BCHP_MEM_DMA_DESC_WORD2_reserved0_MASK                     0x02000000
#define BCHP_MEM_DMA_DESC_WORD2_reserved0_SHIFT                    25

/* MEM_DMA :: DESC_WORD2 :: TRANSFER_SIZE [24:00] */
#define BCHP_MEM_DMA_DESC_WORD2_TRANSFER_SIZE_MASK                 0x01ffffff
#define BCHP_MEM_DMA_DESC_WORD2_TRANSFER_SIZE_SHIFT                0

/***************************************************************************
 *DESC_WORD3 - MEM DMA Descriptor Word 3
 ***************************************************************************/
/* MEM_DMA :: DESC_WORD3 :: DATA_OPERATION [31:31] */
#define BCHP_MEM_DMA_DESC_WORD3_DATA_OPERATION_MASK                0x80000000
#define BCHP_MEM_DMA_DESC_WORD3_DATA_OPERATION_SHIFT               31
#define BCHP_MEM_DMA_DESC_WORD3_DATA_OPERATION_Disable             0
#define BCHP_MEM_DMA_DESC_WORD3_DATA_OPERATION_Enable              1

/* MEM_DMA :: DESC_WORD3 :: ENCRYPT_DECRYPT_SEL [30:30] */
#define BCHP_MEM_DMA_DESC_WORD3_ENCRYPT_DECRYPT_SEL_MASK           0x40000000
#define BCHP_MEM_DMA_DESC_WORD3_ENCRYPT_DECRYPT_SEL_SHIFT          30
#define BCHP_MEM_DMA_DESC_WORD3_ENCRYPT_DECRYPT_SEL_Encryption     0
#define BCHP_MEM_DMA_DESC_WORD3_ENCRYPT_DECRYPT_SEL_Decryption     1

/* MEM_DMA :: DESC_WORD3 :: DES_3DES_SEL [29:29] */
#define BCHP_MEM_DMA_DESC_WORD3_DES_3DES_SEL_MASK                  0x20000000
#define BCHP_MEM_DMA_DESC_WORD3_DES_3DES_SEL_SHIFT                 29

/* MEM_DMA :: DESC_WORD3 :: reserved0 [28:28] */
#define BCHP_MEM_DMA_DESC_WORD3_reserved0_MASK                     0x10000000
#define BCHP_MEM_DMA_DESC_WORD3_reserved0_SHIFT                    28

/* MEM_DMA :: DESC_WORD3 :: NEXT_DESC_ADDR [27:04] */
#define BCHP_MEM_DMA_DESC_WORD3_NEXT_DESC_ADDR_MASK                0x0ffffff0
#define BCHP_MEM_DMA_DESC_WORD3_NEXT_DESC_ADDR_SHIFT               4

/* MEM_DMA :: DESC_WORD3 :: reserved1 [03:03] */
#define BCHP_MEM_DMA_DESC_WORD3_reserved1_MASK                     0x00000008
#define BCHP_MEM_DMA_DESC_WORD3_reserved1_SHIFT                    3

/* MEM_DMA :: DESC_WORD3 :: READ_ENDIAN_MODE [02:02] */
#define BCHP_MEM_DMA_DESC_WORD3_READ_ENDIAN_MODE_MASK              0x00000004
#define BCHP_MEM_DMA_DESC_WORD3_READ_ENDIAN_MODE_SHIFT             2
#define BCHP_MEM_DMA_DESC_WORD3_READ_ENDIAN_MODE_BIG_ENDIAN        0
#define BCHP_MEM_DMA_DESC_WORD3_READ_ENDIAN_MODE_LITTLE_ENDIAN     1

/* MEM_DMA :: DESC_WORD3 :: WRITE_ENDIAN_XLATE_MODE [01:00] */
#define BCHP_MEM_DMA_DESC_WORD3_WRITE_ENDIAN_XLATE_MODE_MASK       0x00000003
#define BCHP_MEM_DMA_DESC_WORD3_WRITE_ENDIAN_XLATE_MODE_SHIFT      0
#define BCHP_MEM_DMA_DESC_WORD3_WRITE_ENDIAN_XLATE_MODE_WORD_ALIGNED 0
#define BCHP_MEM_DMA_DESC_WORD3_WRITE_ENDIAN_XLATE_MODE_HALF_WORD_ALIGNED 1
#define BCHP_MEM_DMA_DESC_WORD3_WRITE_ENDIAN_XLATE_MODE_BYTE_ALIGNED 2
#define BCHP_MEM_DMA_DESC_WORD3_WRITE_ENDIAN_XLATE_MODE_reserved   3

/***************************************************************************
 *PCI
 ***************************************************************************/
/***************************************************************************
 *DMA_DESC_WORD0 - PDD_WORD0
 ***************************************************************************/
/* PCI :: DMA_DESC_WORD0 :: reserved0 [31:28] */
#define BCHP_PCI_DMA_DESC_WORD0_reserved0_MASK                     0xf0000000
#define BCHP_PCI_DMA_DESC_WORD0_reserved0_SHIFT                    28

/* PCI :: DMA_DESC_WORD0 :: MEMORY_ADDRESS [27:00] */
#define BCHP_PCI_DMA_DESC_WORD0_MEMORY_ADDRESS_MASK                0x0fffffff
#define BCHP_PCI_DMA_DESC_WORD0_MEMORY_ADDRESS_SHIFT               0

/***************************************************************************
 *DMA_DESC_WORD1 - PDD_WORD1
 ***************************************************************************/
/* PCI :: DMA_DESC_WORD1 :: PCI_ADDRESS [31:00] */
#define BCHP_PCI_DMA_DESC_WORD1_PCI_ADDRESS_MASK                   0xffffffff
#define BCHP_PCI_DMA_DESC_WORD1_PCI_ADDRESS_SHIFT                  0

/***************************************************************************
 *DMA_DESC_WORD2 - PDD_WORD2
 ***************************************************************************/
/* PCI :: DMA_DESC_WORD2 :: INTERRUPT_ENABLE [31:31] */
#define BCHP_PCI_DMA_DESC_WORD2_INTERRUPT_ENABLE_MASK              0x80000000
#define BCHP_PCI_DMA_DESC_WORD2_INTERRUPT_ENABLE_SHIFT             31

/* PCI :: DMA_DESC_WORD2 :: DMA_DIRECTION [30:30] */
#define BCHP_PCI_DMA_DESC_WORD2_DMA_DIRECTION_MASK                 0x40000000
#define BCHP_PCI_DMA_DESC_WORD2_DMA_DIRECTION_SHIFT                30
#define BCHP_PCI_DMA_DESC_WORD2_DMA_DIRECTION_PCI_TO_MEMORY        1
#define BCHP_PCI_DMA_DESC_WORD2_DMA_DIRECTION_MEMORY_TO_PCI        0

/* PCI :: DMA_DESC_WORD2 :: reserved0 [29:25] */
#define BCHP_PCI_DMA_DESC_WORD2_reserved0_MASK                     0x3e000000
#define BCHP_PCI_DMA_DESC_WORD2_reserved0_SHIFT                    25

/* PCI :: DMA_DESC_WORD2 :: DMA_TRANSFER_SIZE [24:00] */
#define BCHP_PCI_DMA_DESC_WORD2_DMA_TRANSFER_SIZE_MASK             0x01ffffff
#define BCHP_PCI_DMA_DESC_WORD2_DMA_TRANSFER_SIZE_SHIFT            0

/***************************************************************************
 *DMA_DESC_WORD3 - PDD_WORD3
 ***************************************************************************/
/* PCI :: DMA_DESC_WORD3 :: LAST_RECORD_INDICATOR [31:31] */
#define BCHP_PCI_DMA_DESC_WORD3_LAST_RECORD_INDICATOR_MASK         0x80000000
#define BCHP_PCI_DMA_DESC_WORD3_LAST_RECORD_INDICATOR_SHIFT        31

/* PCI :: DMA_DESC_WORD3 :: reserved0 [30:28] */
#define BCHP_PCI_DMA_DESC_WORD3_reserved0_MASK                     0x70000000
#define BCHP_PCI_DMA_DESC_WORD3_reserved0_SHIFT                    28

/* PCI :: DMA_DESC_WORD3 :: NEXT_DESC_ADDR [27:04] */
#define BCHP_PCI_DMA_DESC_WORD3_NEXT_DESC_ADDR_MASK                0x0ffffff0
#define BCHP_PCI_DMA_DESC_WORD3_NEXT_DESC_ADDR_SHIFT               4

/* PCI :: DMA_DESC_WORD3 :: reserved1 [03:02] */
#define BCHP_PCI_DMA_DESC_WORD3_reserved1_MASK                     0x0000000c
#define BCHP_PCI_DMA_DESC_WORD3_reserved1_SHIFT                    2

/* PCI :: DMA_DESC_WORD3 :: ENDIAN_XLATE_MODE [01:00] */
#define BCHP_PCI_DMA_DESC_WORD3_ENDIAN_XLATE_MODE_MASK             0x00000003
#define BCHP_PCI_DMA_DESC_WORD3_ENDIAN_XLATE_MODE_SHIFT            0
#define BCHP_PCI_DMA_DESC_WORD3_ENDIAN_XLATE_MODE_NO_SWAP          0
#define BCHP_PCI_DMA_DESC_WORD3_ENDIAN_XLATE_MODE_SWAP_16_IN_32    1
#define BCHP_PCI_DMA_DESC_WORD3_ENDIAN_XLATE_MODE_SWAP_32          2
#define BCHP_PCI_DMA_DESC_WORD3_ENDIAN_XLATE_MODE_reserved         3

/***************************************************************************
 *PCM
 ***************************************************************************/
/***************************************************************************
 *DESCRIPTOR_WORD0 - Descriptor Word0
 ***************************************************************************/
/* PCM :: DESCRIPTOR_WORD0 :: reserved0 [31:28] */
#define BCHP_PCM_DESCRIPTOR_WORD0_reserved0_MASK                   0xf0000000
#define BCHP_PCM_DESCRIPTOR_WORD0_reserved0_SHIFT                  28

/* PCM :: DESCRIPTOR_WORD0 :: SDRAM_BUF_ADRS [27:04] */
#define BCHP_PCM_DESCRIPTOR_WORD0_SDRAM_BUF_ADRS_MASK              0x0ffffff0
#define BCHP_PCM_DESCRIPTOR_WORD0_SDRAM_BUF_ADRS_SHIFT             4

/* PCM :: DESCRIPTOR_WORD0 :: reserved1 [03:00] */
#define BCHP_PCM_DESCRIPTOR_WORD0_reserved1_MASK                   0x0000000f
#define BCHP_PCM_DESCRIPTOR_WORD0_reserved1_SHIFT                  0

/***************************************************************************
 *DESCRIPTOR_WORD1 - Descriptor Word1
 ***************************************************************************/
/* PCM :: DESCRIPTOR_WORD1 :: reserved0 [31:24] */
#define BCHP_PCM_DESCRIPTOR_WORD1_reserved0_MASK                   0xff000000
#define BCHP_PCM_DESCRIPTOR_WORD1_reserved0_SHIFT                  24

/* PCM :: DESCRIPTOR_WORD1 :: BUFFER_SIZE [23:00] */
#define BCHP_PCM_DESCRIPTOR_WORD1_BUFFER_SIZE_MASK                 0x00ffffff
#define BCHP_PCM_DESCRIPTOR_WORD1_BUFFER_SIZE_SHIFT                0

/***************************************************************************
 *DESCRIPTOR_WORD2 - Descriptor Word2
 ***************************************************************************/
/* PCM :: DESCRIPTOR_WORD2 :: reserved0 [31:25] */
#define BCHP_PCM_DESCRIPTOR_WORD2_reserved0_MASK                   0xfe000000
#define BCHP_PCM_DESCRIPTOR_WORD2_reserved0_SHIFT                  25

/* PCM :: DESCRIPTOR_WORD2 :: INTR_ENABLE [24:24] */
#define BCHP_PCM_DESCRIPTOR_WORD2_INTR_ENABLE_MASK                 0x01000000
#define BCHP_PCM_DESCRIPTOR_WORD2_INTR_ENABLE_SHIFT                24

/* PCM :: DESCRIPTOR_WORD2 :: TRIGGER_COUNT [23:00] */
#define BCHP_PCM_DESCRIPTOR_WORD2_TRIGGER_COUNT_MASK               0x00ffffff
#define BCHP_PCM_DESCRIPTOR_WORD2_TRIGGER_COUNT_SHIFT              0

/***************************************************************************
 *DESCRIPTOR_WORD3 - Descriptor Word3
 ***************************************************************************/
/* PCM :: DESCRIPTOR_WORD3 :: LAST_DESC_FLAG [31:31] */
#define BCHP_PCM_DESCRIPTOR_WORD3_LAST_DESC_FLAG_MASK              0x80000000
#define BCHP_PCM_DESCRIPTOR_WORD3_LAST_DESC_FLAG_SHIFT             31

/* PCM :: DESCRIPTOR_WORD3 :: reserved0 [30:28] */
#define BCHP_PCM_DESCRIPTOR_WORD3_reserved0_MASK                   0x70000000
#define BCHP_PCM_DESCRIPTOR_WORD3_reserved0_SHIFT                  28

/* PCM :: DESCRIPTOR_WORD3 :: NEXT_DESC_ADRS [27:04] */
#define BCHP_PCM_DESCRIPTOR_WORD3_NEXT_DESC_ADRS_MASK              0x0ffffff0
#define BCHP_PCM_DESCRIPTOR_WORD3_NEXT_DESC_ADRS_SHIFT             4

/* PCM :: DESCRIPTOR_WORD3 :: reserved1 [03:00] */
#define BCHP_PCM_DESCRIPTOR_WORD3_reserved1_MASK                   0x0000000f
#define BCHP_PCM_DESCRIPTOR_WORD3_reserved1_SHIFT                  0

/***************************************************************************
 *PX3D
 ***************************************************************************/
/***************************************************************************
 *Type_PrimHeaderA - Prim Header A
 ***************************************************************************/
/* PX3D :: Type_PrimHeaderA :: PrimitiveType [31:30] */
#define BCHP_PX3D_Type_PrimHeaderA_PrimitiveType_MASK              0xc0000000
#define BCHP_PX3D_Type_PrimHeaderA_PrimitiveType_SHIFT             30

/* PX3D :: Type_PrimHeaderA :: AlphaEnable [29:29] */
#define BCHP_PX3D_Type_PrimHeaderA_AlphaEnable_MASK                0x20000000
#define BCHP_PX3D_Type_PrimHeaderA_AlphaEnable_SHIFT               29

/* PX3D :: Type_PrimHeaderA :: TextureEnable [28:28] */
#define BCHP_PX3D_Type_PrimHeaderA_TextureEnable_MASK              0x10000000
#define BCHP_PX3D_Type_PrimHeaderA_TextureEnable_SHIFT             28

/* PX3D :: Type_PrimHeaderA :: Opaque [27:27] */
#define BCHP_PX3D_Type_PrimHeaderA_Opaque_MASK                     0x08000000
#define BCHP_PX3D_Type_PrimHeaderA_Opaque_SHIFT                    27

/* PX3D :: Type_PrimHeaderA :: MIPData [26:26] */
#define BCHP_PX3D_Type_PrimHeaderA_MIPData_MASK                    0x04000000
#define BCHP_PX3D_Type_PrimHeaderA_MIPData_SHIFT                   26

/* PX3D :: Type_PrimHeaderA :: TextureSizeS [25:23] */
#define BCHP_PX3D_Type_PrimHeaderA_TextureSizeS_MASK               0x03800000
#define BCHP_PX3D_Type_PrimHeaderA_TextureSizeS_SHIFT              23

/* PX3D :: Type_PrimHeaderA :: TextureSizeT [22:20] */
#define BCHP_PX3D_Type_PrimHeaderA_TextureSizeT_MASK               0x00700000
#define BCHP_PX3D_Type_PrimHeaderA_TextureSizeT_SHIFT              20

/* PX3D :: Type_PrimHeaderA :: AlphaCompare [19:17] */
#define BCHP_PX3D_Type_PrimHeaderA_AlphaCompare_MASK               0x000e0000
#define BCHP_PX3D_Type_PrimHeaderA_AlphaCompare_SHIFT              17

/* PX3D :: Type_PrimHeaderA :: CantBeBlocked [16:16] */
#define BCHP_PX3D_Type_PrimHeaderA_CantBeBlocked_MASK              0x00010000
#define BCHP_PX3D_Type_PrimHeaderA_CantBeBlocked_SHIFT             16

/* PX3D :: Type_PrimHeaderA :: SpecularEnable [15:15] */
#define BCHP_PX3D_Type_PrimHeaderA_SpecularEnable_MASK             0x00008000
#define BCHP_PX3D_Type_PrimHeaderA_SpecularEnable_SHIFT            15

/* PX3D :: Type_PrimHeaderA :: TextureBlend [14:12] */
#define BCHP_PX3D_Type_PrimHeaderA_TextureBlend_MASK               0x00007000
#define BCHP_PX3D_Type_PrimHeaderA_TextureBlend_SHIFT              12

/* PX3D :: Type_PrimHeaderA :: SrcAlphaBlend [11:08] */
#define BCHP_PX3D_Type_PrimHeaderA_SrcAlphaBlend_MASK              0x00000f00
#define BCHP_PX3D_Type_PrimHeaderA_SrcAlphaBlend_SHIFT             8

/* PX3D :: Type_PrimHeaderA :: DstAlphaBlend [07:05] */
#define BCHP_PX3D_Type_PrimHeaderA_DstAlphaBlend_MASK              0x000000e0
#define BCHP_PX3D_Type_PrimHeaderA_DstAlphaBlend_SHIFT             5

/* PX3D :: Type_PrimHeaderA :: Fog [04:03] */
#define BCHP_PX3D_Type_PrimHeaderA_Fog_MASK                        0x00000018
#define BCHP_PX3D_Type_PrimHeaderA_Fog_SHIFT                       3

/* PX3D :: Type_PrimHeaderA :: TexelFormat [02:00] */
#define BCHP_PX3D_Type_PrimHeaderA_TexelFormat_MASK                0x00000007
#define BCHP_PX3D_Type_PrimHeaderA_TexelFormat_SHIFT               0

/***************************************************************************
 *Type_PrimHeaderB - Prim Header B
 ***************************************************************************/
/* PX3D :: Type_PrimHeaderB :: reserved0 [31:24] */
#define BCHP_PX3D_Type_PrimHeaderB_reserved0_MASK                  0xff000000
#define BCHP_PX3D_Type_PrimHeaderB_reserved0_SHIFT                 24

/* PX3D :: Type_PrimHeaderB :: DepthMask [23:23] */
#define BCHP_PX3D_Type_PrimHeaderB_DepthMask_MASK                  0x00800000
#define BCHP_PX3D_Type_PrimHeaderB_DepthMask_SHIFT                 23

/* PX3D :: Type_PrimHeaderB :: ZCompare [22:20] */
#define BCHP_PX3D_Type_PrimHeaderB_ZCompare_MASK                   0x00700000
#define BCHP_PX3D_Type_PrimHeaderB_ZCompare_SHIFT                  20

/* PX3D :: Type_PrimHeaderB :: reserved1 [19:16] */
#define BCHP_PX3D_Type_PrimHeaderB_reserved1_MASK                  0x000f0000
#define BCHP_PX3D_Type_PrimHeaderB_reserved1_SHIFT                 16

/* PX3D :: Type_PrimHeaderB :: AppPriority [15:00] */
#define BCHP_PX3D_Type_PrimHeaderB_AppPriority_MASK                0x0000ffff
#define BCHP_PX3D_Type_PrimHeaderB_AppPriority_SHIFT               0

/***************************************************************************
 *Type_TextureAddr - Texture Address
 ***************************************************************************/
/* PX3D :: Type_TextureAddr :: reserved0 [31:31] */
#define BCHP_PX3D_Type_TextureAddr_reserved0_MASK                  0x80000000
#define BCHP_PX3D_Type_TextureAddr_reserved0_SHIFT                 31

/* PX3D :: Type_TextureAddr :: SampleTexelCenter [30:30] */
#define BCHP_PX3D_Type_TextureAddr_SampleTexelCenter_MASK          0x40000000
#define BCHP_PX3D_Type_TextureAddr_SampleTexelCenter_SHIFT         30

/* PX3D :: Type_TextureAddr :: ColorKeySelect [29:28] */
#define BCHP_PX3D_Type_TextureAddr_ColorKeySelect_MASK             0x30000000
#define BCHP_PX3D_Type_TextureAddr_ColorKeySelect_SHIFT            28

/* PX3D :: Type_TextureAddr :: WrapType [27:26] */
#define BCHP_PX3D_Type_TextureAddr_WrapType_MASK                   0x0c000000
#define BCHP_PX3D_Type_TextureAddr_WrapType_SHIFT                  26

/* PX3D :: Type_TextureAddr :: TextureAddr [25:02] */
#define BCHP_PX3D_Type_TextureAddr_TextureAddr_MASK                0x03fffffc
#define BCHP_PX3D_Type_TextureAddr_TextureAddr_SHIFT               2

/* PX3D :: Type_TextureAddr :: Swizzled [01:01] */
#define BCHP_PX3D_Type_TextureAddr_Swizzled_MASK                   0x00000002
#define BCHP_PX3D_Type_TextureAddr_Swizzled_SHIFT                  1

/* PX3D :: Type_TextureAddr :: InterpType [00:00] */
#define BCHP_PX3D_Type_TextureAddr_InterpType_MASK                 0x00000001
#define BCHP_PX3D_Type_TextureAddr_InterpType_SHIFT                0

/***************************************************************************
 *RDC
 ***************************************************************************/
/***************************************************************************
 *RUL - RUL Command.
 ***************************************************************************/
/* RDC :: RUL :: opcode [31:24] */
#define BCHP_RDC_RUL_opcode_MASK                                   0xff000000
#define BCHP_RDC_RUL_opcode_SHIFT                                  24
#define BCHP_RDC_RUL_opcode_NOP                                    0
#define BCHP_RDC_RUL_opcode_REG_WRITE_IMM                          1
#define BCHP_RDC_RUL_opcode_REG_WRITE                              2
#define BCHP_RDC_RUL_opcode_REG_READ                               3
#define BCHP_RDC_RUL_opcode_LOAD_IMM                               4
#define BCHP_RDC_RUL_opcode_WINDOW_WRITE                           5
#define BCHP_RDC_RUL_opcode_BLOCK_WRITE                            6
#define BCHP_RDC_RUL_opcode_WINDOW_COPY                            7
#define BCHP_RDC_RUL_opcode_BLOCK_COPY                             8
#define BCHP_RDC_RUL_opcode_WINDOW_TO_BLOCK                        9
#define BCHP_RDC_RUL_opcode_BLOCK_TO_WINDOW                        10
#define BCHP_RDC_RUL_opcode_AND                                    11
#define BCHP_RDC_RUL_opcode_AND_IMM                                12
#define BCHP_RDC_RUL_opcode_OR                                     13
#define BCHP_RDC_RUL_opcode_OR_IMM                                 14
#define BCHP_RDC_RUL_opcode_XOR                                    15
#define BCHP_RDC_RUL_opcode_XOR_IMM                                16
#define BCHP_RDC_RUL_opcode_NOT                                    17
#define BCHP_RDC_RUL_opcode_ROTATE_RIGHT                           18
#define BCHP_RDC_RUL_opcode_SUM                                    19
#define BCHP_RDC_RUL_opcode_SUM_IMM                                20
#define BCHP_RDC_RUL_opcode_PLACEHOLDER                            255

/* RDC :: RUL :: reserved0 [23:23] */
#define BCHP_RDC_RUL_reserved0_MASK                                0x00800000
#define BCHP_RDC_RUL_reserved0_SHIFT                               23

/* union - case rdc_args [22:00] */
/* RDC :: RUL :: rdc_args :: rotation [22:18] */
#define BCHP_RDC_RUL_rdc_args_rotation_MASK                        0x007c0000
#define BCHP_RDC_RUL_rdc_args_rotation_SHIFT                       18

/* RDC :: RUL :: rdc_args :: src1 [17:12] */
#define BCHP_RDC_RUL_rdc_args_src1_MASK                            0x0003f000
#define BCHP_RDC_RUL_rdc_args_src1_SHIFT                           12

/* RDC :: RUL :: rdc_args :: src2 [11:06] */
#define BCHP_RDC_RUL_rdc_args_src2_MASK                            0x00000fc0
#define BCHP_RDC_RUL_rdc_args_src2_SHIFT                           6

/* RDC :: RUL :: rdc_args :: dest [05:00] */
#define BCHP_RDC_RUL_rdc_args_dest_MASK                            0x0000003f
#define BCHP_RDC_RUL_rdc_args_dest_SHIFT                           0

/* union - case reg_args [22:00] */
/* RDC :: RUL :: reg_args :: rotation [22:18] */
#define BCHP_RDC_RUL_reg_args_rotation_MASK                        0x007c0000
#define BCHP_RDC_RUL_reg_args_rotation_SHIFT                       18

/* RDC :: RUL :: reg_args :: src1 [17:12] */
#define BCHP_RDC_RUL_reg_args_src1_MASK                            0x0003f000
#define BCHP_RDC_RUL_reg_args_src1_SHIFT                           12

/* RDC :: RUL :: reg_args :: count [11:00] */
#define BCHP_RDC_RUL_reg_args_count_MASK                           0x00000fff
#define BCHP_RDC_RUL_reg_args_count_SHIFT                          0

/***************************************************************************
 *XPT_PB
 ***************************************************************************/
/***************************************************************************
 *DESCRIPTOR_ABSTRACT - Playback Linked-List Descriptor Abstract
 ***************************************************************************/
/* XPT_PB :: DESCRIPTOR_ABSTRACT :: DESCRIPTOR_FORMAT [31:00] */
#define BCHP_XPT_PB_DESCRIPTOR_ABSTRACT_DESCRIPTOR_FORMAT_MASK     0xffffffff
#define BCHP_XPT_PB_DESCRIPTOR_ABSTRACT_DESCRIPTOR_FORMAT_SHIFT    0

/***************************************************************************
 *DESC_0 - Playback Linked-List Descriptor Word 0
 ***************************************************************************/
/* XPT_PB :: DESC_0 :: reserved0 [31:27] */
#define BCHP_XPT_PB_DESC_0_reserved0_MASK                          0xf8000000
#define BCHP_XPT_PB_DESC_0_reserved0_SHIFT                         27

/* XPT_PB :: DESC_0 :: PB_BUFFER_START_ADDR [26:00] */
#define BCHP_XPT_PB_DESC_0_PB_BUFFER_START_ADDR_MASK               0x07ffffff
#define BCHP_XPT_PB_DESC_0_PB_BUFFER_START_ADDR_SHIFT              0

/***************************************************************************
 *DESC_1 - Playback Linked-List Descriptor Word 1
 ***************************************************************************/
/* XPT_PB :: DESC_1 :: reserved0 [31:27] */
#define BCHP_XPT_PB_DESC_1_reserved0_MASK                          0xf8000000
#define BCHP_XPT_PB_DESC_1_reserved0_SHIFT                         27

/* XPT_PB :: DESC_1 :: PB_BUFFER_LENGTH [26:00] */
#define BCHP_XPT_PB_DESC_1_PB_BUFFER_LENGTH_MASK                   0x07ffffff
#define BCHP_XPT_PB_DESC_1_PB_BUFFER_LENGTH_SHIFT                  0

/***************************************************************************
 *DESC_2 - Playback Linked-List Descriptor Word 2
 ***************************************************************************/
/* XPT_PB :: DESC_2 :: PB_INTERRUPT_ENABLE [31:31] */
#define BCHP_XPT_PB_DESC_2_PB_INTERRUPT_ENABLE_MASK                0x80000000
#define BCHP_XPT_PB_DESC_2_PB_INTERRUPT_ENABLE_SHIFT               31

/* XPT_PB :: DESC_2 :: PB_FORCE_RESYNC [30:30] */
#define BCHP_XPT_PB_DESC_2_PB_FORCE_RESYNC_MASK                    0x40000000
#define BCHP_XPT_PB_DESC_2_PB_FORCE_RESYNC_SHIFT                   30

/* XPT_PB :: DESC_2 :: reserved0 [29:00] */
#define BCHP_XPT_PB_DESC_2_reserved0_MASK                          0x3fffffff
#define BCHP_XPT_PB_DESC_2_reserved0_SHIFT                         0

/***************************************************************************
 *DESC_3 - Playback Linked-List Descriptor Word 3
 ***************************************************************************/
/* XPT_PB :: DESC_3 :: reserved0 [31:27] */
#define BCHP_XPT_PB_DESC_3_reserved0_MASK                          0xf8000000
#define BCHP_XPT_PB_DESC_3_reserved0_SHIFT                         27

/* XPT_PB :: DESC_3 :: PB_NEXT_DESC_ADDR [26:04] */
#define BCHP_XPT_PB_DESC_3_PB_NEXT_DESC_ADDR_MASK                  0x07fffff0
#define BCHP_XPT_PB_DESC_3_PB_NEXT_DESC_ADDR_SHIFT                 4

/* XPT_PB :: DESC_3 :: reserved1 [03:01] */
#define BCHP_XPT_PB_DESC_3_reserved1_MASK                          0x0000000e
#define BCHP_XPT_PB_DESC_3_reserved1_SHIFT                         1

/* XPT_PB :: DESC_3 :: PB_LAST_DESC_IND [00:00] */
#define BCHP_XPT_PB_DESC_3_PB_LAST_DESC_IND_MASK                   0x00000001
#define BCHP_XPT_PB_DESC_3_PB_LAST_DESC_IND_SHIFT                  0

/***************************************************************************
 *XPT_REC
 ***************************************************************************/
/***************************************************************************
 *DESCRIPTOR_ABSTRACT - Record Linked-List Descriptor Abstract
 ***************************************************************************/
/* XPT_REC :: DESCRIPTOR_ABSTRACT :: DESCRIPTOR_FORMAT [31:00] */
#define BCHP_XPT_REC_DESCRIPTOR_ABSTRACT_DESCRIPTOR_FORMAT_MASK    0xffffffff
#define BCHP_XPT_REC_DESCRIPTOR_ABSTRACT_DESCRIPTOR_FORMAT_SHIFT   0

/***************************************************************************
 *DESC_0 - Record Linked-List Descriptor Word 0
 ***************************************************************************/
/* XPT_REC :: DESC_0 :: reserved0 [31:27] */
#define BCHP_XPT_REC_DESC_0_reserved0_MASK                         0xf8000000
#define BCHP_XPT_REC_DESC_0_reserved0_SHIFT                        27

/* XPT_REC :: DESC_0 :: REC_BUFFER_START_ADDR [26:02] */
#define BCHP_XPT_REC_DESC_0_REC_BUFFER_START_ADDR_MASK             0x07fffffc
#define BCHP_XPT_REC_DESC_0_REC_BUFFER_START_ADDR_SHIFT            2

/* XPT_REC :: DESC_0 :: reserved1 [01:00] */
#define BCHP_XPT_REC_DESC_0_reserved1_MASK                         0x00000003
#define BCHP_XPT_REC_DESC_0_reserved1_SHIFT                        0

/***************************************************************************
 *DESC_1 - Record Linked-List Descriptor Word 1
 ***************************************************************************/
/* XPT_REC :: DESC_1 :: reserved0 [31:27] */
#define BCHP_XPT_REC_DESC_1_reserved0_MASK                         0xf8000000
#define BCHP_XPT_REC_DESC_1_reserved0_SHIFT                        27

/* XPT_REC :: DESC_1 :: REC_BUFFER_LENGTH [26:02] */
#define BCHP_XPT_REC_DESC_1_REC_BUFFER_LENGTH_MASK                 0x07fffffc
#define BCHP_XPT_REC_DESC_1_REC_BUFFER_LENGTH_SHIFT                2

/* XPT_REC :: DESC_1 :: reserved1 [01:00] */
#define BCHP_XPT_REC_DESC_1_reserved1_MASK                         0x00000003
#define BCHP_XPT_REC_DESC_1_reserved1_SHIFT                        0

/***************************************************************************
 *DESC_2 - Record Linked-List Descriptor Word 2
 ***************************************************************************/
/* XPT_REC :: DESC_2 :: REC_INTERRUPT_ENABLE [31:31] */
#define BCHP_XPT_REC_DESC_2_REC_INTERRUPT_ENABLE_MASK              0x80000000
#define BCHP_XPT_REC_DESC_2_REC_INTERRUPT_ENABLE_SHIFT             31

/* XPT_REC :: DESC_2 :: reserved0 [30:00] */
#define BCHP_XPT_REC_DESC_2_reserved0_MASK                         0x7fffffff
#define BCHP_XPT_REC_DESC_2_reserved0_SHIFT                        0

/***************************************************************************
 *DESC_3 - Record Linked-List Descriptor Word 3
 ***************************************************************************/
/* XPT_REC :: DESC_3 :: reserved0 [31:27] */
#define BCHP_XPT_REC_DESC_3_reserved0_MASK                         0xf8000000
#define BCHP_XPT_REC_DESC_3_reserved0_SHIFT                        27

/* XPT_REC :: DESC_3 :: REC_NEXT_DESC_ADDR [26:04] */
#define BCHP_XPT_REC_DESC_3_REC_NEXT_DESC_ADDR_MASK                0x07fffff0
#define BCHP_XPT_REC_DESC_3_REC_NEXT_DESC_ADDR_SHIFT               4

/* XPT_REC :: DESC_3 :: reserved1 [03:01] */
#define BCHP_XPT_REC_DESC_3_reserved1_MASK                         0x0000000e
#define BCHP_XPT_REC_DESC_3_reserved1_SHIFT                        1

/* XPT_REC :: DESC_3 :: REC_LAST_DESC_IND [00:00] */
#define BCHP_XPT_REC_DESC_3_REC_LAST_DESC_IND_MASK                 0x00000001
#define BCHP_XPT_REC_DESC_3_REC_LAST_DESC_IND_SHIFT                0

/***************************************************************************
 *INDEX_TABLE_ABSTRACT - Index Table Abstract
 ***************************************************************************/
/* XPT_REC :: INDEX_TABLE_ABSTRACT :: INDEX_ENTRY_FORMAT [31:00] */
#define BCHP_XPT_REC_INDEX_TABLE_ABSTRACT_INDEX_ENTRY_FORMAT_MASK  0xffffffff
#define BCHP_XPT_REC_INDEX_TABLE_ABSTRACT_INDEX_ENTRY_FORMAT_SHIFT 0

/***************************************************************************
 *PTS_INDEX_ENTRY_0 - Presentation Time Stamp Index Entry Word 0
 ***************************************************************************/
/* XPT_REC :: PTS_INDEX_ENTRY_0 :: PTS_ENTRY_TYPE [31:24] */
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_0_PTS_ENTRY_TYPE_MASK         0xff000000
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_0_PTS_ENTRY_TYPE_SHIFT        24

/* XPT_REC :: PTS_INDEX_ENTRY_0 :: SC_TIMESTAMP_LO [23:00] */
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_0_SC_TIMESTAMP_LO_MASK        0x00ffffff
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_0_SC_TIMESTAMP_LO_SHIFT       0

/***************************************************************************
 *PTS_INDEX_ENTRY_1 - Presentation Time Stamp Index Entry Word 1
 ***************************************************************************/
/* XPT_REC :: PTS_INDEX_ENTRY_1 :: SC_TIMESTAMP_HI [31:24] */
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_1_SC_TIMESTAMP_HI_MASK        0xff000000
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_1_SC_TIMESTAMP_HI_SHIFT       24

/* XPT_REC :: PTS_INDEX_ENTRY_1 :: reserved0 [23:13] */
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_1_reserved0_MASK              0x00ffe000
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_1_reserved0_SHIFT             13

/* XPT_REC :: PTS_INDEX_ENTRY_1 :: SC_PID [12:00] */
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_1_SC_PID_MASK                 0x00001fff
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_1_SC_PID_SHIFT                0

/***************************************************************************
 *PTS_INDEX_ENTRY_2 - Presentation Time Stamp Index Entry Word 2
 ***************************************************************************/
/* XPT_REC :: PTS_INDEX_ENTRY_2 :: SC_VALUE_FE [31:24] */
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_2_SC_VALUE_FE_MASK            0xff000000
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_2_SC_VALUE_FE_SHIFT           24

/* XPT_REC :: PTS_INDEX_ENTRY_2 :: reserved0 [23:01] */
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_2_reserved0_MASK              0x00fffffe
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_2_reserved0_SHIFT             1

/* XPT_REC :: PTS_INDEX_ENTRY_2 :: SC_PTS_MSBIT [00:00] */
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_2_SC_PTS_MSBIT_MASK           0x00000001
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_2_SC_PTS_MSBIT_SHIFT          0

/***************************************************************************
 *PTS_INDEX_ENTRY_3 - Presentation Time Stamp Index Entry Word 3
 ***************************************************************************/
/* XPT_REC :: PTS_INDEX_ENTRY_3 :: SC_PTS_LSBITS [31:00] */
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_3_SC_PTS_LSBITS_MASK          0xffffffff
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_3_SC_PTS_LSBITS_SHIFT         0

/***************************************************************************
 *PTS_INDEX_ENTRY_4 - Presentation Time Stamp Index Entry Word 4
 ***************************************************************************/
/* XPT_REC :: PTS_INDEX_ENTRY_4 :: reserved0 [31:00] */
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_4_reserved0_MASK              0xffffffff
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_4_reserved0_SHIFT             0

/***************************************************************************
 *PTS_INDEX_ENTRY_5 - Presentation Time Stamp Index Entry Word 5
 ***************************************************************************/
/* XPT_REC :: PTS_INDEX_ENTRY_5 :: reserved0 [31:00] */
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_5_reserved0_MASK              0xffffffff
#define BCHP_XPT_REC_PTS_INDEX_ENTRY_5_reserved0_SHIFT             0

/***************************************************************************
 *SC_INDEX_ENTRY_0 - Start Code Index Entry Word 0
 ***************************************************************************/
/* XPT_REC :: SC_INDEX_ENTRY_0 :: SC_ENTRY_TYPE [31:24] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_0_SC_ENTRY_TYPE_MASK           0xff000000
#define BCHP_XPT_REC_SC_INDEX_ENTRY_0_SC_ENTRY_TYPE_SHIFT          24

/* XPT_REC :: SC_INDEX_ENTRY_0 :: SC_TIMESTAMP_LO [23:00] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_0_SC_TIMESTAMP_LO_MASK         0x00ffffff
#define BCHP_XPT_REC_SC_INDEX_ENTRY_0_SC_TIMESTAMP_LO_SHIFT        0

/***************************************************************************
 *SC_INDEX_ENTRY_1 - Start Code Index Entry Word 1
 ***************************************************************************/
/* XPT_REC :: SC_INDEX_ENTRY_1 :: SC_TIMESTAMP_HI [31:24] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_1_SC_TIMESTAMP_HI_MASK         0xff000000
#define BCHP_XPT_REC_SC_INDEX_ENTRY_1_SC_TIMESTAMP_HI_SHIFT        24

/* XPT_REC :: SC_INDEX_ENTRY_1 :: reserved0 [23:13] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_1_reserved0_MASK               0x00ffe000
#define BCHP_XPT_REC_SC_INDEX_ENTRY_1_reserved0_SHIFT              13

/* XPT_REC :: SC_INDEX_ENTRY_1 :: SC_PID [12:00] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_1_SC_PID_MASK                  0x00001fff
#define BCHP_XPT_REC_SC_INDEX_ENTRY_1_SC_PID_SHIFT                 0

/***************************************************************************
 *SC_INDEX_ENTRY_2 - Start Code Index Entry Word 2
 ***************************************************************************/
/* XPT_REC :: SC_INDEX_ENTRY_2 :: SC_VALUE [31:24] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_2_SC_VALUE_MASK                0xff000000
#define BCHP_XPT_REC_SC_INDEX_ENTRY_2_SC_VALUE_SHIFT               24

/* XPT_REC :: SC_INDEX_ENTRY_2 :: SC_CONTENTS [23:08] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_2_SC_CONTENTS_MASK             0x00ffff00
#define BCHP_XPT_REC_SC_INDEX_ENTRY_2_SC_CONTENTS_SHIFT            8

/* XPT_REC :: SC_INDEX_ENTRY_2 :: SC_PACKET_OFFSET [07:00] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_2_SC_PACKET_OFFSET_MASK        0x000000ff
#define BCHP_XPT_REC_SC_INDEX_ENTRY_2_SC_PACKET_OFFSET_SHIFT       0

/***************************************************************************
 *SC_INDEX_ENTRY_3 - Start Code Index Entry Word 3
 ***************************************************************************/
/* XPT_REC :: SC_INDEX_ENTRY_3 :: SC_RECORD_COUNT_LSBITS [31:00] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_3_SC_RECORD_COUNT_LSBITS_MASK  0xffffffff
#define BCHP_XPT_REC_SC_INDEX_ENTRY_3_SC_RECORD_COUNT_LSBITS_SHIFT 0

/***************************************************************************
 *SC_INDEX_ENTRY_4 - Start Code Index Entry Word 4
 ***************************************************************************/
/* XPT_REC :: SC_INDEX_ENTRY_4 :: SC_RECORD_COUNT_MSBITS [31:24] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_4_SC_RECORD_COUNT_MSBITS_MASK  0xff000000
#define BCHP_XPT_REC_SC_INDEX_ENTRY_4_SC_RECORD_COUNT_MSBITS_SHIFT 24

/* XPT_REC :: SC_INDEX_ENTRY_4 :: SC_ES_BYTES_1 [23:00] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_4_SC_ES_BYTES_1_MASK           0x00ffffff
#define BCHP_XPT_REC_SC_INDEX_ENTRY_4_SC_ES_BYTES_1_SHIFT          0

/***************************************************************************
 *SC_INDEX_ENTRY_5 - Start Code Index Entry Word 5
 ***************************************************************************/
/* XPT_REC :: SC_INDEX_ENTRY_5 :: SC_PD_ERR [31:31] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_5_SC_PD_ERR_MASK               0x80000000
#define BCHP_XPT_REC_SC_INDEX_ENTRY_5_SC_PD_ERR_SHIFT              31

/* XPT_REC :: SC_INDEX_ENTRY_5 :: SC_CC_ERR [30:30] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_5_SC_CC_ERR_MASK               0x40000000
#define BCHP_XPT_REC_SC_INDEX_ENTRY_5_SC_CC_ERR_SHIFT              30

/* XPT_REC :: SC_INDEX_ENTRY_5 :: SC_TEI_ERR [29:29] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_5_SC_TEI_ERR_MASK              0x20000000
#define BCHP_XPT_REC_SC_INDEX_ENTRY_5_SC_TEI_ERR_SHIFT             29

/* XPT_REC :: SC_INDEX_ENTRY_5 :: SC_OVFL_ERR [28:28] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_5_SC_OVFL_ERR_MASK             0x10000000
#define BCHP_XPT_REC_SC_INDEX_ENTRY_5_SC_OVFL_ERR_SHIFT            28

/* XPT_REC :: SC_INDEX_ENTRY_5 :: SC_PES_LEN_ERR [27:27] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_5_SC_PES_LEN_ERR_MASK          0x08000000
#define BCHP_XPT_REC_SC_INDEX_ENTRY_5_SC_PES_LEN_ERR_SHIFT         27

/* XPT_REC :: SC_INDEX_ENTRY_5 :: reserved0 [26:24] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_5_reserved0_MASK               0x07000000
#define BCHP_XPT_REC_SC_INDEX_ENTRY_5_reserved0_SHIFT              24

/* XPT_REC :: SC_INDEX_ENTRY_5 :: SC_ES_BYTES_2 [23:00] */
#define BCHP_XPT_REC_SC_INDEX_ENTRY_5_SC_ES_BYTES_2_MASK           0x00ffffff
#define BCHP_XPT_REC_SC_INDEX_ENTRY_5_SC_ES_BYTES_2_SHIFT          0

/***************************************************************************
 *SP_INDEX_ENTRY_0 - Seamless Pause Index Entry Word 0
 ***************************************************************************/
/* XPT_REC :: SP_INDEX_ENTRY_0 :: SP_ENTRY_TYPE [31:24] */
#define BCHP_XPT_REC_SP_INDEX_ENTRY_0_SP_ENTRY_TYPE_MASK           0xff000000
#define BCHP_XPT_REC_SP_INDEX_ENTRY_0_SP_ENTRY_TYPE_SHIFT          24

/* XPT_REC :: SP_INDEX_ENTRY_0 :: reserved0 [23:00] */
#define BCHP_XPT_REC_SP_INDEX_ENTRY_0_reserved0_MASK               0x00ffffff
#define BCHP_XPT_REC_SP_INDEX_ENTRY_0_reserved0_SHIFT              0

/***************************************************************************
 *SP_INDEX_ENTRY_1 - Seamless Pause Index Entry Word 1
 ***************************************************************************/
/* XPT_REC :: SP_INDEX_ENTRY_1 :: reserved0 [31:00] */
#define BCHP_XPT_REC_SP_INDEX_ENTRY_1_reserved0_MASK               0xffffffff
#define BCHP_XPT_REC_SP_INDEX_ENTRY_1_reserved0_SHIFT              0

/***************************************************************************
 *SP_INDEX_ENTRY_2 - Seamless Pause Index Entry Word 2
 ***************************************************************************/
/* XPT_REC :: SP_INDEX_ENTRY_2 :: SP_IDENTIFIER [31:16] */
#define BCHP_XPT_REC_SP_INDEX_ENTRY_2_SP_IDENTIFIER_MASK           0xffff0000
#define BCHP_XPT_REC_SP_INDEX_ENTRY_2_SP_IDENTIFIER_SHIFT          16

/* XPT_REC :: SP_INDEX_ENTRY_2 :: reserved0 [15:00] */
#define BCHP_XPT_REC_SP_INDEX_ENTRY_2_reserved0_MASK               0x0000ffff
#define BCHP_XPT_REC_SP_INDEX_ENTRY_2_reserved0_SHIFT              0

/***************************************************************************
 *SP_INDEX_ENTRY_3 - Seamless Pause Index Entry Word 3
 ***************************************************************************/
/* XPT_REC :: SP_INDEX_ENTRY_3 :: SP_RECORD_COUNT_LSBITS [31:00] */
#define BCHP_XPT_REC_SP_INDEX_ENTRY_3_SP_RECORD_COUNT_LSBITS_MASK  0xffffffff
#define BCHP_XPT_REC_SP_INDEX_ENTRY_3_SP_RECORD_COUNT_LSBITS_SHIFT 0

/***************************************************************************
 *SP_INDEX_ENTRY_4 - Seamless Pause Index Entry Word 4
 ***************************************************************************/
/* XPT_REC :: SP_INDEX_ENTRY_4 :: SP_RECORD_COUNT_MSBITS [31:24] */
#define BCHP_XPT_REC_SP_INDEX_ENTRY_4_SP_RECORD_COUNT_MSBITS_MASK  0xff000000
#define BCHP_XPT_REC_SP_INDEX_ENTRY_4_SP_RECORD_COUNT_MSBITS_SHIFT 24

/* XPT_REC :: SP_INDEX_ENTRY_4 :: reserved0 [23:00] */
#define BCHP_XPT_REC_SP_INDEX_ENTRY_4_reserved0_MASK               0x00ffffff
#define BCHP_XPT_REC_SP_INDEX_ENTRY_4_reserved0_SHIFT              0

/***************************************************************************
 *SP_INDEX_ENTRY_5 - Seamless Pause Index Entry Word 5
 ***************************************************************************/
/* XPT_REC :: SP_INDEX_ENTRY_5 :: reserved0 [31:00] */
#define BCHP_XPT_REC_SP_INDEX_ENTRY_5_reserved0_MASK               0xffffffff
#define BCHP_XPT_REC_SP_INDEX_ENTRY_5_reserved0_SHIFT              0

/***************************************************************************
 *TF_INDEX_ENTRY_0 - Transport Field Index Entry Word 0
 ***************************************************************************/
/* XPT_REC :: TF_INDEX_ENTRY_0 :: TF_ENTRY_TYPE [31:24] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_0_TF_ENTRY_TYPE_MASK           0xff000000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_0_TF_ENTRY_TYPE_SHIFT          24

/* XPT_REC :: TF_INDEX_ENTRY_0 :: reserved0 [23:00] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_0_reserved0_MASK               0x00ffffff
#define BCHP_XPT_REC_TF_INDEX_ENTRY_0_reserved0_SHIFT              0

/***************************************************************************
 *TF_INDEX_ENTRY_1 - Transport Field Index Entry Word 1
 ***************************************************************************/
/* union - case MPEG [31:00] */
/* XPT_REC :: TF_INDEX_ENTRY_1 :: MPEG :: reserved0 [31:24] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_MPEG_reserved0_MASK          0xff000000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_MPEG_reserved0_SHIFT         24

/* XPT_REC :: TF_INDEX_ENTRY_1 :: MPEG :: TF_TEI [23:23] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_MPEG_TF_TEI_MASK             0x00800000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_MPEG_TF_TEI_SHIFT            23

/* XPT_REC :: TF_INDEX_ENTRY_1 :: MPEG :: TF_PUSI [22:22] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_MPEG_TF_PUSI_MASK            0x00400000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_MPEG_TF_PUSI_SHIFT           22

/* XPT_REC :: TF_INDEX_ENTRY_1 :: MPEG :: TF_TPRI [21:21] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_MPEG_TF_TPRI_MASK            0x00200000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_MPEG_TF_TPRI_SHIFT           21

/* XPT_REC :: TF_INDEX_ENTRY_1 :: MPEG :: TF_PID [20:08] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_MPEG_TF_PID_MASK             0x001fff00
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_MPEG_TF_PID_SHIFT            8

/* XPT_REC :: TF_INDEX_ENTRY_1 :: MPEG :: TF_SCRAM_CTRL [07:06] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_MPEG_TF_SCRAM_CTRL_MASK      0x000000c0
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_MPEG_TF_SCRAM_CTRL_SHIFT     6

/* XPT_REC :: TF_INDEX_ENTRY_1 :: MPEG :: TF_ADAPT_CTRL [05:04] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_MPEG_TF_ADAPT_CTRL_MASK      0x00000030
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_MPEG_TF_ADAPT_CTRL_SHIFT     4

/* XPT_REC :: TF_INDEX_ENTRY_1 :: MPEG :: TF_CONT_COUNT [03:00] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_MPEG_TF_CONT_COUNT_MASK      0x0000000f
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_MPEG_TF_CONT_COUNT_SHIFT     0

/* union - case DIRECTV [31:00] */
/* XPT_REC :: TF_INDEX_ENTRY_1 :: DIRECTV :: reserved0 [31:24] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_DIRECTV_reserved0_MASK       0xff000000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_DIRECTV_reserved0_SHIFT      24

/* XPT_REC :: TF_INDEX_ENTRY_1 :: DIRECTV :: TF_PF [23:23] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_DIRECTV_TF_PF_MASK           0x00800000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_DIRECTV_TF_PF_SHIFT          23

/* XPT_REC :: TF_INDEX_ENTRY_1 :: DIRECTV :: TF_BB [22:22] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_DIRECTV_TF_BB_MASK           0x00400000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_DIRECTV_TF_BB_SHIFT          22

/* XPT_REC :: TF_INDEX_ENTRY_1 :: DIRECTV :: TF_CF [21:21] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_DIRECTV_TF_CF_MASK           0x00200000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_DIRECTV_TF_CF_SHIFT          21

/* XPT_REC :: TF_INDEX_ENTRY_1 :: DIRECTV :: TF_CS [20:20] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_DIRECTV_TF_CS_MASK           0x00100000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_DIRECTV_TF_CS_SHIFT          20

/* XPT_REC :: TF_INDEX_ENTRY_1 :: DIRECTV :: TF_SCID [19:08] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_DIRECTV_TF_SCID_MASK         0x000fff00
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_DIRECTV_TF_SCID_SHIFT        8

/* XPT_REC :: TF_INDEX_ENTRY_1 :: DIRECTV :: TF_CC [07:04] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_DIRECTV_TF_CC_MASK           0x000000f0
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_DIRECTV_TF_CC_SHIFT          4

/* XPT_REC :: TF_INDEX_ENTRY_1 :: DIRECTV :: TF_HD [03:00] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_DIRECTV_TF_HD_MASK           0x0000000f
#define BCHP_XPT_REC_TF_INDEX_ENTRY_1_DIRECTV_TF_HD_SHIFT          0

/***************************************************************************
 *TF_INDEX_ENTRY_2 - Transport Field Index Entry Word 2
 ***************************************************************************/
/* union - case MPEG [31:00] */
/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_RECORD_COUNT_MSBITS [31:24] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_RECORD_COUNT_MSBITS_MASK 0xff000000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_RECORD_COUNT_MSBITS_SHIFT 24

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: reserved0 [23:18] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_reserved0_MASK          0x00fc0000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_reserved0_SHIFT         18

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_RECORD_IDLE [17:17] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_RECORD_IDLE_MASK     0x00020000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_RECORD_IDLE_SHIFT    17

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_FIRST_PACKET [16:16] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_FIRST_PACKET_MASK    0x00010000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_FIRST_PACKET_SHIFT   16

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_SUBSTITUTE_PACKET [15:15] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_SUBSTITUTE_PACKET_MASK 0x00008000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_SUBSTITUTE_PACKET_SHIFT 15

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_ECM_POLARITY_1 [14:14] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_ECM_POLARITY_1_MASK  0x00004000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_ECM_POLARITY_1_SHIFT 14

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_ECM_POLARITY_0 [13:13] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_ECM_POLARITY_0_MASK  0x00002000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_ECM_POLARITY_0_SHIFT 13

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_SECTION_FILT_MATCH [12:12] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_SECTION_FILT_MATCH_MASK 0x00001000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_SECTION_FILT_MATCH_SHIFT 12

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_ADAPT_FIELD_EXT_FLAG [11:11] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_ADAPT_FIELD_EXT_FLAG_MASK 0x00000800
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_ADAPT_FIELD_EXT_FLAG_SHIFT 11

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_PRIVATE_DATA_FLAG [10:10] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_PRIVATE_DATA_FLAG_MASK 0x00000400
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_PRIVATE_DATA_FLAG_SHIFT 10

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_SPLICING_POINT_FLAG [09:09] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_SPLICING_POINT_FLAG_MASK 0x00000200
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_SPLICING_POINT_FLAG_SHIFT 9

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_OPCR_FLAG [08:08] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_OPCR_FLAG_MASK       0x00000100
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_OPCR_FLAG_SHIFT      8

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_PCR_FLAG [07:07] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_PCR_FLAG_MASK        0x00000080
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_PCR_FLAG_SHIFT       7

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_ES_PRIORITY_INDICATOR [06:06] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_ES_PRIORITY_INDICATOR_MASK 0x00000040
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_ES_PRIORITY_INDICATOR_SHIFT 6

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_RANDOM_ACCESS_IND [05:05] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_RANDOM_ACCESS_IND_MASK 0x00000020
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_RANDOM_ACCESS_IND_SHIFT 5

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_DISCONTINUITY_IND [04:04] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_DISCONTINUITY_IND_MASK 0x00000010
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_DISCONTINUITY_IND_SHIFT 4

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_AFC_CHANGE [03:03] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_AFC_CHANGE_MASK      0x00000008
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_AFC_CHANGE_SHIFT     3

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_TSC_CHANGE [02:02] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_TSC_CHANGE_MASK      0x00000004
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_TSC_CHANGE_SHIFT     2

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_TRANSPORT_PRIORITY [01:01] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_TRANSPORT_PRIORITY_MASK 0x00000002
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_TRANSPORT_PRIORITY_SHIFT 1

/* XPT_REC :: TF_INDEX_ENTRY_2 :: MPEG :: TF_PUSI_MATCH [00:00] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_PUSI_MATCH_MASK      0x00000001
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_MPEG_TF_PUSI_MATCH_SHIFT     0

/* union - case DIRECTV [31:00] */
/* XPT_REC :: TF_INDEX_ENTRY_2 :: DIRECTV :: TF_RECORD_COUNT_MSBITS [31:24] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_RECORD_COUNT_MSBITS_MASK 0xff000000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_RECORD_COUNT_MSBITS_SHIFT 24

/* XPT_REC :: TF_INDEX_ENTRY_2 :: DIRECTV :: reserved0 [23:18] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_reserved0_MASK       0x00fc0000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_reserved0_SHIFT      18

/* XPT_REC :: TF_INDEX_ENTRY_2 :: DIRECTV :: TF_RECORD_IDLE [17:17] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_RECORD_IDLE_MASK  0x00020000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_RECORD_IDLE_SHIFT 17

/* XPT_REC :: TF_INDEX_ENTRY_2 :: DIRECTV :: TF_FIRST_PACKET [16:16] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_FIRST_PACKET_MASK 0x00010000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_FIRST_PACKET_SHIFT 16

/* XPT_REC :: TF_INDEX_ENTRY_2 :: DIRECTV :: TF_SUBSTITUTE_PACKET [15:15] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_SUBSTITUTE_PACKET_MASK 0x00008000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_SUBSTITUTE_PACKET_SHIFT 15

/* XPT_REC :: TF_INDEX_ENTRY_2 :: DIRECTV :: reserved1 [14:12] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_reserved1_MASK       0x00007000
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_reserved1_SHIFT      12

/* XPT_REC :: TF_INDEX_ENTRY_2 :: DIRECTV :: TF_CWP_DET [11:11] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_CWP_DET_MASK      0x00000800
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_CWP_DET_SHIFT     11

/* XPT_REC :: TF_INDEX_ENTRY_2 :: DIRECTV :: TF_RTS_DET [10:10] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_RTS_DET_MASK      0x00000400
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_RTS_DET_SHIFT     10

/* XPT_REC :: TF_INDEX_ENTRY_2 :: DIRECTV :: TF_CFF_MATCH [09:09] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_CFF_MATCH_MASK    0x00000200
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_CFF_MATCH_SHIFT   9

/* XPT_REC :: TF_INDEX_ENTRY_2 :: DIRECTV :: TF_MF_MATCH [08:08] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_MF_MATCH_MASK     0x00000100
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_MF_MATCH_SHIFT    8

/* XPT_REC :: TF_INDEX_ENTRY_2 :: DIRECTV :: TF_HD_MATCH [07:04] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_HD_MATCH_MASK     0x000000f0
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_HD_MATCH_SHIFT    4

/* XPT_REC :: TF_INDEX_ENTRY_2 :: DIRECTV :: TF_CSAUX_CHANGE [03:03] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_CSAUX_CHANGE_MASK 0x00000008
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_CSAUX_CHANGE_SHIFT 3

/* XPT_REC :: TF_INDEX_ENTRY_2 :: DIRECTV :: TF_CS_CHANGE [02:02] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_CS_CHANGE_MASK    0x00000004
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_CS_CHANGE_SHIFT   2

/* XPT_REC :: TF_INDEX_ENTRY_2 :: DIRECTV :: TF_CF_CHANGE [01:01] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_CF_CHANGE_MASK    0x00000002
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_CF_CHANGE_SHIFT   1

/* XPT_REC :: TF_INDEX_ENTRY_2 :: DIRECTV :: TF_BB_MATCH [00:00] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_BB_MATCH_MASK     0x00000001
#define BCHP_XPT_REC_TF_INDEX_ENTRY_2_DIRECTV_TF_BB_MATCH_SHIFT    0

/***************************************************************************
 *TF_INDEX_ENTRY_3 - Transport Field Index Entry Word 3
 ***************************************************************************/
/* XPT_REC :: TF_INDEX_ENTRY_3 :: TF_RECORD_COUNT_LSBITS [31:00] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_3_TF_RECORD_COUNT_LSBITS_MASK  0xffffffff
#define BCHP_XPT_REC_TF_INDEX_ENTRY_3_TF_RECORD_COUNT_LSBITS_SHIFT 0

/***************************************************************************
 *TF_INDEX_ENTRY_4 - Transport Field Index Entry Word 4
 ***************************************************************************/
/* XPT_REC :: TF_INDEX_ENTRY_4 :: TF_TIMER [31:00] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_4_TF_TIMER_MASK                0xffffffff
#define BCHP_XPT_REC_TF_INDEX_ENTRY_4_TF_TIMER_SHIFT               0

/***************************************************************************
 *TF_INDEX_ENTRY_5 - Transport Field Index Entry Word 5
 ***************************************************************************/
/* union - case MPEG [31:00] */
/* XPT_REC :: TF_INDEX_ENTRY_5 :: MPEG :: TF_PCR [31:00] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_5_MPEG_TF_PCR_MASK             0xffffffff
#define BCHP_XPT_REC_TF_INDEX_ENTRY_5_MPEG_TF_PCR_SHIFT            0

/* union - case DIRECTV [31:00] */
/* XPT_REC :: TF_INDEX_ENTRY_5 :: DIRECTV :: TF_RTS [31:00] */
#define BCHP_XPT_REC_TF_INDEX_ENTRY_5_DIRECTV_TF_RTS_MASK          0xffffffff
#define BCHP_XPT_REC_TF_INDEX_ENTRY_5_DIRECTV_TF_RTS_SHIFT         0

/***************************************************************************
 *XPT_REGS
 ***************************************************************************/
/***************************************************************************
 *ABSTRACT_00_SPECVERSION - Data Transport Specification Version
 ***************************************************************************/
/* XPT_REGS :: ABSTRACT_00_SPECVERSION :: reserved0 [31:00] */
#define BCHP_XPT_REGS_ABSTRACT_00_SPECVERSION_reserved0_MASK       0xffffffff
#define BCHP_XPT_REGS_ABSTRACT_00_SPECVERSION_reserved0_SHIFT      0

/***************************************************************************
 *ABSTRACT_01_DEFINITION_OF_TERMS - Data Transport Definition of Terms
 ***************************************************************************/
/* XPT_REGS :: ABSTRACT_01_DEFINITION_OF_TERMS :: reserved0 [31:00] */
#define BCHP_XPT_REGS_ABSTRACT_01_DEFINITION_OF_TERMS_reserved0_MASK 0xffffffff
#define BCHP_XPT_REGS_ABSTRACT_01_DEFINITION_OF_TERMS_reserved0_SHIFT 0

/***************************************************************************
 *USER_GUIDE_01_PID_TABLE - Data Transport PID Table Programming
 ***************************************************************************/
/* XPT_REGS :: USER_GUIDE_01_PID_TABLE :: MORE_INFORMATION [31:00] */
#define BCHP_XPT_REGS_USER_GUIDE_01_PID_TABLE_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_XPT_REGS_USER_GUIDE_01_PID_TABLE_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *USER_GUIDE_02_DMA_MESSAGE_BUFFER - Data Transport DMA Message Buffer Programming
 ***************************************************************************/
/* XPT_REGS :: USER_GUIDE_02_DMA_MESSAGE_BUFFER :: MORE_INFORMATION [31:00] */
#define BCHP_XPT_REGS_USER_GUIDE_02_DMA_MESSAGE_BUFFER_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_XPT_REGS_USER_GUIDE_02_DMA_MESSAGE_BUFFER_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *USER_GUIDE_03_PSI_SECTION_FILTER - Data Transport PSI Section Filter Programming
 ***************************************************************************/
/* XPT_REGS :: USER_GUIDE_03_PSI_SECTION_FILTER :: MORE_INFORMATION [31:00] */
#define BCHP_XPT_REGS_USER_GUIDE_03_PSI_SECTION_FILTER_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_XPT_REGS_USER_GUIDE_03_PSI_SECTION_FILTER_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *USER_GUIDE_04_PES_PARSER - Data Transport PES Parser
 ***************************************************************************/
/* XPT_REGS :: USER_GUIDE_04_PES_PARSER :: reserved0 [31:00] */
#define BCHP_XPT_REGS_USER_GUIDE_04_PES_PARSER_reserved0_MASK      0xffffffff
#define BCHP_XPT_REGS_USER_GUIDE_04_PES_PARSER_reserved0_SHIFT     0

/***************************************************************************
 *USER_GUIDE_05_CONDITIONAL_ACCESS - Data Transport Conditional Access Programming
 ***************************************************************************/
/* XPT_REGS :: USER_GUIDE_05_CONDITIONAL_ACCESS :: MORE_INFORMATION [31:00] */
#define BCHP_XPT_REGS_USER_GUIDE_05_CONDITIONAL_ACCESS_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_XPT_REGS_USER_GUIDE_05_CONDITIONAL_ACCESS_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *USER_GUIDE_07_INPUT_AND_PARSER_BAND - Data Transport Input and Parser Band Programming
 ***************************************************************************/
/* XPT_REGS :: USER_GUIDE_07_INPUT_AND_PARSER_BAND :: MORE_INFORMATION [31:00] */
#define BCHP_XPT_REGS_USER_GUIDE_07_INPUT_AND_PARSER_BAND_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_XPT_REGS_USER_GUIDE_07_INPUT_AND_PARSER_BAND_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *USER_GUIDE_08_AUDIO_VIDEO_INTERFACE - Data Transport Audio/Video Interface Programming
 ***************************************************************************/
/* XPT_REGS :: USER_GUIDE_08_AUDIO_VIDEO_INTERFACE :: MORE_INFORMATION [31:00] */
#define BCHP_XPT_REGS_USER_GUIDE_08_AUDIO_VIDEO_INTERFACE_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_XPT_REGS_USER_GUIDE_08_AUDIO_VIDEO_INTERFACE_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *USER_GUIDE_10_PVR_LINKED_LISTS - Data Transport PVR (Playback/Record/SCD) Linked-List Descriptor Programming
 ***************************************************************************/
/* XPT_REGS :: USER_GUIDE_10_PVR_LINKED_LISTS :: MORE_INFORMATION [31:00] */
#define BCHP_XPT_REGS_USER_GUIDE_10_PVR_LINKED_LISTS_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_XPT_REGS_USER_GUIDE_10_PVR_LINKED_LISTS_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *USER_GUIDE_11_PVR_PLAYBACK - Data Transport PVR Playback Programming
 ***************************************************************************/
/* XPT_REGS :: USER_GUIDE_11_PVR_PLAYBACK :: MORE_INFORMATION [31:00] */
#define BCHP_XPT_REGS_USER_GUIDE_11_PVR_PLAYBACK_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_XPT_REGS_USER_GUIDE_11_PVR_PLAYBACK_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *USER_GUIDE_12_PVR_RECORD - Data Transport PVR Record Programming
 ***************************************************************************/
/* XPT_REGS :: USER_GUIDE_12_PVR_RECORD :: MORE_INFORMATION [31:00] */
#define BCHP_XPT_REGS_USER_GUIDE_12_PVR_RECORD_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_XPT_REGS_USER_GUIDE_12_PVR_RECORD_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *USER_GUIDE_13_PVR_SCD_TPIT - Data Transport PVR SCD And TPIT Programming
 ***************************************************************************/
/* XPT_REGS :: USER_GUIDE_13_PVR_SCD_TPIT :: MORE_INFORMATION [31:00] */
#define BCHP_XPT_REGS_USER_GUIDE_13_PVR_SCD_TPIT_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_XPT_REGS_USER_GUIDE_13_PVR_SCD_TPIT_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *USER_GUIDE_20_HS_PORT_HSX - Data Transport HSX Programming
 ***************************************************************************/
/* XPT_REGS :: USER_GUIDE_20_HS_PORT_HSX :: MORE_INFORMATION [31:00] */
#define BCHP_XPT_REGS_USER_GUIDE_20_HS_PORT_HSX_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_XPT_REGS_USER_GUIDE_20_HS_PORT_HSX_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *USER_GUIDE_21_HS_PORT_RMX - Data Transport RMX Programming
 ***************************************************************************/
/* XPT_REGS :: USER_GUIDE_21_HS_PORT_RMX :: MORE_INFORMATION [31:00] */
#define BCHP_XPT_REGS_USER_GUIDE_21_HS_PORT_RMX_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_XPT_REGS_USER_GUIDE_21_HS_PORT_RMX_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *USER_GUIDE_23_DPCR_MODULE - Data Transport DPCR Module
 ***************************************************************************/
/* XPT_REGS :: USER_GUIDE_23_DPCR_MODULE :: MORE_INFORMATION [31:00] */
#define BCHP_XPT_REGS_USER_GUIDE_23_DPCR_MODULE_MORE_INFORMATION_MASK 0xffffffff
#define BCHP_XPT_REGS_USER_GUIDE_23_DPCR_MODULE_MORE_INFORMATION_SHIFT 0

/***************************************************************************
 *XPT_SCD
 ***************************************************************************/
/***************************************************************************
 *DESCRIPTOR_ABSTRACT - SCD Linked-List Descriptor Abstract
 ***************************************************************************/
/* XPT_SCD :: DESCRIPTOR_ABSTRACT :: DESCRIPTOR_FORMAT [31:00] */
#define BCHP_XPT_SCD_DESCRIPTOR_ABSTRACT_DESCRIPTOR_FORMAT_MASK    0xffffffff
#define BCHP_XPT_SCD_DESCRIPTOR_ABSTRACT_DESCRIPTOR_FORMAT_SHIFT   0

/***************************************************************************
 *DESC_0 - SCD Linked-List Descriptor Word 0
 ***************************************************************************/
/* XPT_SCD :: DESC_0 :: reserved0 [31:27] */
#define BCHP_XPT_SCD_DESC_0_reserved0_MASK                         0xf8000000
#define BCHP_XPT_SCD_DESC_0_reserved0_SHIFT                        27

/* XPT_SCD :: DESC_0 :: SCD_BUFFER_START_ADDR [26:02] */
#define BCHP_XPT_SCD_DESC_0_SCD_BUFFER_START_ADDR_MASK             0x07fffffc
#define BCHP_XPT_SCD_DESC_0_SCD_BUFFER_START_ADDR_SHIFT            2

/* XPT_SCD :: DESC_0 :: reserved1 [01:00] */
#define BCHP_XPT_SCD_DESC_0_reserved1_MASK                         0x00000003
#define BCHP_XPT_SCD_DESC_0_reserved1_SHIFT                        0

/***************************************************************************
 *DESC_1 - SCD Linked-List Descriptor Word 1
 ***************************************************************************/
/* XPT_SCD :: DESC_1 :: reserved0 [31:27] */
#define BCHP_XPT_SCD_DESC_1_reserved0_MASK                         0xf8000000
#define BCHP_XPT_SCD_DESC_1_reserved0_SHIFT                        27

/* XPT_SCD :: DESC_1 :: SCD_BUFFER_LENGTH [26:04] */
#define BCHP_XPT_SCD_DESC_1_SCD_BUFFER_LENGTH_MASK                 0x07fffff0
#define BCHP_XPT_SCD_DESC_1_SCD_BUFFER_LENGTH_SHIFT                4

/* XPT_SCD :: DESC_1 :: reserved1 [03:00] */
#define BCHP_XPT_SCD_DESC_1_reserved1_MASK                         0x0000000f
#define BCHP_XPT_SCD_DESC_1_reserved1_SHIFT                        0

/***************************************************************************
 *DESC_2 - SCD Linked-List Descriptor Word 2
 ***************************************************************************/
/* XPT_SCD :: DESC_2 :: SCD_INTERRUPT_ENABLE [31:31] */
#define BCHP_XPT_SCD_DESC_2_SCD_INTERRUPT_ENABLE_MASK              0x80000000
#define BCHP_XPT_SCD_DESC_2_SCD_INTERRUPT_ENABLE_SHIFT             31

/* XPT_SCD :: DESC_2 :: reserved0 [30:00] */
#define BCHP_XPT_SCD_DESC_2_reserved0_MASK                         0x7fffffff
#define BCHP_XPT_SCD_DESC_2_reserved0_SHIFT                        0

/***************************************************************************
 *DESC_3 - SCD Linked-List Descriptor Word 3
 ***************************************************************************/
/* XPT_SCD :: DESC_3 :: reserved0 [31:27] */
#define BCHP_XPT_SCD_DESC_3_reserved0_MASK                         0xf8000000
#define BCHP_XPT_SCD_DESC_3_reserved0_SHIFT                        27

/* XPT_SCD :: DESC_3 :: SCD_NEXT_DESC_ADDR [26:04] */
#define BCHP_XPT_SCD_DESC_3_SCD_NEXT_DESC_ADDR_MASK                0x07fffff0
#define BCHP_XPT_SCD_DESC_3_SCD_NEXT_DESC_ADDR_SHIFT               4

/* XPT_SCD :: DESC_3 :: reserved1 [03:01] */
#define BCHP_XPT_SCD_DESC_3_reserved1_MASK                         0x0000000e
#define BCHP_XPT_SCD_DESC_3_reserved1_SHIFT                        1

/* XPT_SCD :: DESC_3 :: SCD_LAST_DESC_IND [00:00] */
#define BCHP_XPT_SCD_DESC_3_SCD_LAST_DESC_IND_MASK                 0x00000001
#define BCHP_XPT_SCD_DESC_3_SCD_LAST_DESC_IND_SHIFT                0

#endif /* #ifndef BCHP_COMMON_H__ */

/* End of File */
