/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Mar 20 13:02:35 2009
 *                 MD5 Checksum         4f0509cfa0b8fc4589050694b4a3e234
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7340/rdb/a0/bchp_avd_rgr_0.h $
 * 
 * Hydra_Software_Devel/1   3/22/09 7:49p yuxiaz
 * PR53430: Initial version of header files.
 *
 ***************************************************************************/

#ifndef BCHP_AVD_RGR_0_H__
#define BCHP_AVD_RGR_0_H__

/***************************************************************************
 *AVD_RGR_0
 ***************************************************************************/
#define BCHP_AVD_RGR_0_REVISION                  0x00900400 /* RGR Bridge Revision */
#define BCHP_AVD_RGR_0_CTRL                      0x00900404 /* RGR Bridge Control Register */
#define BCHP_AVD_RGR_0_RBUS_TIMER                0x00900408 /* RGR Bridge RBUS Timer Register */
#define BCHP_AVD_RGR_0_SW_RESET_0                0x0090040c /* RGR Bridge Software Reset 0 Register */
#define BCHP_AVD_RGR_0_SW_RESET_1                0x00900410 /* RGR Bridge Software Reset 1 Register */

/***************************************************************************
 *REVISION - RGR Bridge Revision
 ***************************************************************************/
/* AVD_RGR_0 :: REVISION :: reserved0 [31:16] */
#define BCHP_AVD_RGR_0_REVISION_reserved0_MASK                     0xffff0000
#define BCHP_AVD_RGR_0_REVISION_reserved0_SHIFT                    16

/* AVD_RGR_0 :: REVISION :: MAJOR [15:08] */
#define BCHP_AVD_RGR_0_REVISION_MAJOR_MASK                         0x0000ff00
#define BCHP_AVD_RGR_0_REVISION_MAJOR_SHIFT                        8

/* AVD_RGR_0 :: REVISION :: MINOR [07:00] */
#define BCHP_AVD_RGR_0_REVISION_MINOR_MASK                         0x000000ff
#define BCHP_AVD_RGR_0_REVISION_MINOR_SHIFT                        0

/***************************************************************************
 *CTRL - RGR Bridge Control Register
 ***************************************************************************/
/* AVD_RGR_0 :: CTRL :: reserved0 [31:02] */
#define BCHP_AVD_RGR_0_CTRL_reserved0_MASK                         0xfffffffc
#define BCHP_AVD_RGR_0_CTRL_reserved0_SHIFT                        2

/* AVD_RGR_0 :: CTRL :: rbus_error_intr [01:01] */
#define BCHP_AVD_RGR_0_CTRL_rbus_error_intr_MASK                   0x00000002
#define BCHP_AVD_RGR_0_CTRL_rbus_error_intr_SHIFT                  1
#define BCHP_AVD_RGR_0_CTRL_rbus_error_intr_INTR_DISABLE           0
#define BCHP_AVD_RGR_0_CTRL_rbus_error_intr_INTR_ENABLE            1

/* AVD_RGR_0 :: CTRL :: gisb_error_intr [00:00] */
#define BCHP_AVD_RGR_0_CTRL_gisb_error_intr_MASK                   0x00000001
#define BCHP_AVD_RGR_0_CTRL_gisb_error_intr_SHIFT                  0
#define BCHP_AVD_RGR_0_CTRL_gisb_error_intr_INTR_DISABLE           0
#define BCHP_AVD_RGR_0_CTRL_gisb_error_intr_INTR_ENABLE            1

/***************************************************************************
 *RBUS_TIMER - RGR Bridge RBUS Timer Register
 ***************************************************************************/
/* AVD_RGR_0 :: RBUS_TIMER :: reserved0 [31:16] */
#define BCHP_AVD_RGR_0_RBUS_TIMER_reserved0_MASK                   0xffff0000
#define BCHP_AVD_RGR_0_RBUS_TIMER_reserved0_SHIFT                  16

/* AVD_RGR_0 :: RBUS_TIMER :: timer_value [15:00] */
#define BCHP_AVD_RGR_0_RBUS_TIMER_timer_value_MASK                 0x0000ffff
#define BCHP_AVD_RGR_0_RBUS_TIMER_timer_value_SHIFT                0

/***************************************************************************
 *SW_RESET_0 - RGR Bridge Software Reset 0 Register
 ***************************************************************************/
/* AVD_RGR_0 :: SW_RESET_0 :: reserved0 [31:00] */
#define BCHP_AVD_RGR_0_SW_RESET_0_reserved0_MASK                   0xffffffff
#define BCHP_AVD_RGR_0_SW_RESET_0_reserved0_SHIFT                  0

/***************************************************************************
 *SW_RESET_1 - RGR Bridge Software Reset 1 Register
 ***************************************************************************/
/* AVD_RGR_0 :: SW_RESET_1 :: reserved0 [31:00] */
#define BCHP_AVD_RGR_0_SW_RESET_1_reserved0_MASK                   0xffffffff
#define BCHP_AVD_RGR_0_SW_RESET_1_reserved0_SHIFT                  0

#endif /* #ifndef BCHP_AVD_RGR_0_H__ */

/* End of File */
