/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Mar 20 12:59:51 2009
 *                 MD5 Checksum         4f0509cfa0b8fc4589050694b4a3e234
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7340/rdb/a0/bchp_mmisc.h $
 * 
 * Hydra_Software_Devel/1   3/22/09 8:42p yuxiaz
 * PR53430: Initial version of header files.
 *
 ***************************************************************************/

#ifndef BCHP_MMISC_H__
#define BCHP_MMISC_H__

/***************************************************************************
 *MMISC - BVN Middle Control Registers
 ***************************************************************************/
#define BCHP_MMISC_SOFT_RESET                    0x00122800 /* BVN Middle Soft Reset */
#define BCHP_MMISC_TEST_PORT_SEL                 0x00122804 /* BVN Middle Test Port Select */
#define BCHP_MMISC_TEST_PORT_DATA                0x00122808 /* BVN Middle Test Port Status */
#define BCHP_MMISC_BVNM_SCL_0_MBIST_TM_CTRL      0x00122810 /* BVN Middle SCL_0 MBIST TM Control */
#define BCHP_MMISC_BVNM_SCL_1_MBIST_TM_CTRL      0x00122814 /* BVN Middle SCL_1 MBIST TM Control */
#define BCHP_MMISC_BVNM_DNR_MBIST_TM_CTRL        0x00122818 /* BVN Middle DNR_0 MBIST TM Control */
#define BCHP_MMISC_BVNM_CLOCK_CTRL               0x00122820 /* BVN Middle clock control register */
#define BCHP_MMISC_SCRATCH_0                     0x0012282c /* Scratch Register */

/***************************************************************************
 *SOFT_RESET - BVN Middle Soft Reset
 ***************************************************************************/
/* MMISC :: SOFT_RESET :: reserved0 [31:30] */
#define BCHP_MMISC_SOFT_RESET_reserved0_MASK                       0xc0000000
#define BCHP_MMISC_SOFT_RESET_reserved0_SHIFT                      30

/* MMISC :: SOFT_RESET :: DNR_0 [29:29] */
#define BCHP_MMISC_SOFT_RESET_DNR_0_MASK                           0x20000000
#define BCHP_MMISC_SOFT_RESET_DNR_0_SHIFT                          29

/* MMISC :: SOFT_RESET :: TAB_0 [28:28] */
#define BCHP_MMISC_SOFT_RESET_TAB_0_MASK                           0x10000000
#define BCHP_MMISC_SOFT_RESET_TAB_0_SHIFT                          28

/* MMISC :: SOFT_RESET :: reserved1 [27:25] */
#define BCHP_MMISC_SOFT_RESET_reserved1_MASK                       0x0e000000
#define BCHP_MMISC_SOFT_RESET_reserved1_SHIFT                      25

/* MMISC :: SOFT_RESET :: LBOX_0 [24:24] */
#define BCHP_MMISC_SOFT_RESET_LBOX_0_MASK                          0x01000000
#define BCHP_MMISC_SOFT_RESET_LBOX_0_SHIFT                         24

/* MMISC :: SOFT_RESET :: reserved2 [23:10] */
#define BCHP_MMISC_SOFT_RESET_reserved2_MASK                       0x00fffc00
#define BCHP_MMISC_SOFT_RESET_reserved2_SHIFT                      10

/* MMISC :: SOFT_RESET :: VNET_B [09:09] */
#define BCHP_MMISC_SOFT_RESET_VNET_B_MASK                          0x00000200
#define BCHP_MMISC_SOFT_RESET_VNET_B_SHIFT                         9

/* MMISC :: SOFT_RESET :: VNET_F [08:08] */
#define BCHP_MMISC_SOFT_RESET_VNET_F_MASK                          0x00000100
#define BCHP_MMISC_SOFT_RESET_VNET_F_SHIFT                         8

/* MMISC :: SOFT_RESET :: reserved3 [07:02] */
#define BCHP_MMISC_SOFT_RESET_reserved3_MASK                       0x000000fc
#define BCHP_MMISC_SOFT_RESET_reserved3_SHIFT                      2

/* MMISC :: SOFT_RESET :: SCL_1 [01:01] */
#define BCHP_MMISC_SOFT_RESET_SCL_1_MASK                           0x00000002
#define BCHP_MMISC_SOFT_RESET_SCL_1_SHIFT                          1

/* MMISC :: SOFT_RESET :: SCL_0 [00:00] */
#define BCHP_MMISC_SOFT_RESET_SCL_0_MASK                           0x00000001
#define BCHP_MMISC_SOFT_RESET_SCL_0_SHIFT                          0

/***************************************************************************
 *TEST_PORT_SEL - BVN Middle Test Port Select
 ***************************************************************************/
/* MMISC :: TEST_PORT_SEL :: reserved0 [31:01] */
#define BCHP_MMISC_TEST_PORT_SEL_reserved0_MASK                    0xfffffffe
#define BCHP_MMISC_TEST_PORT_SEL_reserved0_SHIFT                   1

/* MMISC :: TEST_PORT_SEL :: TEST_PORT_SEL [00:00] */
#define BCHP_MMISC_TEST_PORT_SEL_TEST_PORT_SEL_MASK                0x00000001
#define BCHP_MMISC_TEST_PORT_SEL_TEST_PORT_SEL_SHIFT               0
#define BCHP_MMISC_TEST_PORT_SEL_TEST_PORT_SEL_TP_OUT_1            1
#define BCHP_MMISC_TEST_PORT_SEL_TEST_PORT_SEL_TP_OUT_0            0

/***************************************************************************
 *TEST_PORT_DATA - BVN Middle Test Port Status
 ***************************************************************************/
/* MMISC :: TEST_PORT_DATA :: TEST_PORT_DATA [31:00] */
#define BCHP_MMISC_TEST_PORT_DATA_TEST_PORT_DATA_MASK              0xffffffff
#define BCHP_MMISC_TEST_PORT_DATA_TEST_PORT_DATA_SHIFT             0

/***************************************************************************
 *BVNM_SCL_0_MBIST_TM_CTRL - BVN Middle SCL_0 MBIST TM Control
 ***************************************************************************/
/* MMISC :: BVNM_SCL_0_MBIST_TM_CTRL :: reserved0 [31:16] */
#define BCHP_MMISC_BVNM_SCL_0_MBIST_TM_CTRL_reserved0_MASK         0xffff0000
#define BCHP_MMISC_BVNM_SCL_0_MBIST_TM_CTRL_reserved0_SHIFT        16

/* MMISC :: BVNM_SCL_0_MBIST_TM_CTRL :: HD_SCL_TM1 [15:08] */
#define BCHP_MMISC_BVNM_SCL_0_MBIST_TM_CTRL_HD_SCL_TM1_MASK        0x0000ff00
#define BCHP_MMISC_BVNM_SCL_0_MBIST_TM_CTRL_HD_SCL_TM1_SHIFT       8

/* MMISC :: BVNM_SCL_0_MBIST_TM_CTRL :: HD_SCL_TM0 [07:00] */
#define BCHP_MMISC_BVNM_SCL_0_MBIST_TM_CTRL_HD_SCL_TM0_MASK        0x000000ff
#define BCHP_MMISC_BVNM_SCL_0_MBIST_TM_CTRL_HD_SCL_TM0_SHIFT       0

/***************************************************************************
 *BVNM_SCL_1_MBIST_TM_CTRL - BVN Middle SCL_1 MBIST TM Control
 ***************************************************************************/
/* MMISC :: BVNM_SCL_1_MBIST_TM_CTRL :: reserved0 [31:16] */
#define BCHP_MMISC_BVNM_SCL_1_MBIST_TM_CTRL_reserved0_MASK         0xffff0000
#define BCHP_MMISC_BVNM_SCL_1_MBIST_TM_CTRL_reserved0_SHIFT        16

/* MMISC :: BVNM_SCL_1_MBIST_TM_CTRL :: HD_SCL_TM1 [15:08] */
#define BCHP_MMISC_BVNM_SCL_1_MBIST_TM_CTRL_HD_SCL_TM1_MASK        0x0000ff00
#define BCHP_MMISC_BVNM_SCL_1_MBIST_TM_CTRL_HD_SCL_TM1_SHIFT       8

/* MMISC :: BVNM_SCL_1_MBIST_TM_CTRL :: HD_SCL_TM0 [07:00] */
#define BCHP_MMISC_BVNM_SCL_1_MBIST_TM_CTRL_HD_SCL_TM0_MASK        0x000000ff
#define BCHP_MMISC_BVNM_SCL_1_MBIST_TM_CTRL_HD_SCL_TM0_SHIFT       0

/***************************************************************************
 *BVNM_DNR_MBIST_TM_CTRL - BVN Middle DNR_0 MBIST TM Control
 ***************************************************************************/
/* MMISC :: BVNM_DNR_MBIST_TM_CTRL :: reserved0 [31:12] */
#define BCHP_MMISC_BVNM_DNR_MBIST_TM_CTRL_reserved0_MASK           0xfffff000
#define BCHP_MMISC_BVNM_DNR_MBIST_TM_CTRL_reserved0_SHIFT          12

/* MMISC :: BVNM_DNR_MBIST_TM_CTRL :: DNR_TM1 [11:08] */
#define BCHP_MMISC_BVNM_DNR_MBIST_TM_CTRL_DNR_TM1_MASK             0x00000f00
#define BCHP_MMISC_BVNM_DNR_MBIST_TM_CTRL_DNR_TM1_SHIFT            8

/* MMISC :: BVNM_DNR_MBIST_TM_CTRL :: DNR_TM0 [07:00] */
#define BCHP_MMISC_BVNM_DNR_MBIST_TM_CTRL_DNR_TM0_MASK             0x000000ff
#define BCHP_MMISC_BVNM_DNR_MBIST_TM_CTRL_DNR_TM0_SHIFT            0

/***************************************************************************
 *BVNM_CLOCK_CTRL - BVN Middle clock control register
 ***************************************************************************/
/* MMISC :: BVNM_CLOCK_CTRL :: reserved0 [31:01] */
#define BCHP_MMISC_BVNM_CLOCK_CTRL_reserved0_MASK                  0xfffffffe
#define BCHP_MMISC_BVNM_CLOCK_CTRL_reserved0_SHIFT                 1

/* MMISC :: BVNM_CLOCK_CTRL :: CLK_FREE_RUN_MODE [00:00] */
#define BCHP_MMISC_BVNM_CLOCK_CTRL_CLK_FREE_RUN_MODE_MASK          0x00000001
#define BCHP_MMISC_BVNM_CLOCK_CTRL_CLK_FREE_RUN_MODE_SHIFT         0

/***************************************************************************
 *SCRATCH_0 - Scratch Register
 ***************************************************************************/
/* MMISC :: SCRATCH_0 :: VALUE [31:00] */
#define BCHP_MMISC_SCRATCH_0_VALUE_MASK                            0xffffffff
#define BCHP_MMISC_SCRATCH_0_VALUE_SHIFT                           0

#endif /* #ifndef BCHP_MMISC_H__ */

/* End of File */
