/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Mar 20 12:51:03 2009
 *                 MD5 Checksum         4f0509cfa0b8fc4589050694b4a3e234
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7340/rdb/a0/bchp_moca_genet_tdma.h $
 * 
 * Hydra_Software_Devel/1   3/22/09 8:47p yuxiaz
 * PR53430: Initial version of header files.
 *
 ***************************************************************************/

#ifndef BCHP_MOCA_GENET_TDMA_H__
#define BCHP_MOCA_GENET_TDMA_H__

/***************************************************************************
 *MOCA_GENET_TDMA
 ***************************************************************************/
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD0    0x00303000 /* Descriptor Word 0 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD1    0x00303004 /* Descriptor Word 1 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD2    0x00303008 /* Descriptor Word 2 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD3    0x0030300c /* Descriptor Word 3 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD4    0x00303010 /* Descriptor Word 4 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD5    0x00303014 /* Descriptor Word 5 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD6    0x00303018 /* Descriptor Word 6 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD7    0x0030301c /* Descriptor Word 7 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD8    0x00303020 /* Descriptor Word 8 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD9    0x00303024 /* Descriptor Word 9 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD10   0x00303028 /* Descriptor Word 10 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD11   0x0030302c /* Descriptor Word 11 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD12   0x00303030 /* Descriptor Word 12 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD13   0x00303034 /* Descriptor Word 13 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD14   0x00303038 /* Descriptor Word 14 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD15   0x0030303c /* Descriptor Word 15 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD16   0x00303040 /* Descriptor Word 16 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD17   0x00303044 /* Descriptor Word 17 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD18   0x00303048 /* Descriptor Word 18 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD19   0x0030304c /* Descriptor Word 19 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD20   0x00303050 /* Descriptor Word 20 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD21   0x00303054 /* Descriptor Word 21 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD22   0x00303058 /* Descriptor Word 22 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD23   0x0030305c /* Descriptor Word 23 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD24   0x00303060 /* Descriptor Word 24 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD25   0x00303064 /* Descriptor Word 25 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD26   0x00303068 /* Descriptor Word 26 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD27   0x0030306c /* Descriptor Word 27 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD28   0x00303070 /* Descriptor Word 28 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD29   0x00303074 /* Descriptor Word 29 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD30   0x00303078 /* Descriptor Word 30 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD31   0x0030307c /* Descriptor Word 31 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD32   0x00303080 /* Descriptor Word 32 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD33   0x00303084 /* Descriptor Word 33 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD34   0x00303088 /* Descriptor Word 34 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD35   0x0030308c /* Descriptor Word 35 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD36   0x00303090 /* Descriptor Word 36 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD37   0x00303094 /* Descriptor Word 37 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD38   0x00303098 /* Descriptor Word 38 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD39   0x0030309c /* Descriptor Word 39 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD40   0x003030a0 /* Descriptor Word 40 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD41   0x003030a4 /* Descriptor Word 41 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD42   0x003030a8 /* Descriptor Word 42 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD43   0x003030ac /* Descriptor Word 43 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD44   0x003030b0 /* Descriptor Word 44 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD45   0x003030b4 /* Descriptor Word 45 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD46   0x003030b8 /* Descriptor Word 46 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD47   0x003030bc /* Descriptor Word 47 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD48   0x003030c0 /* Descriptor Word 48 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD49   0x003030c4 /* Descriptor Word 49 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD50   0x003030c8 /* Descriptor Word 50 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD51   0x003030cc /* Descriptor Word 51 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD52   0x003030d0 /* Descriptor Word 52 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD53   0x003030d4 /* Descriptor Word 53 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD54   0x003030d8 /* Descriptor Word 54 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD55   0x003030dc /* Descriptor Word 55 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD56   0x003030e0 /* Descriptor Word 56 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD57   0x003030e4 /* Descriptor Word 57 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD58   0x003030e8 /* Descriptor Word 58 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD59   0x003030ec /* Descriptor Word 59 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD60   0x003030f0 /* Descriptor Word 60 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD61   0x003030f4 /* Descriptor Word 61 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD62   0x003030f8 /* Descriptor Word 62 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD63   0x003030fc /* Descriptor Word 63 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD64   0x00303100 /* Descriptor Word 64 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD65   0x00303104 /* Descriptor Word 65 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD66   0x00303108 /* Descriptor Word 66 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD67   0x0030310c /* Descriptor Word 67 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD68   0x00303110 /* Descriptor Word 68 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD69   0x00303114 /* Descriptor Word 69 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD70   0x00303118 /* Descriptor Word 70 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD71   0x0030311c /* Descriptor Word 71 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD72   0x00303120 /* Descriptor Word 72 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD73   0x00303124 /* Descriptor Word 73 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD74   0x00303128 /* Descriptor Word 74 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD75   0x0030312c /* Descriptor Word 75 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD76   0x00303130 /* Descriptor Word 76 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD77   0x00303134 /* Descriptor Word 77 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD78   0x00303138 /* Descriptor Word 78 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD79   0x0030313c /* Descriptor Word 79 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD80   0x00303140 /* Descriptor Word 80 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD81   0x00303144 /* Descriptor Word 81 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD82   0x00303148 /* Descriptor Word 82 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD83   0x0030314c /* Descriptor Word 83 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD84   0x00303150 /* Descriptor Word 84 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD85   0x00303154 /* Descriptor Word 85 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD86   0x00303158 /* Descriptor Word 86 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD87   0x0030315c /* Descriptor Word 87 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD88   0x00303160 /* Descriptor Word 88 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD89   0x00303164 /* Descriptor Word 89 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD90   0x00303168 /* Descriptor Word 90 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD91   0x0030316c /* Descriptor Word 91 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD92   0x00303170 /* Descriptor Word 92 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD93   0x00303174 /* Descriptor Word 93 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD94   0x00303178 /* Descriptor Word 94 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD95   0x0030317c /* Descriptor Word 95 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD96   0x00303180 /* Descriptor Word 96 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD97   0x00303184 /* Descriptor Word 97 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD98   0x00303188 /* Descriptor Word 98 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD99   0x0030318c /* Descriptor Word 99 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD100  0x00303190 /* Descriptor Word 100 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD101  0x00303194 /* Descriptor Word 101 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD102  0x00303198 /* Descriptor Word 102 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD103  0x0030319c /* Descriptor Word 103 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD104  0x003031a0 /* Descriptor Word 104 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD105  0x003031a4 /* Descriptor Word 105 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD106  0x003031a8 /* Descriptor Word 106 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD107  0x003031ac /* Descriptor Word 107 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD108  0x003031b0 /* Descriptor Word 108 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD109  0x003031b4 /* Descriptor Word 109 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD110  0x003031b8 /* Descriptor Word 110 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD111  0x003031bc /* Descriptor Word 111 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD112  0x003031c0 /* Descriptor Word 112 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD113  0x003031c4 /* Descriptor Word 113 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD114  0x003031c8 /* Descriptor Word 114 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD115  0x003031cc /* Descriptor Word 115 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD116  0x003031d0 /* Descriptor Word 116 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD117  0x003031d4 /* Descriptor Word 117 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD118  0x003031d8 /* Descriptor Word 118 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD119  0x003031dc /* Descriptor Word 119 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD120  0x003031e0 /* Descriptor Word 120 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD121  0x003031e4 /* Descriptor Word 121 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD122  0x003031e8 /* Descriptor Word 122 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD123  0x003031ec /* Descriptor Word 123 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD124  0x003031f0 /* Descriptor Word 124 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD125  0x003031f4 /* Descriptor Word 125 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD126  0x003031f8 /* Descriptor Word 126 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD127  0x003031fc /* Descriptor Word 127 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD128  0x00303200 /* Descriptor Word 128 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD129  0x00303204 /* Descriptor Word 129 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD130  0x00303208 /* Descriptor Word 130 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD131  0x0030320c /* Descriptor Word 131 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD132  0x00303210 /* Descriptor Word 132 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD133  0x00303214 /* Descriptor Word 133 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD134  0x00303218 /* Descriptor Word 134 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD135  0x0030321c /* Descriptor Word 135 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD136  0x00303220 /* Descriptor Word 136 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD137  0x00303224 /* Descriptor Word 137 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD138  0x00303228 /* Descriptor Word 138 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD139  0x0030322c /* Descriptor Word 139 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD140  0x00303230 /* Descriptor Word 140 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD141  0x00303234 /* Descriptor Word 141 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD142  0x00303238 /* Descriptor Word 142 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD143  0x0030323c /* Descriptor Word 143 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD144  0x00303240 /* Descriptor Word 144 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD145  0x00303244 /* Descriptor Word 145 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD146  0x00303248 /* Descriptor Word 146 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD147  0x0030324c /* Descriptor Word 147 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD148  0x00303250 /* Descriptor Word 148 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD149  0x00303254 /* Descriptor Word 149 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD150  0x00303258 /* Descriptor Word 150 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD151  0x0030325c /* Descriptor Word 151 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD152  0x00303260 /* Descriptor Word 152 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD153  0x00303264 /* Descriptor Word 153 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD154  0x00303268 /* Descriptor Word 154 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD155  0x0030326c /* Descriptor Word 155 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD156  0x00303270 /* Descriptor Word 156 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD157  0x00303274 /* Descriptor Word 157 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD158  0x00303278 /* Descriptor Word 158 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD159  0x0030327c /* Descriptor Word 159 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD160  0x00303280 /* Descriptor Word 160 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD161  0x00303284 /* Descriptor Word 161 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD162  0x00303288 /* Descriptor Word 162 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD163  0x0030328c /* Descriptor Word 163 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD164  0x00303290 /* Descriptor Word 164 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD165  0x00303294 /* Descriptor Word 165 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD166  0x00303298 /* Descriptor Word 166 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD167  0x0030329c /* Descriptor Word 167 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD168  0x003032a0 /* Descriptor Word 168 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD169  0x003032a4 /* Descriptor Word 169 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD170  0x003032a8 /* Descriptor Word 170 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD171  0x003032ac /* Descriptor Word 171 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD172  0x003032b0 /* Descriptor Word 172 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD173  0x003032b4 /* Descriptor Word 173 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD174  0x003032b8 /* Descriptor Word 174 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD175  0x003032bc /* Descriptor Word 175 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD176  0x003032c0 /* Descriptor Word 176 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD177  0x003032c4 /* Descriptor Word 177 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD178  0x003032c8 /* Descriptor Word 178 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD179  0x003032cc /* Descriptor Word 179 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD180  0x003032d0 /* Descriptor Word 180 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD181  0x003032d4 /* Descriptor Word 181 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD182  0x003032d8 /* Descriptor Word 182 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD183  0x003032dc /* Descriptor Word 183 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD184  0x003032e0 /* Descriptor Word 184 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD185  0x003032e4 /* Descriptor Word 185 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD186  0x003032e8 /* Descriptor Word 186 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD187  0x003032ec /* Descriptor Word 187 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD188  0x003032f0 /* Descriptor Word 188 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD189  0x003032f4 /* Descriptor Word 189 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD190  0x003032f8 /* Descriptor Word 190 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD191  0x003032fc /* Descriptor Word 191 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD192  0x00303300 /* Descriptor Word 192 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD193  0x00303304 /* Descriptor Word 193 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD194  0x00303308 /* Descriptor Word 194 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD195  0x0030330c /* Descriptor Word 195 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD196  0x00303310 /* Descriptor Word 196 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD197  0x00303314 /* Descriptor Word 197 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD198  0x00303318 /* Descriptor Word 198 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD199  0x0030331c /* Descriptor Word 199 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD200  0x00303320 /* Descriptor Word 200 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD201  0x00303324 /* Descriptor Word 201 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD202  0x00303328 /* Descriptor Word 202 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD203  0x0030332c /* Descriptor Word 203 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD204  0x00303330 /* Descriptor Word 204 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD205  0x00303334 /* Descriptor Word 205 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD206  0x00303338 /* Descriptor Word 206 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD207  0x0030333c /* Descriptor Word 207 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD208  0x00303340 /* Descriptor Word 208 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD209  0x00303344 /* Descriptor Word 209 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD210  0x00303348 /* Descriptor Word 210 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD211  0x0030334c /* Descriptor Word 211 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD212  0x00303350 /* Descriptor Word 212 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD213  0x00303354 /* Descriptor Word 213 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD214  0x00303358 /* Descriptor Word 214 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD215  0x0030335c /* Descriptor Word 215 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD216  0x00303360 /* Descriptor Word 216 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD217  0x00303364 /* Descriptor Word 217 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD218  0x00303368 /* Descriptor Word 218 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD219  0x0030336c /* Descriptor Word 219 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD220  0x00303370 /* Descriptor Word 220 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD221  0x00303374 /* Descriptor Word 221 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD222  0x00303378 /* Descriptor Word 222 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD223  0x0030337c /* Descriptor Word 223 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD224  0x00303380 /* Descriptor Word 224 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD225  0x00303384 /* Descriptor Word 225 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD226  0x00303388 /* Descriptor Word 226 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD227  0x0030338c /* Descriptor Word 227 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD228  0x00303390 /* Descriptor Word 228 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD229  0x00303394 /* Descriptor Word 229 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD230  0x00303398 /* Descriptor Word 230 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD231  0x0030339c /* Descriptor Word 231 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD232  0x003033a0 /* Descriptor Word 232 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD233  0x003033a4 /* Descriptor Word 233 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD234  0x003033a8 /* Descriptor Word 234 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD235  0x003033ac /* Descriptor Word 235 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD236  0x003033b0 /* Descriptor Word 236 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD237  0x003033b4 /* Descriptor Word 237 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD238  0x003033b8 /* Descriptor Word 238 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD239  0x003033bc /* Descriptor Word 239 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD240  0x003033c0 /* Descriptor Word 240 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD241  0x003033c4 /* Descriptor Word 241 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD242  0x003033c8 /* Descriptor Word 242 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD243  0x003033cc /* Descriptor Word 243 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD244  0x003033d0 /* Descriptor Word 244 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD245  0x003033d4 /* Descriptor Word 245 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD246  0x003033d8 /* Descriptor Word 246 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD247  0x003033dc /* Descriptor Word 247 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD248  0x003033e0 /* Descriptor Word 248 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD249  0x003033e4 /* Descriptor Word 249 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD250  0x003033e8 /* Descriptor Word 250 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD251  0x003033ec /* Descriptor Word 251 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD252  0x003033f0 /* Descriptor Word 252 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD253  0x003033f4 /* Descriptor Word 253 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD254  0x003033f8 /* Descriptor Word 254 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD255  0x003033fc /* Descriptor Word 255 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD256  0x00303400 /* Descriptor Word 256 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD257  0x00303404 /* Descriptor Word 257 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD258  0x00303408 /* Descriptor Word 258 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD259  0x0030340c /* Descriptor Word 259 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD260  0x00303410 /* Descriptor Word 260 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD261  0x00303414 /* Descriptor Word 261 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD262  0x00303418 /* Descriptor Word 262 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD263  0x0030341c /* Descriptor Word 263 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD264  0x00303420 /* Descriptor Word 264 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD265  0x00303424 /* Descriptor Word 265 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD266  0x00303428 /* Descriptor Word 266 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD267  0x0030342c /* Descriptor Word 267 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD268  0x00303430 /* Descriptor Word 268 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD269  0x00303434 /* Descriptor Word 269 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD270  0x00303438 /* Descriptor Word 270 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD271  0x0030343c /* Descriptor Word 271 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD272  0x00303440 /* Descriptor Word 272 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD273  0x00303444 /* Descriptor Word 273 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD274  0x00303448 /* Descriptor Word 274 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD275  0x0030344c /* Descriptor Word 275 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD276  0x00303450 /* Descriptor Word 276 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD277  0x00303454 /* Descriptor Word 277 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD278  0x00303458 /* Descriptor Word 278 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD279  0x0030345c /* Descriptor Word 279 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD280  0x00303460 /* Descriptor Word 280 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD281  0x00303464 /* Descriptor Word 281 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD282  0x00303468 /* Descriptor Word 282 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD283  0x0030346c /* Descriptor Word 283 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD284  0x00303470 /* Descriptor Word 284 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD285  0x00303474 /* Descriptor Word 285 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD286  0x00303478 /* Descriptor Word 286 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD287  0x0030347c /* Descriptor Word 287 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD288  0x00303480 /* Descriptor Word 288 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD289  0x00303484 /* Descriptor Word 289 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD290  0x00303488 /* Descriptor Word 290 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD291  0x0030348c /* Descriptor Word 291 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD292  0x00303490 /* Descriptor Word 292 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD293  0x00303494 /* Descriptor Word 293 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD294  0x00303498 /* Descriptor Word 294 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD295  0x0030349c /* Descriptor Word 295 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD296  0x003034a0 /* Descriptor Word 296 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD297  0x003034a4 /* Descriptor Word 297 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD298  0x003034a8 /* Descriptor Word 298 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD299  0x003034ac /* Descriptor Word 299 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD300  0x003034b0 /* Descriptor Word 300 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD301  0x003034b4 /* Descriptor Word 301 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD302  0x003034b8 /* Descriptor Word 302 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD303  0x003034bc /* Descriptor Word 303 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD304  0x003034c0 /* Descriptor Word 304 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD305  0x003034c4 /* Descriptor Word 305 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD306  0x003034c8 /* Descriptor Word 306 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD307  0x003034cc /* Descriptor Word 307 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD308  0x003034d0 /* Descriptor Word 308 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD309  0x003034d4 /* Descriptor Word 309 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD310  0x003034d8 /* Descriptor Word 310 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD311  0x003034dc /* Descriptor Word 311 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD312  0x003034e0 /* Descriptor Word 312 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD313  0x003034e4 /* Descriptor Word 313 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD314  0x003034e8 /* Descriptor Word 314 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD315  0x003034ec /* Descriptor Word 315 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD316  0x003034f0 /* Descriptor Word 316 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD317  0x003034f4 /* Descriptor Word 317 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD318  0x003034f8 /* Descriptor Word 318 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD319  0x003034fc /* Descriptor Word 319 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD320  0x00303500 /* Descriptor Word 320 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD321  0x00303504 /* Descriptor Word 321 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD322  0x00303508 /* Descriptor Word 322 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD323  0x0030350c /* Descriptor Word 323 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD324  0x00303510 /* Descriptor Word 324 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD325  0x00303514 /* Descriptor Word 325 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD326  0x00303518 /* Descriptor Word 326 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD327  0x0030351c /* Descriptor Word 327 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD328  0x00303520 /* Descriptor Word 328 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD329  0x00303524 /* Descriptor Word 329 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD330  0x00303528 /* Descriptor Word 330 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD331  0x0030352c /* Descriptor Word 331 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD332  0x00303530 /* Descriptor Word 332 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD333  0x00303534 /* Descriptor Word 333 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD334  0x00303538 /* Descriptor Word 334 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD335  0x0030353c /* Descriptor Word 335 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD336  0x00303540 /* Descriptor Word 336 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD337  0x00303544 /* Descriptor Word 337 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD338  0x00303548 /* Descriptor Word 338 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD339  0x0030354c /* Descriptor Word 339 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD340  0x00303550 /* Descriptor Word 340 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD341  0x00303554 /* Descriptor Word 341 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD342  0x00303558 /* Descriptor Word 342 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD343  0x0030355c /* Descriptor Word 343 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD344  0x00303560 /* Descriptor Word 344 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD345  0x00303564 /* Descriptor Word 345 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD346  0x00303568 /* Descriptor Word 346 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD347  0x0030356c /* Descriptor Word 347 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD348  0x00303570 /* Descriptor Word 348 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD349  0x00303574 /* Descriptor Word 349 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD350  0x00303578 /* Descriptor Word 350 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD351  0x0030357c /* Descriptor Word 351 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD352  0x00303580 /* Descriptor Word 352 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD353  0x00303584 /* Descriptor Word 353 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD354  0x00303588 /* Descriptor Word 354 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD355  0x0030358c /* Descriptor Word 355 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD356  0x00303590 /* Descriptor Word 356 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD357  0x00303594 /* Descriptor Word 357 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD358  0x00303598 /* Descriptor Word 358 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD359  0x0030359c /* Descriptor Word 359 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD360  0x003035a0 /* Descriptor Word 360 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD361  0x003035a4 /* Descriptor Word 361 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD362  0x003035a8 /* Descriptor Word 362 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD363  0x003035ac /* Descriptor Word 363 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD364  0x003035b0 /* Descriptor Word 364 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD365  0x003035b4 /* Descriptor Word 365 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD366  0x003035b8 /* Descriptor Word 366 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD367  0x003035bc /* Descriptor Word 367 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD368  0x003035c0 /* Descriptor Word 368 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD369  0x003035c4 /* Descriptor Word 369 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD370  0x003035c8 /* Descriptor Word 370 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD371  0x003035cc /* Descriptor Word 371 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD372  0x003035d0 /* Descriptor Word 372 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD373  0x003035d4 /* Descriptor Word 373 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD374  0x003035d8 /* Descriptor Word 374 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD375  0x003035dc /* Descriptor Word 375 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD376  0x003035e0 /* Descriptor Word 376 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD377  0x003035e4 /* Descriptor Word 377 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD378  0x003035e8 /* Descriptor Word 378 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD379  0x003035ec /* Descriptor Word 379 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD380  0x003035f0 /* Descriptor Word 380 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD381  0x003035f4 /* Descriptor Word 381 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD382  0x003035f8 /* Descriptor Word 382 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD383  0x003035fc /* Descriptor Word 383 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD384  0x00303600 /* Descriptor Word 384 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD385  0x00303604 /* Descriptor Word 385 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD386  0x00303608 /* Descriptor Word 386 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD387  0x0030360c /* Descriptor Word 387 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD388  0x00303610 /* Descriptor Word 388 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD389  0x00303614 /* Descriptor Word 389 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD390  0x00303618 /* Descriptor Word 390 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD391  0x0030361c /* Descriptor Word 391 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD392  0x00303620 /* Descriptor Word 392 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD393  0x00303624 /* Descriptor Word 393 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD394  0x00303628 /* Descriptor Word 394 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD395  0x0030362c /* Descriptor Word 395 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD396  0x00303630 /* Descriptor Word 396 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD397  0x00303634 /* Descriptor Word 397 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD398  0x00303638 /* Descriptor Word 398 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD399  0x0030363c /* Descriptor Word 399 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD400  0x00303640 /* Descriptor Word 400 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD401  0x00303644 /* Descriptor Word 401 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD402  0x00303648 /* Descriptor Word 402 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD403  0x0030364c /* Descriptor Word 403 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD404  0x00303650 /* Descriptor Word 404 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD405  0x00303654 /* Descriptor Word 405 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD406  0x00303658 /* Descriptor Word 406 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD407  0x0030365c /* Descriptor Word 407 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD408  0x00303660 /* Descriptor Word 408 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD409  0x00303664 /* Descriptor Word 409 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD410  0x00303668 /* Descriptor Word 410 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD411  0x0030366c /* Descriptor Word 411 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD412  0x00303670 /* Descriptor Word 412 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD413  0x00303674 /* Descriptor Word 413 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD414  0x00303678 /* Descriptor Word 414 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD415  0x0030367c /* Descriptor Word 415 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD416  0x00303680 /* Descriptor Word 416 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD417  0x00303684 /* Descriptor Word 417 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD418  0x00303688 /* Descriptor Word 418 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD419  0x0030368c /* Descriptor Word 419 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD420  0x00303690 /* Descriptor Word 420 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD421  0x00303694 /* Descriptor Word 421 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD422  0x00303698 /* Descriptor Word 422 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD423  0x0030369c /* Descriptor Word 423 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD424  0x003036a0 /* Descriptor Word 424 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD425  0x003036a4 /* Descriptor Word 425 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD426  0x003036a8 /* Descriptor Word 426 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD427  0x003036ac /* Descriptor Word 427 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD428  0x003036b0 /* Descriptor Word 428 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD429  0x003036b4 /* Descriptor Word 429 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD430  0x003036b8 /* Descriptor Word 430 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD431  0x003036bc /* Descriptor Word 431 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD432  0x003036c0 /* Descriptor Word 432 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD433  0x003036c4 /* Descriptor Word 433 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD434  0x003036c8 /* Descriptor Word 434 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD435  0x003036cc /* Descriptor Word 435 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD436  0x003036d0 /* Descriptor Word 436 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD437  0x003036d4 /* Descriptor Word 437 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD438  0x003036d8 /* Descriptor Word 438 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD439  0x003036dc /* Descriptor Word 439 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD440  0x003036e0 /* Descriptor Word 440 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD441  0x003036e4 /* Descriptor Word 441 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD442  0x003036e8 /* Descriptor Word 442 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD443  0x003036ec /* Descriptor Word 443 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD444  0x003036f0 /* Descriptor Word 444 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD445  0x003036f4 /* Descriptor Word 445 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD446  0x003036f8 /* Descriptor Word 446 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD447  0x003036fc /* Descriptor Word 447 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD448  0x00303700 /* Descriptor Word 448 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD449  0x00303704 /* Descriptor Word 449 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD450  0x00303708 /* Descriptor Word 450 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD451  0x0030370c /* Descriptor Word 451 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD452  0x00303710 /* Descriptor Word 452 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD453  0x00303714 /* Descriptor Word 453 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD454  0x00303718 /* Descriptor Word 454 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD455  0x0030371c /* Descriptor Word 455 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD456  0x00303720 /* Descriptor Word 456 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD457  0x00303724 /* Descriptor Word 457 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD458  0x00303728 /* Descriptor Word 458 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD459  0x0030372c /* Descriptor Word 459 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD460  0x00303730 /* Descriptor Word 460 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD461  0x00303734 /* Descriptor Word 461 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD462  0x00303738 /* Descriptor Word 462 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD463  0x0030373c /* Descriptor Word 463 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD464  0x00303740 /* Descriptor Word 464 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD465  0x00303744 /* Descriptor Word 465 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD466  0x00303748 /* Descriptor Word 466 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD467  0x0030374c /* Descriptor Word 467 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD468  0x00303750 /* Descriptor Word 468 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD469  0x00303754 /* Descriptor Word 469 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD470  0x00303758 /* Descriptor Word 470 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD471  0x0030375c /* Descriptor Word 471 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD472  0x00303760 /* Descriptor Word 472 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD473  0x00303764 /* Descriptor Word 473 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD474  0x00303768 /* Descriptor Word 474 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD475  0x0030376c /* Descriptor Word 475 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD476  0x00303770 /* Descriptor Word 476 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD477  0x00303774 /* Descriptor Word 477 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD478  0x00303778 /* Descriptor Word 478 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD479  0x0030377c /* Descriptor Word 479 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD480  0x00303780 /* Descriptor Word 480 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD481  0x00303784 /* Descriptor Word 481 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD482  0x00303788 /* Descriptor Word 482 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD483  0x0030378c /* Descriptor Word 483 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD484  0x00303790 /* Descriptor Word 484 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD485  0x00303794 /* Descriptor Word 485 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD486  0x00303798 /* Descriptor Word 486 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD487  0x0030379c /* Descriptor Word 487 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD488  0x003037a0 /* Descriptor Word 488 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD489  0x003037a4 /* Descriptor Word 489 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD490  0x003037a8 /* Descriptor Word 490 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD491  0x003037ac /* Descriptor Word 491 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD492  0x003037b0 /* Descriptor Word 492 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD493  0x003037b4 /* Descriptor Word 493 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD494  0x003037b8 /* Descriptor Word 494 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD495  0x003037bc /* Descriptor Word 495 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD496  0x003037c0 /* Descriptor Word 496 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD497  0x003037c4 /* Descriptor Word 497 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD498  0x003037c8 /* Descriptor Word 498 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD499  0x003037cc /* Descriptor Word 499 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD500  0x003037d0 /* Descriptor Word 500 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD501  0x003037d4 /* Descriptor Word 501 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD502  0x003037d8 /* Descriptor Word 502 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD503  0x003037dc /* Descriptor Word 503 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD504  0x003037e0 /* Descriptor Word 504 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD505  0x003037e4 /* Descriptor Word 505 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD506  0x003037e8 /* Descriptor Word 506 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD507  0x003037ec /* Descriptor Word 507 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD508  0x003037f0 /* Descriptor Word 508 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD509  0x003037f4 /* Descriptor Word 509 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD510  0x003037f8 /* Descriptor Word 510 Register */
#define BCHP_MOCA_GENET_TDMA_DESCRIPTOR_WORD511  0x003037fc /* Descriptor Word 511 Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER0       0x00303800 /* Ring Buffer 0 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX0     0x00303804 /* Ring Buffer 0 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX0     0x00303808 /* Ring Buffer 0 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE0      0x0030380c /* Ring Buffer 0 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS0      0x00303810 /* Ring Buffer 0 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS0        0x00303814 /* Ring Buffer 0 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold0 0x00303818 /* Ring Buffer 0 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD0        0x0030381c /* Ring Buffer 0 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER0      0x00303820 /* Ring Buffer 0 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED0_0           0x00303824 /* Ring Buffer 0 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED0_1           0x00303828 /* Ring Buffer 0 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED0_2           0x0030382c /* Ring Buffer 0 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED0_3           0x00303830 /* Ring Buffer 0 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED0_4           0x00303834 /* Ring Buffer 0 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED0_5           0x00303838 /* Ring Buffer 0 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED0_6           0x0030383c /* Ring Buffer 0 Unused Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER1       0x00303840 /* Ring Buffer 1 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX1     0x00303844 /* Ring Buffer 1 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX1     0x00303848 /* Ring Buffer 1 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE1      0x0030384c /* Ring Buffer 1 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS1      0x00303850 /* Ring Buffer 1 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS1        0x00303854 /* Ring Buffer 1 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold1 0x00303858 /* Ring Buffer 1 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD1        0x0030385c /* Ring Buffer 1 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER1      0x00303860 /* Ring Buffer 1 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED1_0           0x00303864 /* Ring Buffer 1 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED1_1           0x00303868 /* Ring Buffer 1 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED1_2           0x0030386c /* Ring Buffer 1 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED1_3           0x00303870 /* Ring Buffer 1 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED1_4           0x00303874 /* Ring Buffer 1 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED1_5           0x00303878 /* Ring Buffer 1 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED1_6           0x0030387c /* Ring Buffer 1 Unused Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER2       0x00303880 /* Ring Buffer 2 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX2     0x00303884 /* Ring Buffer 2 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX2     0x00303888 /* Ring Buffer 2 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE2      0x0030388c /* Ring Buffer 2 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS2      0x00303890 /* Ring Buffer 2 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS2        0x00303894 /* Ring Buffer 2 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold2 0x00303898 /* Ring Buffer 2 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD2        0x0030389c /* Ring Buffer 2 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER2      0x003038a0 /* Ring Buffer 2 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED2_0           0x003038a4 /* Ring Buffer 2 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED2_1           0x003038a8 /* Ring Buffer 2 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED2_2           0x003038ac /* Ring Buffer 2 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED2_3           0x003038b0 /* Ring Buffer 2 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED2_4           0x003038b4 /* Ring Buffer 2 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED2_5           0x003038b8 /* Ring Buffer 2 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED2_6           0x003038bc /* Ring Buffer 2 Unused Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER3       0x003038c0 /* Ring Buffer 3 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX3     0x003038c4 /* Ring Buffer 3 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX3     0x003038c8 /* Ring Buffer 3 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE3      0x003038cc /* Ring Buffer 3 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS3      0x003038d0 /* Ring Buffer 3 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS3        0x003038d4 /* Ring Buffer 3 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold3 0x003038d8 /* Ring Buffer 3 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD3        0x003038dc /* Ring Buffer 3 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER3      0x003038e0 /* Ring Buffer 3 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED3_0           0x003038e4 /* Ring Buffer 3 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED3_1           0x003038e8 /* Ring Buffer 3 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED3_2           0x003038ec /* Ring Buffer 3 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED3_3           0x003038f0 /* Ring Buffer 3 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED3_4           0x003038f4 /* Ring Buffer 3 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED3_5           0x003038f8 /* Ring Buffer 3 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED3_6           0x003038fc /* Ring Buffer 3 Unused Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER4       0x00303900 /* Ring Buffer 4 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX4     0x00303904 /* Ring Buffer 4 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX4     0x00303908 /* Ring Buffer 4 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE4      0x0030390c /* Ring Buffer 4 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS4      0x00303910 /* Ring Buffer 4 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS4        0x00303914 /* Ring Buffer 4 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold4 0x00303918 /* Ring Buffer 4 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD4        0x0030391c /* Ring Buffer 4 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER4      0x00303920 /* Ring Buffer 4 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED4_0           0x00303924 /* Ring Buffer 4 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED4_1           0x00303928 /* Ring Buffer 4 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED4_2           0x0030392c /* Ring Buffer 4 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED4_3           0x00303930 /* Ring Buffer 4 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED4_4           0x00303934 /* Ring Buffer 4 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED4_5           0x00303938 /* Ring Buffer 4 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED4_6           0x0030393c /* Ring Buffer 4 Unused Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER5       0x00303940 /* Ring Buffer 5 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX5     0x00303944 /* Ring Buffer 5 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX5     0x00303948 /* Ring Buffer 5 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE5      0x0030394c /* Ring Buffer 5 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS5      0x00303950 /* Ring Buffer 5 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS5        0x00303954 /* Ring Buffer 5 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold5 0x00303958 /* Ring Buffer 5 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD5        0x0030395c /* Ring Buffer 5 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER5      0x00303960 /* Ring Buffer 5 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED5_0           0x00303964 /* Ring Buffer 5 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED5_1           0x00303968 /* Ring Buffer 5 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED5_2           0x0030396c /* Ring Buffer 5 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED5_3           0x00303970 /* Ring Buffer 5 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED5_4           0x00303974 /* Ring Buffer 5 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED5_5           0x00303978 /* Ring Buffer 5 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED5_6           0x0030397c /* Ring Buffer 5 Unused Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER6       0x00303980 /* Ring Buffer 6 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX6     0x00303984 /* Ring Buffer 6 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX6     0x00303988 /* Ring Buffer 6 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE6      0x0030398c /* Ring Buffer 6 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS6      0x00303990 /* Ring Buffer 6 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS6        0x00303994 /* Ring Buffer 6 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold6 0x00303998 /* Ring Buffer 6 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD6        0x0030399c /* Ring Buffer 6 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER6      0x003039a0 /* Ring Buffer 6 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED6_0           0x003039a4 /* Ring Buffer 6 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED6_1           0x003039a8 /* Ring Buffer 6 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED6_2           0x003039ac /* Ring Buffer 6 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED6_3           0x003039b0 /* Ring Buffer 6 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED6_4           0x003039b4 /* Ring Buffer 6 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED6_5           0x003039b8 /* Ring Buffer 6 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED6_6           0x003039bc /* Ring Buffer 6 Unused Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER7       0x003039c0 /* Ring Buffer 7 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX7     0x003039c4 /* Ring Buffer 7 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX7     0x003039c8 /* Ring Buffer 7 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE7      0x003039cc /* Ring Buffer 7 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS7      0x003039d0 /* Ring Buffer 7 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS7        0x003039d4 /* Ring Buffer 7 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold7 0x003039d8 /* Ring Buffer 7 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD7        0x003039dc /* Ring Buffer 7 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER7      0x003039e0 /* Ring Buffer 7 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED7_0           0x003039e4 /* Ring Buffer 7 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED7_1           0x003039e8 /* Ring Buffer 7 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED7_2           0x003039ec /* Ring Buffer 7 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED7_3           0x003039f0 /* Ring Buffer 7 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED7_4           0x003039f4 /* Ring Buffer 7 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED7_5           0x003039f8 /* Ring Buffer 7 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED7_6           0x003039fc /* Ring Buffer 7 Unused Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER8       0x00303a00 /* Ring Buffer 8 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX8     0x00303a04 /* Ring Buffer 8 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX8     0x00303a08 /* Ring Buffer 8 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE8      0x00303a0c /* Ring Buffer 8 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS8      0x00303a10 /* Ring Buffer 8 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS8        0x00303a14 /* Ring Buffer 8 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold8 0x00303a18 /* Ring Buffer 8 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD8        0x00303a1c /* Ring Buffer 8 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER8      0x00303a20 /* Ring Buffer 8 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED8_0           0x00303a24 /* Ring Buffer 8 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED8_1           0x00303a28 /* Ring Buffer 8 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED8_2           0x00303a2c /* Ring Buffer 8 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED8_3           0x00303a30 /* Ring Buffer 8 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED8_4           0x00303a34 /* Ring Buffer 8 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED8_5           0x00303a38 /* Ring Buffer 8 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED8_6           0x00303a3c /* Ring Buffer 8 Unused Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER9       0x00303a40 /* Ring Buffer 9 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX9     0x00303a44 /* Ring Buffer 9 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX9     0x00303a48 /* Ring Buffer 9 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE9      0x00303a4c /* Ring Buffer 9 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS9      0x00303a50 /* Ring Buffer 9 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS9        0x00303a54 /* Ring Buffer 9 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold9 0x00303a58 /* Ring Buffer 9 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD9        0x00303a5c /* Ring Buffer 9 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER9      0x00303a60 /* Ring Buffer 9 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED9_0           0x00303a64 /* Ring Buffer 9 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED9_1           0x00303a68 /* Ring Buffer 9 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED9_2           0x00303a6c /* Ring Buffer 9 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED9_3           0x00303a70 /* Ring Buffer 9 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED9_4           0x00303a74 /* Ring Buffer 9 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED9_5           0x00303a78 /* Ring Buffer 9 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED9_6           0x00303a7c /* Ring Buffer 9 Unused Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER10      0x00303a80 /* Ring Buffer 10 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX10    0x00303a84 /* Ring Buffer 10 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX10    0x00303a88 /* Ring Buffer 10 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE10     0x00303a8c /* Ring Buffer 10 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS10     0x00303a90 /* Ring Buffer 10 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS10       0x00303a94 /* Ring Buffer 10 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold10 0x00303a98 /* Ring Buffer 10 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD10       0x00303a9c /* Ring Buffer 10 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER10     0x00303aa0 /* Ring Buffer 10 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED10_0          0x00303aa4 /* Ring Buffer 10 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED10_1          0x00303aa8 /* Ring Buffer 10 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED10_2          0x00303aac /* Ring Buffer 10 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED10_3          0x00303ab0 /* Ring Buffer 10 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED10_4          0x00303ab4 /* Ring Buffer 10 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED10_5          0x00303ab8 /* Ring Buffer 10 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED10_6          0x00303abc /* Ring Buffer 10 Unused Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER11      0x00303ac0 /* Ring Buffer 11 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX11    0x00303ac4 /* Ring Buffer 11 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX11    0x00303ac8 /* Ring Buffer 11 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE11     0x00303acc /* Ring Buffer 11 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS11     0x00303ad0 /* Ring Buffer 11 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS11       0x00303ad4 /* Ring Buffer 11 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold11 0x00303ad8 /* Ring Buffer 11 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD11       0x00303adc /* Ring Buffer 11 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER11     0x00303ae0 /* Ring Buffer 11 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED11_0          0x00303ae4 /* Ring Buffer 11 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED11_1          0x00303ae8 /* Ring Buffer 11 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED11_2          0x00303aec /* Ring Buffer 11 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED11_3          0x00303af0 /* Ring Buffer 11 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED11_4          0x00303af4 /* Ring Buffer 11 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED11_5          0x00303af8 /* Ring Buffer 11 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED11_6          0x00303afc /* Ring Buffer 11 Unused Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER12      0x00303b00 /* Ring Buffer 12 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX12    0x00303b04 /* Ring Buffer 12 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX12    0x00303b08 /* Ring Buffer 12 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE12     0x00303b0c /* Ring Buffer 12 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS12     0x00303b10 /* Ring Buffer 12 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS12       0x00303b14 /* Ring Buffer 12 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold12 0x00303b18 /* Ring Buffer 12 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD12       0x00303b1c /* Ring Buffer 12 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER12     0x00303b20 /* Ring Buffer 12 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED12_0          0x00303b24 /* Ring Buffer 12 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED12_1          0x00303b28 /* Ring Buffer 12 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED12_2          0x00303b2c /* Ring Buffer 12 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED12_3          0x00303b30 /* Ring Buffer 12 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED12_4          0x00303b34 /* Ring Buffer 12 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED12_5          0x00303b38 /* Ring Buffer 12 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED12_6          0x00303b3c /* Ring Buffer 12 Unused Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER13      0x00303b40 /* Ring Buffer 13 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX13    0x00303b44 /* Ring Buffer 13 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX13    0x00303b48 /* Ring Buffer 13 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE13     0x00303b4c /* Ring Buffer 13 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS13     0x00303b50 /* Ring Buffer 13 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS13       0x00303b54 /* Ring Buffer 13 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold13 0x00303b58 /* Ring Buffer 13 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD13       0x00303b5c /* Ring Buffer 13 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER13     0x00303b60 /* Ring Buffer 13 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED13_0          0x00303b64 /* Ring Buffer 13 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED13_1          0x00303b68 /* Ring Buffer 13 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED13_2          0x00303b6c /* Ring Buffer 13 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED13_3          0x00303b70 /* Ring Buffer 13 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED13_4          0x00303b74 /* Ring Buffer 13 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED13_5          0x00303b78 /* Ring Buffer 13 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED13_6          0x00303b7c /* Ring Buffer 13 Unused Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER14      0x00303b80 /* Ring Buffer 14 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX14    0x00303b84 /* Ring Buffer 14 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX14    0x00303b88 /* Ring Buffer 14 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE14     0x00303b8c /* Ring Buffer 14 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS14     0x00303b90 /* Ring Buffer 14 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS14       0x00303b94 /* Ring Buffer 14 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold14 0x00303b98 /* Ring Buffer 14 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD14       0x00303b9c /* Ring Buffer 14 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER14     0x00303ba0 /* Ring Buffer 14 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED14_0          0x00303ba4 /* Ring Buffer 14 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED14_1          0x00303ba8 /* Ring Buffer 14 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED14_2          0x00303bac /* Ring Buffer 14 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED14_3          0x00303bb0 /* Ring Buffer 14 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED14_4          0x00303bb4 /* Ring Buffer 14 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED14_5          0x00303bb8 /* Ring Buffer 14 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED14_6          0x00303bbc /* Ring Buffer 14 Unused Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER15      0x00303bc0 /* Ring Buffer 15 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX15    0x00303bc4 /* Ring Buffer 15 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX15    0x00303bc8 /* Ring Buffer 15 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE15     0x00303bcc /* Ring Buffer 15 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS15     0x00303bd0 /* Ring Buffer 15 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS15       0x00303bd4 /* Ring Buffer 15 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold15 0x00303bd8 /* Ring Buffer 15 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD15       0x00303bdc /* Ring Buffer 15 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER15     0x00303be0 /* Ring Buffer 15 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED15_0          0x00303be4 /* Ring Buffer 15 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED15_1          0x00303be8 /* Ring Buffer 15 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED15_2          0x00303bec /* Ring Buffer 15 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED15_3          0x00303bf0 /* Ring Buffer 15 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED15_4          0x00303bf4 /* Ring Buffer 15 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED15_5          0x00303bf8 /* Ring Buffer 15 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED15_6          0x00303bfc /* Ring Buffer 15 Unused Register */
#define BCHP_MOCA_GENET_TDMA_READ_POINTER16      0x00303c00 /* Ring Buffer 16 Read Pointer Register */
#define BCHP_MOCA_GENET_TDMA_CONSUMER_INDEX16    0x00303c04 /* Ring Buffer 16 Consumer Index Register */
#define BCHP_MOCA_GENET_TDMA_PRODUCER_INDEX16    0x00303c08 /* Ring Buffer 16 Producer Index Register */
#define BCHP_MOCA_GENET_TDMA_RING_BUF_SIZE16     0x00303c0c /* Ring Buffer 16 Size Register */
#define BCHP_MOCA_GENET_TDMA_START_ADDRESS16     0x00303c10 /* Ring Buffer 16 Start Address Register */
#define BCHP_MOCA_GENET_TDMA_END_ADDRESS16       0x00303c14 /* Ring Buffer 16 End Address Register */
#define BCHP_MOCA_GENET_TDMA_Multiple_Buffers_Done_Interrupt_Threshold16 0x00303c18 /* Ring Buffer 16 Multiple Buffers Done Interrupt Threshold Register */
#define BCHP_MOCA_GENET_TDMA_FLOW_PERIOD16       0x00303c1c /* Ring Buffer 16 Flow Period Register */
#define BCHP_MOCA_GENET_TDMA_WRITE_POINTER16     0x00303c20 /* Ring Buffer 16 Write Pointer Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED16_0          0x00303c24 /* Ring Buffer 16 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED16_1          0x00303c28 /* Ring Buffer 16 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED16_2          0x00303c2c /* Ring Buffer 16 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED16_3          0x00303c30 /* Ring Buffer 16 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED16_4          0x00303c34 /* Ring Buffer 16 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED16_5          0x00303c38 /* Ring Buffer 16 Unused Register */
#define BCHP_MOCA_GENET_TDMA_UNUSED16_6          0x00303c3c /* Ring Buffer 16 Unused Register */
#define BCHP_MOCA_GENET_TDMA_CONTROL             0x00303c40 /* TDMA Control Register */
#define BCHP_MOCA_GENET_TDMA_STATUS              0x00303c44 /* TDMA Status Register */
#define BCHP_MOCA_GENET_TDMA_SCB_BURST_SIZE      0x00303c4c /* Maximum SCB Burst Size Register */
#define BCHP_MOCA_GENET_TDMA_ACTIVITY            0x00303c50 /* TDMA Activity Register */
#define BCHP_MOCA_GENET_TDMA_MASK                0x00303c54 /* Backpressure Mask Register */
#define BCHP_MOCA_GENET_TDMA_MAP0                0x00303c58 /* Ring Buffer to Flow Mapping Register 0 */
#define BCHP_MOCA_GENET_TDMA_MAP1                0x00303c5c /* Ring Buffer to Flow Mapping Register 1 */
#define BCHP_MOCA_GENET_TDMA_MAP2                0x00303c60 /* Ring Buffer to Flow Mapping Register 2 */
#define BCHP_MOCA_GENET_TDMA_BACK_STATUS         0x00303c64 /* Backpressure Status Register */
#define BCHP_MOCA_GENET_TDMA_OVERRIDE            0x00303c68 /* SCB Endianess Override Register */
#define BCHP_MOCA_GENET_TDMA_RATE_LIMIT_CTRL     0x00303c6c /* TDMA Rate Limiting Control Register */
#define BCHP_MOCA_GENET_TDMA_ARB_CTRL            0x00303c70 /* TDMA Arbitration Control Register */
#define BCHP_MOCA_GENET_TDMA_PRIORITY0           0x00303c74 /* Ring Buffer to Priority Mapping Register 0 */
#define BCHP_MOCA_GENET_TDMA_PRIORITY1           0x00303c78 /* Ring Buffer to Priority Mapping Register 1 */
#define BCHP_MOCA_GENET_TDMA_PRIORITY2           0x00303c7c /* Ring Buffer to Priority Mapping Register 2 */
#define BCHP_MOCA_GENET_TDMA_TEST                0x00303c80 /* TEST Register */
#define BCHP_MOCA_GENET_TDMA_DEBUG               0x00303c84 /* Debug Register */
#define BCHP_MOCA_GENET_TDMA_RATE_ADJ            0x00303c88 /* Rate Adjustment  Register */

#endif /* #ifndef BCHP_MOCA_GENET_TDMA_H__ */

/* End of File */
