/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Mar 20 13:06:20 2009
 *                 MD5 Checksum         4f0509cfa0b8fc4589050694b4a3e234
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7340/rdb/a0/bchp_qpsk_grb.h $
 * 
 * Hydra_Software_Devel/1   3/22/09 9:00p yuxiaz
 * PR53430: Initial version of header files.
 *
 ***************************************************************************/

#ifndef BCHP_QPSK_GRB_H__
#define BCHP_QPSK_GRB_H__

/***************************************************************************
 *QPSK_GRB - QPSK GISB Bridge Registers
 ***************************************************************************/
#define BCHP_QPSK_GRB_REVISION                   0x01300f00 /* GR Bridge Revision */
#define BCHP_QPSK_GRB_CTRL                       0x01300f04 /* GR Bridge Control Register */
#define BCHP_QPSK_GRB_SW_RESET_0                 0x01300f08 /* GR Bridge Software Reset 0 Register */
#define BCHP_QPSK_GRB_SW_RESET_1                 0x01300f0c /* GR Bridge Software Reset 1 Register */

#endif /* #ifndef BCHP_QPSK_GRB_H__ */

/* End of File */
