/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Mar 20 12:54:18 2009
 *                 MD5 Checksum         4f0509cfa0b8fc4589050694b4a3e234
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7340/rdb/a0/bchp_bscb.h $
 * 
 * Hydra_Software_Devel/1   3/22/09 7:51p yuxiaz
 * PR53430: Initial version of header files.
 *
 ***************************************************************************/

#ifndef BCHP_BSCB_H__
#define BCHP_BSCB_H__

/***************************************************************************
 *BSCB - Broadcom Serial Control Master B
 ***************************************************************************/
#define BCHP_BSCB_CHIP_ADDRESS                   0x00406280 /* BSC Chip Address And Read/Write Control */
#define BCHP_BSCB_DATA_IN0                       0x00406284 /* BSC Write Data Register 0 */
#define BCHP_BSCB_DATA_IN1                       0x00406288 /* BSC Write Data Register 1 */
#define BCHP_BSCB_DATA_IN2                       0x0040628c /* BSC Write Data Register 2 */
#define BCHP_BSCB_DATA_IN3                       0x00406290 /* BSC Write Data Register 3 */
#define BCHP_BSCB_DATA_IN4                       0x00406294 /* BSC Write Data Register 4 */
#define BCHP_BSCB_DATA_IN5                       0x00406298 /* BSC Write Data Register 5 */
#define BCHP_BSCB_DATA_IN6                       0x0040629c /* BSC Write Data Register 6 */
#define BCHP_BSCB_DATA_IN7                       0x004062a0 /* BSC Write Data Register 7 */
#define BCHP_BSCB_CNT_REG                        0x004062a4 /* BSC Transfer Count Register */
#define BCHP_BSCB_CTL_REG                        0x004062a8 /* BSC Control Register */
#define BCHP_BSCB_IIC_ENABLE                     0x004062ac /* BSC Read/Write Enable And Interrupt */
#define BCHP_BSCB_DATA_OUT0                      0x004062b0 /* BSC Read Data Register 0 */
#define BCHP_BSCB_DATA_OUT1                      0x004062b4 /* BSC Read Data Register 1 */
#define BCHP_BSCB_DATA_OUT2                      0x004062b8 /* BSC Read Data Register 2 */
#define BCHP_BSCB_DATA_OUT3                      0x004062bc /* BSC Read Data Register 3 */
#define BCHP_BSCB_DATA_OUT4                      0x004062c0 /* BSC Read Data Register 4 */
#define BCHP_BSCB_DATA_OUT5                      0x004062c4 /* BSC Read Data Register 5 */
#define BCHP_BSCB_DATA_OUT6                      0x004062c8 /* BSC Read Data Register 6 */
#define BCHP_BSCB_DATA_OUT7                      0x004062cc /* BSC Read Data Register 7 */
#define BCHP_BSCB_CTLHI_REG                      0x004062d0 /* BSC Control Register */
#define BCHP_BSCB_SCL_PARAM                      0x004062d4 /* BSC SCL Parameter Register */

#endif /* #ifndef BCHP_BSCB_H__ */

/* End of File */
