/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Mar 20 12:53:00 2009
 *                 MD5 Checksum         4f0509cfa0b8fc4589050694b4a3e234
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7340/rdb/a0/bchp_lbox_0.h $
 * 
 * Hydra_Software_Devel/1   3/22/09 8:35p yuxiaz
 * PR53430: Initial version of header files.
 *
 ***************************************************************************/

#ifndef BCHP_LBOX_0_H__
#define BCHP_LBOX_0_H__

/***************************************************************************
 *LBOX_0 - Letter Box Detector 0 Registers
 ***************************************************************************/
#define BCHP_LBOX_0_REVISION_ID                  0x00125000 /* Chip Revision ID. */
#define BCHP_LBOX_0_ENABLE_ACCEPT                0x00125004 /* OPERATIONS MODES (Control). */
#define BCHP_LBOX_0_CONFIGURATION                0x00125008 /* OPERATIONS MODES (Control). */
#define BCHP_LBOX_0_HORIZONTAL_WINDOW_REGION     0x0012500c /* Top/Bottom Horizontal Region (Control). */
#define BCHP_LBOX_0_VERTICAL_WINDOW_REGION       0x00125010 /* Left/Right Vertical Region (Control). */
#define BCHP_LBOX_0_PIXEL_THRESHOLD              0x00125014 /* Black Pixel Threshold (Control). */
#define BCHP_LBOX_0_BLACK_LINE_THRESHOLD_NTA     0x00125018 /* Black Line Threshold (Control - Number & Threshold Algorithm) */
#define BCHP_LBOX_0_BLACK_COL_THRESHOLD_NTA      0x0012501c /* Black Column Threshold (Control - Number & Threshold Algorithm) */
#define BCHP_LBOX_0_WHITE_LINE_THRESHOLD_NTA     0x00125020 /* White Line Threshold (Control - Number & Threshold Algorithm) */
#define BCHP_LBOX_0_WHITE_COL_THRESHOLD_NTA      0x00125024 /* White Column Threshold (Control - Number & Threshold Algorithm) */
#define BCHP_LBOX_0_BLACK_LINE_THRESHOLD_LSUM    0x00125028 /* Black Line Threshold (Control - Luma Sum Algorithm) */
#define BCHP_LBOX_0_WHITE_LINE_THRESHOLD_LSUM    0x0012502c /* White Line Threshold (Control - Luma Sum Algorithm) */
#define BCHP_LBOX_0_NON_BLACK_LINE               0x00125030 /* First/Last Non-Black Line (Status - Number & Threshold and Luma Sum Algorithms) */
#define BCHP_LBOX_0_FIRST_WHITE_LINE             0x00125034 /* First White Line Statistics (Status - Number & Threshold and Luma Sum Algorithms) */
#define BCHP_LBOX_0_LAST_WHITE_LINE              0x00125038 /* Last White Line Statistics (Status - Number & Threshold and Luma Sum Algorithms) */
#define BCHP_LBOX_0_MINMAX_NON_BLACK_LINES       0x0012503c /* Min/Max Non-Black Line (Status - Number & Threshold and Luma Sum Algorithms) */
#define BCHP_LBOX_0_MIN_WHITE_LINE               0x00125040 /* Minimum First White Line Statistics (Status - Number & Threshold and Luma Sum Algorithms) */
#define BCHP_LBOX_0_MAX_WHITE_LINE               0x00125044 /* Maximum Last White Line Statistics (Status - Number & Threshold and Luma Sum Algorithms) */
#define BCHP_LBOX_0_NON_BLACK_COL                0x00125048 /* First/Last Non-Black Column (Status - Number & Threshold Algorithm) */
#define BCHP_LBOX_0_FIRST_WHITE_COL              0x0012504c /* First White Column Statistics (Status - Number & Threshold Algorithm) */
#define BCHP_LBOX_0_LAST_WHITE_COL               0x00125050 /* Last White Column Statistics (Status - Number & Threshold Algorithm) */
#define BCHP_LBOX_0_MINMAX_NON_BLACK_COL         0x00125054 /* Min/Max Non-Black Column (Status - Number & Threshold Algorithm) */
#define BCHP_LBOX_0_MIN_WHITE_COL                0x00125058 /* Minimum First White Column Statistics (Status - Number & Threshold Algorithm) */
#define BCHP_LBOX_0_MAX_WHITE_COL                0x0012505c /* Maximum Last White Column Statistics (Status - Number & Threshold Algorithm) */
#define BCHP_LBOX_0_MIN_LUMA_VALUE               0x00125060 /* The minimum luma value over all time (Control). */
#define BCHP_LBOX_0_TB_INTERRUPT_THRESHOLD       0x00125064 /* Top/Bottom Interrupt Threshold (Control). */
#define BCHP_LBOX_0_LR_INTERRUPT_THRESHOLD       0x00125068 /* Left/Right Interrupt Threshold (Control). */
#define BCHP_LBOX_0_CLEAR_STATUS                 0x0012506c /* Clear all of the Status registers. */
#define BCHP_LBOX_0_SCRATCH                      0x00125070 /* Reserved Register For Future Use. */

/***************************************************************************
 *REVISION_ID - Chip Revision ID.
 ***************************************************************************/
/* LBOX_0 :: REVISION_ID :: reserved0 [31:16] */
#define BCHP_LBOX_0_REVISION_ID_reserved0_MASK                     0xffff0000
#define BCHP_LBOX_0_REVISION_ID_reserved0_SHIFT                    16

/* LBOX_0 :: REVISION_ID :: REVISION_ID_MAJOR [15:08] */
#define BCHP_LBOX_0_REVISION_ID_REVISION_ID_MAJOR_MASK             0x0000ff00
#define BCHP_LBOX_0_REVISION_ID_REVISION_ID_MAJOR_SHIFT            8

/* LBOX_0 :: REVISION_ID :: REVISION_ID_MINOR [07:00] */
#define BCHP_LBOX_0_REVISION_ID_REVISION_ID_MINOR_MASK             0x000000ff
#define BCHP_LBOX_0_REVISION_ID_REVISION_ID_MINOR_SHIFT            0

/***************************************************************************
 *ENABLE_ACCEPT - OPERATIONS MODES (Control).
 ***************************************************************************/
/* LBOX_0 :: ENABLE_ACCEPT :: reserved0 [31:01] */
#define BCHP_LBOX_0_ENABLE_ACCEPT_reserved0_MASK                   0xfffffffe
#define BCHP_LBOX_0_ENABLE_ACCEPT_reserved0_SHIFT                  1

/* LBOX_0 :: ENABLE_ACCEPT :: ENABLE_ACCEPT [00:00] */
#define BCHP_LBOX_0_ENABLE_ACCEPT_ENABLE_ACCEPT_MASK               0x00000001
#define BCHP_LBOX_0_ENABLE_ACCEPT_ENABLE_ACCEPT_SHIFT              0
#define BCHP_LBOX_0_ENABLE_ACCEPT_ENABLE_ACCEPT_DIS                0
#define BCHP_LBOX_0_ENABLE_ACCEPT_ENABLE_ACCEPT_EN                 1

/***************************************************************************
 *CONFIGURATION - OPERATIONS MODES (Control).
 ***************************************************************************/
/* LBOX_0 :: CONFIGURATION :: reserved0 [31:05] */
#define BCHP_LBOX_0_CONFIGURATION_reserved0_MASK                   0xffffffe0
#define BCHP_LBOX_0_CONFIGURATION_reserved0_SHIFT                  5

/* LBOX_0 :: CONFIGURATION :: TB_HORIZONTAL_REGION_ENABLE [04:04] */
#define BCHP_LBOX_0_CONFIGURATION_TB_HORIZONTAL_REGION_ENABLE_MASK 0x00000010
#define BCHP_LBOX_0_CONFIGURATION_TB_HORIZONTAL_REGION_ENABLE_SHIFT 4
#define BCHP_LBOX_0_CONFIGURATION_TB_HORIZONTAL_REGION_ENABLE_DISABLE 0
#define BCHP_LBOX_0_CONFIGURATION_TB_HORIZONTAL_REGION_ENABLE_ENABLE 1

/* LBOX_0 :: CONFIGURATION :: TB_VERTICAL_REGION_ENABLE [03:03] */
#define BCHP_LBOX_0_CONFIGURATION_TB_VERTICAL_REGION_ENABLE_MASK   0x00000008
#define BCHP_LBOX_0_CONFIGURATION_TB_VERTICAL_REGION_ENABLE_SHIFT  3
#define BCHP_LBOX_0_CONFIGURATION_TB_VERTICAL_REGION_ENABLE_DISABLE 0
#define BCHP_LBOX_0_CONFIGURATION_TB_VERTICAL_REGION_ENABLE_ENABLE 1

/* LBOX_0 :: CONFIGURATION :: LR_HORIZONTAL_REGION_ENABLE [02:02] */
#define BCHP_LBOX_0_CONFIGURATION_LR_HORIZONTAL_REGION_ENABLE_MASK 0x00000004
#define BCHP_LBOX_0_CONFIGURATION_LR_HORIZONTAL_REGION_ENABLE_SHIFT 2
#define BCHP_LBOX_0_CONFIGURATION_LR_HORIZONTAL_REGION_ENABLE_DISABLE 0
#define BCHP_LBOX_0_CONFIGURATION_LR_HORIZONTAL_REGION_ENABLE_ENABLE 1

/* LBOX_0 :: CONFIGURATION :: LR_VERTICAL_REGION_ENABLE [01:01] */
#define BCHP_LBOX_0_CONFIGURATION_LR_VERTICAL_REGION_ENABLE_MASK   0x00000002
#define BCHP_LBOX_0_CONFIGURATION_LR_VERTICAL_REGION_ENABLE_SHIFT  1
#define BCHP_LBOX_0_CONFIGURATION_LR_VERTICAL_REGION_ENABLE_DISABLE 0
#define BCHP_LBOX_0_CONFIGURATION_LR_VERTICAL_REGION_ENABLE_ENABLE 1

/* LBOX_0 :: CONFIGURATION :: DETECT_MODE [00:00] */
#define BCHP_LBOX_0_CONFIGURATION_DETECT_MODE_MASK                 0x00000001
#define BCHP_LBOX_0_CONFIGURATION_DETECT_MODE_SHIFT                0
#define BCHP_LBOX_0_CONFIGURATION_DETECT_MODE_NUMBER               0
#define BCHP_LBOX_0_CONFIGURATION_DETECT_MODE_SUM                  1

/***************************************************************************
 *HORIZONTAL_WINDOW_REGION - Top/Bottom Horizontal Region (Control).
 ***************************************************************************/
/* LBOX_0 :: HORIZONTAL_WINDOW_REGION :: reserved0 [31:27] */
#define BCHP_LBOX_0_HORIZONTAL_WINDOW_REGION_reserved0_MASK        0xf8000000
#define BCHP_LBOX_0_HORIZONTAL_WINDOW_REGION_reserved0_SHIFT       27

/* LBOX_0 :: HORIZONTAL_WINDOW_REGION :: HORIZONTAL_START_POINT [26:16] */
#define BCHP_LBOX_0_HORIZONTAL_WINDOW_REGION_HORIZONTAL_START_POINT_MASK 0x07ff0000
#define BCHP_LBOX_0_HORIZONTAL_WINDOW_REGION_HORIZONTAL_START_POINT_SHIFT 16

/* LBOX_0 :: HORIZONTAL_WINDOW_REGION :: reserved1 [15:11] */
#define BCHP_LBOX_0_HORIZONTAL_WINDOW_REGION_reserved1_MASK        0x0000f800
#define BCHP_LBOX_0_HORIZONTAL_WINDOW_REGION_reserved1_SHIFT       11

/* LBOX_0 :: HORIZONTAL_WINDOW_REGION :: HORIZONTAL_END_POINT [10:00] */
#define BCHP_LBOX_0_HORIZONTAL_WINDOW_REGION_HORIZONTAL_END_POINT_MASK 0x000007ff
#define BCHP_LBOX_0_HORIZONTAL_WINDOW_REGION_HORIZONTAL_END_POINT_SHIFT 0

/***************************************************************************
 *VERTICAL_WINDOW_REGION - Left/Right Vertical Region (Control).
 ***************************************************************************/
/* LBOX_0 :: VERTICAL_WINDOW_REGION :: reserved0 [31:27] */
#define BCHP_LBOX_0_VERTICAL_WINDOW_REGION_reserved0_MASK          0xf8000000
#define BCHP_LBOX_0_VERTICAL_WINDOW_REGION_reserved0_SHIFT         27

/* LBOX_0 :: VERTICAL_WINDOW_REGION :: VERTICAL_START_POINT [26:16] */
#define BCHP_LBOX_0_VERTICAL_WINDOW_REGION_VERTICAL_START_POINT_MASK 0x07ff0000
#define BCHP_LBOX_0_VERTICAL_WINDOW_REGION_VERTICAL_START_POINT_SHIFT 16

/* LBOX_0 :: VERTICAL_WINDOW_REGION :: reserved1 [15:11] */
#define BCHP_LBOX_0_VERTICAL_WINDOW_REGION_reserved1_MASK          0x0000f800
#define BCHP_LBOX_0_VERTICAL_WINDOW_REGION_reserved1_SHIFT         11

/* LBOX_0 :: VERTICAL_WINDOW_REGION :: VERTICAL_END_POINT [10:00] */
#define BCHP_LBOX_0_VERTICAL_WINDOW_REGION_VERTICAL_END_POINT_MASK 0x000007ff
#define BCHP_LBOX_0_VERTICAL_WINDOW_REGION_VERTICAL_END_POINT_SHIFT 0

/***************************************************************************
 *PIXEL_THRESHOLD - Black Pixel Threshold (Control).
 ***************************************************************************/
/* LBOX_0 :: PIXEL_THRESHOLD :: reserved0 [31:24] */
#define BCHP_LBOX_0_PIXEL_THRESHOLD_reserved0_MASK                 0xff000000
#define BCHP_LBOX_0_PIXEL_THRESHOLD_reserved0_SHIFT                24

/* LBOX_0 :: PIXEL_THRESHOLD :: BLACK_LEVEL_LUMA_SUM [23:16] */
#define BCHP_LBOX_0_PIXEL_THRESHOLD_BLACK_LEVEL_LUMA_SUM_MASK      0x00ff0000
#define BCHP_LBOX_0_PIXEL_THRESHOLD_BLACK_LEVEL_LUMA_SUM_SHIFT     16

/* LBOX_0 :: PIXEL_THRESHOLD :: TB_BLACK_LEVEL_NTA [15:08] */
#define BCHP_LBOX_0_PIXEL_THRESHOLD_TB_BLACK_LEVEL_NTA_MASK        0x0000ff00
#define BCHP_LBOX_0_PIXEL_THRESHOLD_TB_BLACK_LEVEL_NTA_SHIFT       8

/* LBOX_0 :: PIXEL_THRESHOLD :: LR_BLACK_LEVEL_NTA [07:00] */
#define BCHP_LBOX_0_PIXEL_THRESHOLD_LR_BLACK_LEVEL_NTA_MASK        0x000000ff
#define BCHP_LBOX_0_PIXEL_THRESHOLD_LR_BLACK_LEVEL_NTA_SHIFT       0

/***************************************************************************
 *BLACK_LINE_THRESHOLD_NTA - Black Line Threshold (Control - Number & Threshold Algorithm)
 ***************************************************************************/
/* LBOX_0 :: BLACK_LINE_THRESHOLD_NTA :: reserved0 [31:11] */
#define BCHP_LBOX_0_BLACK_LINE_THRESHOLD_NTA_reserved0_MASK        0xfffff800
#define BCHP_LBOX_0_BLACK_LINE_THRESHOLD_NTA_reserved0_SHIFT       11

/* LBOX_0 :: BLACK_LINE_THRESHOLD_NTA :: BLACK_LINE_THRESHOLD_SIZE [10:00] */
#define BCHP_LBOX_0_BLACK_LINE_THRESHOLD_NTA_BLACK_LINE_THRESHOLD_SIZE_MASK 0x000007ff
#define BCHP_LBOX_0_BLACK_LINE_THRESHOLD_NTA_BLACK_LINE_THRESHOLD_SIZE_SHIFT 0

/***************************************************************************
 *BLACK_COL_THRESHOLD_NTA - Black Column Threshold (Control - Number & Threshold Algorithm)
 ***************************************************************************/
/* LBOX_0 :: BLACK_COL_THRESHOLD_NTA :: reserved0 [31:11] */
#define BCHP_LBOX_0_BLACK_COL_THRESHOLD_NTA_reserved0_MASK         0xfffff800
#define BCHP_LBOX_0_BLACK_COL_THRESHOLD_NTA_reserved0_SHIFT        11

/* LBOX_0 :: BLACK_COL_THRESHOLD_NTA :: BLACK_COL_THRESHOLD_SIZE [10:00] */
#define BCHP_LBOX_0_BLACK_COL_THRESHOLD_NTA_BLACK_COL_THRESHOLD_SIZE_MASK 0x000007ff
#define BCHP_LBOX_0_BLACK_COL_THRESHOLD_NTA_BLACK_COL_THRESHOLD_SIZE_SHIFT 0

/***************************************************************************
 *WHITE_LINE_THRESHOLD_NTA - White Line Threshold (Control - Number & Threshold Algorithm)
 ***************************************************************************/
/* LBOX_0 :: WHITE_LINE_THRESHOLD_NTA :: reserved0 [31:11] */
#define BCHP_LBOX_0_WHITE_LINE_THRESHOLD_NTA_reserved0_MASK        0xfffff800
#define BCHP_LBOX_0_WHITE_LINE_THRESHOLD_NTA_reserved0_SHIFT       11

/* LBOX_0 :: WHITE_LINE_THRESHOLD_NTA :: WHITE_LINE_THRESHOLD_SIZE [10:00] */
#define BCHP_LBOX_0_WHITE_LINE_THRESHOLD_NTA_WHITE_LINE_THRESHOLD_SIZE_MASK 0x000007ff
#define BCHP_LBOX_0_WHITE_LINE_THRESHOLD_NTA_WHITE_LINE_THRESHOLD_SIZE_SHIFT 0

/***************************************************************************
 *WHITE_COL_THRESHOLD_NTA - White Column Threshold (Control - Number & Threshold Algorithm)
 ***************************************************************************/
/* LBOX_0 :: WHITE_COL_THRESHOLD_NTA :: reserved0 [31:11] */
#define BCHP_LBOX_0_WHITE_COL_THRESHOLD_NTA_reserved0_MASK         0xfffff800
#define BCHP_LBOX_0_WHITE_COL_THRESHOLD_NTA_reserved0_SHIFT        11

/* LBOX_0 :: WHITE_COL_THRESHOLD_NTA :: WHITE_COL_THRESHOLD_SIZE [10:00] */
#define BCHP_LBOX_0_WHITE_COL_THRESHOLD_NTA_WHITE_COL_THRESHOLD_SIZE_MASK 0x000007ff
#define BCHP_LBOX_0_WHITE_COL_THRESHOLD_NTA_WHITE_COL_THRESHOLD_SIZE_SHIFT 0

/***************************************************************************
 *BLACK_LINE_THRESHOLD_LSUM - Black Line Threshold (Control - Luma Sum Algorithm)
 ***************************************************************************/
/* LBOX_0 :: BLACK_LINE_THRESHOLD_LSUM :: reserved0 [31:19] */
#define BCHP_LBOX_0_BLACK_LINE_THRESHOLD_LSUM_reserved0_MASK       0xfff80000
#define BCHP_LBOX_0_BLACK_LINE_THRESHOLD_LSUM_reserved0_SHIFT      19

/* LBOX_0 :: BLACK_LINE_THRESHOLD_LSUM :: BLACK_LINE_THRESHOLD_SIZE [18:00] */
#define BCHP_LBOX_0_BLACK_LINE_THRESHOLD_LSUM_BLACK_LINE_THRESHOLD_SIZE_MASK 0x0007ffff
#define BCHP_LBOX_0_BLACK_LINE_THRESHOLD_LSUM_BLACK_LINE_THRESHOLD_SIZE_SHIFT 0

/***************************************************************************
 *WHITE_LINE_THRESHOLD_LSUM - White Line Threshold (Control - Luma Sum Algorithm)
 ***************************************************************************/
/* LBOX_0 :: WHITE_LINE_THRESHOLD_LSUM :: reserved0 [31:19] */
#define BCHP_LBOX_0_WHITE_LINE_THRESHOLD_LSUM_reserved0_MASK       0xfff80000
#define BCHP_LBOX_0_WHITE_LINE_THRESHOLD_LSUM_reserved0_SHIFT      19

/* LBOX_0 :: WHITE_LINE_THRESHOLD_LSUM :: WHITE_LINE_THRESHOLD_SIZE [18:00] */
#define BCHP_LBOX_0_WHITE_LINE_THRESHOLD_LSUM_WHITE_LINE_THRESHOLD_SIZE_MASK 0x0007ffff
#define BCHP_LBOX_0_WHITE_LINE_THRESHOLD_LSUM_WHITE_LINE_THRESHOLD_SIZE_SHIFT 0

/***************************************************************************
 *NON_BLACK_LINE - First/Last Non-Black Line (Status - Number & Threshold and Luma Sum Algorithms)
 ***************************************************************************/
/* LBOX_0 :: NON_BLACK_LINE :: reserved0 [31:22] */
#define BCHP_LBOX_0_NON_BLACK_LINE_reserved0_MASK                  0xffc00000
#define BCHP_LBOX_0_NON_BLACK_LINE_reserved0_SHIFT                 22

/* LBOX_0 :: NON_BLACK_LINE :: FIRST_NON_BLACK_LINE_NUMBER [21:11] */
#define BCHP_LBOX_0_NON_BLACK_LINE_FIRST_NON_BLACK_LINE_NUMBER_MASK 0x003ff800
#define BCHP_LBOX_0_NON_BLACK_LINE_FIRST_NON_BLACK_LINE_NUMBER_SHIFT 11

/* LBOX_0 :: NON_BLACK_LINE :: LAST_NON_BLACK_LINE_NUMBER [10:00] */
#define BCHP_LBOX_0_NON_BLACK_LINE_LAST_NON_BLACK_LINE_NUMBER_MASK 0x000007ff
#define BCHP_LBOX_0_NON_BLACK_LINE_LAST_NON_BLACK_LINE_NUMBER_SHIFT 0

/***************************************************************************
 *FIRST_WHITE_LINE - First White Line Statistics (Status - Number & Threshold and Luma Sum Algorithms)
 ***************************************************************************/
/* LBOX_0 :: FIRST_WHITE_LINE :: reserved0 [31:30] */
#define BCHP_LBOX_0_FIRST_WHITE_LINE_reserved0_MASK                0xc0000000
#define BCHP_LBOX_0_FIRST_WHITE_LINE_reserved0_SHIFT               30

/* LBOX_0 :: FIRST_WHITE_LINE :: FIRST_WHITE_LINE_STRENGTH [29:11] */
#define BCHP_LBOX_0_FIRST_WHITE_LINE_FIRST_WHITE_LINE_STRENGTH_MASK 0x3ffff800
#define BCHP_LBOX_0_FIRST_WHITE_LINE_FIRST_WHITE_LINE_STRENGTH_SHIFT 11

/* LBOX_0 :: FIRST_WHITE_LINE :: FIRST_WHITE_LINE_NUMBER [10:00] */
#define BCHP_LBOX_0_FIRST_WHITE_LINE_FIRST_WHITE_LINE_NUMBER_MASK  0x000007ff
#define BCHP_LBOX_0_FIRST_WHITE_LINE_FIRST_WHITE_LINE_NUMBER_SHIFT 0

/***************************************************************************
 *LAST_WHITE_LINE - Last White Line Statistics (Status - Number & Threshold and Luma Sum Algorithms)
 ***************************************************************************/
/* LBOX_0 :: LAST_WHITE_LINE :: reserved0 [31:30] */
#define BCHP_LBOX_0_LAST_WHITE_LINE_reserved0_MASK                 0xc0000000
#define BCHP_LBOX_0_LAST_WHITE_LINE_reserved0_SHIFT                30

/* LBOX_0 :: LAST_WHITE_LINE :: LAST_WHITE_LINE_STRENGTH [29:11] */
#define BCHP_LBOX_0_LAST_WHITE_LINE_LAST_WHITE_LINE_STRENGTH_MASK  0x3ffff800
#define BCHP_LBOX_0_LAST_WHITE_LINE_LAST_WHITE_LINE_STRENGTH_SHIFT 11

/* LBOX_0 :: LAST_WHITE_LINE :: LAST_WHITE_LINE_NUMBER [10:00] */
#define BCHP_LBOX_0_LAST_WHITE_LINE_LAST_WHITE_LINE_NUMBER_MASK    0x000007ff
#define BCHP_LBOX_0_LAST_WHITE_LINE_LAST_WHITE_LINE_NUMBER_SHIFT   0

/***************************************************************************
 *MINMAX_NON_BLACK_LINES - Min/Max Non-Black Line (Status - Number & Threshold and Luma Sum Algorithms)
 ***************************************************************************/
/* LBOX_0 :: MINMAX_NON_BLACK_LINES :: reserved0 [31:22] */
#define BCHP_LBOX_0_MINMAX_NON_BLACK_LINES_reserved0_MASK          0xffc00000
#define BCHP_LBOX_0_MINMAX_NON_BLACK_LINES_reserved0_SHIFT         22

/* LBOX_0 :: MINMAX_NON_BLACK_LINES :: SMALL_NON_BLACK_LINE_NUMBER [21:11] */
#define BCHP_LBOX_0_MINMAX_NON_BLACK_LINES_SMALL_NON_BLACK_LINE_NUMBER_MASK 0x003ff800
#define BCHP_LBOX_0_MINMAX_NON_BLACK_LINES_SMALL_NON_BLACK_LINE_NUMBER_SHIFT 11

/* LBOX_0 :: MINMAX_NON_BLACK_LINES :: LARGE_NON_BLACK_LINE_NUMBER [10:00] */
#define BCHP_LBOX_0_MINMAX_NON_BLACK_LINES_LARGE_NON_BLACK_LINE_NUMBER_MASK 0x000007ff
#define BCHP_LBOX_0_MINMAX_NON_BLACK_LINES_LARGE_NON_BLACK_LINE_NUMBER_SHIFT 0

/***************************************************************************
 *MIN_WHITE_LINE - Minimum First White Line Statistics (Status - Number & Threshold and Luma Sum Algorithms)
 ***************************************************************************/
/* LBOX_0 :: MIN_WHITE_LINE :: reserved0 [31:30] */
#define BCHP_LBOX_0_MIN_WHITE_LINE_reserved0_MASK                  0xc0000000
#define BCHP_LBOX_0_MIN_WHITE_LINE_reserved0_SHIFT                 30

/* LBOX_0 :: MIN_WHITE_LINE :: SMALL_WHITE_LINE_STRENGTH [29:11] */
#define BCHP_LBOX_0_MIN_WHITE_LINE_SMALL_WHITE_LINE_STRENGTH_MASK  0x3ffff800
#define BCHP_LBOX_0_MIN_WHITE_LINE_SMALL_WHITE_LINE_STRENGTH_SHIFT 11

/* LBOX_0 :: MIN_WHITE_LINE :: SMALL_WHITE_LINE_NUMBER [10:00] */
#define BCHP_LBOX_0_MIN_WHITE_LINE_SMALL_WHITE_LINE_NUMBER_MASK    0x000007ff
#define BCHP_LBOX_0_MIN_WHITE_LINE_SMALL_WHITE_LINE_NUMBER_SHIFT   0

/***************************************************************************
 *MAX_WHITE_LINE - Maximum Last White Line Statistics (Status - Number & Threshold and Luma Sum Algorithms)
 ***************************************************************************/
/* LBOX_0 :: MAX_WHITE_LINE :: reserved0 [31:30] */
#define BCHP_LBOX_0_MAX_WHITE_LINE_reserved0_MASK                  0xc0000000
#define BCHP_LBOX_0_MAX_WHITE_LINE_reserved0_SHIFT                 30

/* LBOX_0 :: MAX_WHITE_LINE :: LARGE_WHITE_LINE_STRENGTH [29:11] */
#define BCHP_LBOX_0_MAX_WHITE_LINE_LARGE_WHITE_LINE_STRENGTH_MASK  0x3ffff800
#define BCHP_LBOX_0_MAX_WHITE_LINE_LARGE_WHITE_LINE_STRENGTH_SHIFT 11

/* LBOX_0 :: MAX_WHITE_LINE :: LARGE_WHITE_LINE_NUMBER [10:00] */
#define BCHP_LBOX_0_MAX_WHITE_LINE_LARGE_WHITE_LINE_NUMBER_MASK    0x000007ff
#define BCHP_LBOX_0_MAX_WHITE_LINE_LARGE_WHITE_LINE_NUMBER_SHIFT   0

/***************************************************************************
 *NON_BLACK_COL - First/Last Non-Black Column (Status - Number & Threshold Algorithm)
 ***************************************************************************/
/* LBOX_0 :: NON_BLACK_COL :: reserved0 [31:22] */
#define BCHP_LBOX_0_NON_BLACK_COL_reserved0_MASK                   0xffc00000
#define BCHP_LBOX_0_NON_BLACK_COL_reserved0_SHIFT                  22

/* LBOX_0 :: NON_BLACK_COL :: FIRST_NON_BLACK_COL_NUMBER [21:11] */
#define BCHP_LBOX_0_NON_BLACK_COL_FIRST_NON_BLACK_COL_NUMBER_MASK  0x003ff800
#define BCHP_LBOX_0_NON_BLACK_COL_FIRST_NON_BLACK_COL_NUMBER_SHIFT 11

/* LBOX_0 :: NON_BLACK_COL :: LAST_NON_BLACK_COL_NUMBER [10:00] */
#define BCHP_LBOX_0_NON_BLACK_COL_LAST_NON_BLACK_COL_NUMBER_MASK   0x000007ff
#define BCHP_LBOX_0_NON_BLACK_COL_LAST_NON_BLACK_COL_NUMBER_SHIFT  0

/***************************************************************************
 *FIRST_WHITE_COL - First White Column Statistics (Status - Number & Threshold Algorithm)
 ***************************************************************************/
/* LBOX_0 :: FIRST_WHITE_COL :: reserved0 [31:22] */
#define BCHP_LBOX_0_FIRST_WHITE_COL_reserved0_MASK                 0xffc00000
#define BCHP_LBOX_0_FIRST_WHITE_COL_reserved0_SHIFT                22

/* LBOX_0 :: FIRST_WHITE_COL :: FIRST_WHITE_COL_STRENGTH [21:11] */
#define BCHP_LBOX_0_FIRST_WHITE_COL_FIRST_WHITE_COL_STRENGTH_MASK  0x003ff800
#define BCHP_LBOX_0_FIRST_WHITE_COL_FIRST_WHITE_COL_STRENGTH_SHIFT 11

/* LBOX_0 :: FIRST_WHITE_COL :: FIRST_WHITE_COL_NUMBER [10:00] */
#define BCHP_LBOX_0_FIRST_WHITE_COL_FIRST_WHITE_COL_NUMBER_MASK    0x000007ff
#define BCHP_LBOX_0_FIRST_WHITE_COL_FIRST_WHITE_COL_NUMBER_SHIFT   0

/***************************************************************************
 *LAST_WHITE_COL - Last White Column Statistics (Status - Number & Threshold Algorithm)
 ***************************************************************************/
/* LBOX_0 :: LAST_WHITE_COL :: reserved0 [31:22] */
#define BCHP_LBOX_0_LAST_WHITE_COL_reserved0_MASK                  0xffc00000
#define BCHP_LBOX_0_LAST_WHITE_COL_reserved0_SHIFT                 22

/* LBOX_0 :: LAST_WHITE_COL :: LAST_WHITE_COL_STRENGTH [21:11] */
#define BCHP_LBOX_0_LAST_WHITE_COL_LAST_WHITE_COL_STRENGTH_MASK    0x003ff800
#define BCHP_LBOX_0_LAST_WHITE_COL_LAST_WHITE_COL_STRENGTH_SHIFT   11

/* LBOX_0 :: LAST_WHITE_COL :: LAST_WHITE_COL_NUMBER [10:00] */
#define BCHP_LBOX_0_LAST_WHITE_COL_LAST_WHITE_COL_NUMBER_MASK      0x000007ff
#define BCHP_LBOX_0_LAST_WHITE_COL_LAST_WHITE_COL_NUMBER_SHIFT     0

/***************************************************************************
 *MINMAX_NON_BLACK_COL - Min/Max Non-Black Column (Status - Number & Threshold Algorithm)
 ***************************************************************************/
/* LBOX_0 :: MINMAX_NON_BLACK_COL :: reserved0 [31:22] */
#define BCHP_LBOX_0_MINMAX_NON_BLACK_COL_reserved0_MASK            0xffc00000
#define BCHP_LBOX_0_MINMAX_NON_BLACK_COL_reserved0_SHIFT           22

/* LBOX_0 :: MINMAX_NON_BLACK_COL :: SMALL_NON_BLACK_COL_NUMBER [21:11] */
#define BCHP_LBOX_0_MINMAX_NON_BLACK_COL_SMALL_NON_BLACK_COL_NUMBER_MASK 0x003ff800
#define BCHP_LBOX_0_MINMAX_NON_BLACK_COL_SMALL_NON_BLACK_COL_NUMBER_SHIFT 11

/* LBOX_0 :: MINMAX_NON_BLACK_COL :: LARGE_NON_BLACK_COL_NUMBER [10:00] */
#define BCHP_LBOX_0_MINMAX_NON_BLACK_COL_LARGE_NON_BLACK_COL_NUMBER_MASK 0x000007ff
#define BCHP_LBOX_0_MINMAX_NON_BLACK_COL_LARGE_NON_BLACK_COL_NUMBER_SHIFT 0

/***************************************************************************
 *MIN_WHITE_COL - Minimum First White Column Statistics (Status - Number & Threshold Algorithm)
 ***************************************************************************/
/* LBOX_0 :: MIN_WHITE_COL :: reserved0 [31:22] */
#define BCHP_LBOX_0_MIN_WHITE_COL_reserved0_MASK                   0xffc00000
#define BCHP_LBOX_0_MIN_WHITE_COL_reserved0_SHIFT                  22

/* LBOX_0 :: MIN_WHITE_COL :: SMALL_WHITE_COL_STRENGTH [21:11] */
#define BCHP_LBOX_0_MIN_WHITE_COL_SMALL_WHITE_COL_STRENGTH_MASK    0x003ff800
#define BCHP_LBOX_0_MIN_WHITE_COL_SMALL_WHITE_COL_STRENGTH_SHIFT   11

/* LBOX_0 :: MIN_WHITE_COL :: SMALL_WHITE_COL_NUMBER [10:00] */
#define BCHP_LBOX_0_MIN_WHITE_COL_SMALL_WHITE_COL_NUMBER_MASK      0x000007ff
#define BCHP_LBOX_0_MIN_WHITE_COL_SMALL_WHITE_COL_NUMBER_SHIFT     0

/***************************************************************************
 *MAX_WHITE_COL - Maximum Last White Column Statistics (Status - Number & Threshold Algorithm)
 ***************************************************************************/
/* LBOX_0 :: MAX_WHITE_COL :: reserved0 [31:22] */
#define BCHP_LBOX_0_MAX_WHITE_COL_reserved0_MASK                   0xffc00000
#define BCHP_LBOX_0_MAX_WHITE_COL_reserved0_SHIFT                  22

/* LBOX_0 :: MAX_WHITE_COL :: LARGE_WHITE_COL_STRENGTH [21:11] */
#define BCHP_LBOX_0_MAX_WHITE_COL_LARGE_WHITE_COL_STRENGTH_MASK    0x003ff800
#define BCHP_LBOX_0_MAX_WHITE_COL_LARGE_WHITE_COL_STRENGTH_SHIFT   11

/* LBOX_0 :: MAX_WHITE_COL :: LARGE_WHITE_COL_NUMBER [10:00] */
#define BCHP_LBOX_0_MAX_WHITE_COL_LARGE_WHITE_COL_NUMBER_MASK      0x000007ff
#define BCHP_LBOX_0_MAX_WHITE_COL_LARGE_WHITE_COL_NUMBER_SHIFT     0

/***************************************************************************
 *MIN_LUMA_VALUE - The minimum luma value over all time (Control).
 ***************************************************************************/
/* LBOX_0 :: MIN_LUMA_VALUE :: reserved0 [31:16] */
#define BCHP_LBOX_0_MIN_LUMA_VALUE_reserved0_MASK                  0xffff0000
#define BCHP_LBOX_0_MIN_LUMA_VALUE_reserved0_SHIFT                 16

/* LBOX_0 :: MIN_LUMA_VALUE :: TB_LUMA_VALUE [15:08] */
#define BCHP_LBOX_0_MIN_LUMA_VALUE_TB_LUMA_VALUE_MASK              0x0000ff00
#define BCHP_LBOX_0_MIN_LUMA_VALUE_TB_LUMA_VALUE_SHIFT             8

/* LBOX_0 :: MIN_LUMA_VALUE :: LR_LUMA_VALUE [07:00] */
#define BCHP_LBOX_0_MIN_LUMA_VALUE_LR_LUMA_VALUE_MASK              0x000000ff
#define BCHP_LBOX_0_MIN_LUMA_VALUE_LR_LUMA_VALUE_SHIFT             0

/***************************************************************************
 *TB_INTERRUPT_THRESHOLD - Top/Bottom Interrupt Threshold (Control).
 ***************************************************************************/
/* LBOX_0 :: TB_INTERRUPT_THRESHOLD :: reserved0 [31:22] */
#define BCHP_LBOX_0_TB_INTERRUPT_THRESHOLD_reserved0_MASK          0xffc00000
#define BCHP_LBOX_0_TB_INTERRUPT_THRESHOLD_reserved0_SHIFT         22

/* LBOX_0 :: TB_INTERRUPT_THRESHOLD :: TOP_THRESHOLD [21:11] */
#define BCHP_LBOX_0_TB_INTERRUPT_THRESHOLD_TOP_THRESHOLD_MASK      0x003ff800
#define BCHP_LBOX_0_TB_INTERRUPT_THRESHOLD_TOP_THRESHOLD_SHIFT     11

/* LBOX_0 :: TB_INTERRUPT_THRESHOLD :: BOTTOM_THRESHOLD [10:00] */
#define BCHP_LBOX_0_TB_INTERRUPT_THRESHOLD_BOTTOM_THRESHOLD_MASK   0x000007ff
#define BCHP_LBOX_0_TB_INTERRUPT_THRESHOLD_BOTTOM_THRESHOLD_SHIFT  0

/***************************************************************************
 *LR_INTERRUPT_THRESHOLD - Left/Right Interrupt Threshold (Control).
 ***************************************************************************/
/* LBOX_0 :: LR_INTERRUPT_THRESHOLD :: reserved0 [31:22] */
#define BCHP_LBOX_0_LR_INTERRUPT_THRESHOLD_reserved0_MASK          0xffc00000
#define BCHP_LBOX_0_LR_INTERRUPT_THRESHOLD_reserved0_SHIFT         22

/* LBOX_0 :: LR_INTERRUPT_THRESHOLD :: LEFT_THRESHOLD [21:11] */
#define BCHP_LBOX_0_LR_INTERRUPT_THRESHOLD_LEFT_THRESHOLD_MASK     0x003ff800
#define BCHP_LBOX_0_LR_INTERRUPT_THRESHOLD_LEFT_THRESHOLD_SHIFT    11

/* LBOX_0 :: LR_INTERRUPT_THRESHOLD :: RIGHT_THRESHOLD [10:00] */
#define BCHP_LBOX_0_LR_INTERRUPT_THRESHOLD_RIGHT_THRESHOLD_MASK    0x000007ff
#define BCHP_LBOX_0_LR_INTERRUPT_THRESHOLD_RIGHT_THRESHOLD_SHIFT   0

/***************************************************************************
 *CLEAR_STATUS - Clear all of the Status registers.
 ***************************************************************************/
/* LBOX_0 :: CLEAR_STATUS :: reserved0 [31:02] */
#define BCHP_LBOX_0_CLEAR_STATUS_reserved0_MASK                    0xfffffffc
#define BCHP_LBOX_0_CLEAR_STATUS_reserved0_SHIFT                   2

/* LBOX_0 :: CLEAR_STATUS :: CLEAR_EDGES [01:01] */
#define BCHP_LBOX_0_CLEAR_STATUS_CLEAR_EDGES_MASK                  0x00000002
#define BCHP_LBOX_0_CLEAR_STATUS_CLEAR_EDGES_SHIFT                 1

/* LBOX_0 :: CLEAR_STATUS :: CLEAR_LUMA [00:00] */
#define BCHP_LBOX_0_CLEAR_STATUS_CLEAR_LUMA_MASK                   0x00000001
#define BCHP_LBOX_0_CLEAR_STATUS_CLEAR_LUMA_SHIFT                  0

/***************************************************************************
 *SCRATCH - Reserved Register For Future Use.
 ***************************************************************************/
/* LBOX_0 :: SCRATCH :: RESERVED [31:00] */
#define BCHP_LBOX_0_SCRATCH_RESERVED_MASK                          0xffffffff
#define BCHP_LBOX_0_SCRATCH_RESERVED_SHIFT                         0

#endif /* #ifndef BCHP_LBOX_0_H__ */

/* End of File */
