/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Mar 20 13:02:22 2009
 *                 MD5 Checksum         4f0509cfa0b8fc4589050694b4a3e234
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7340/rdb/a0/bchp_sm.h $
 * 
 * Hydra_Software_Devel/1   3/22/09 9:09p yuxiaz
 * PR53430: Initial version of header files.
 *
 ***************************************************************************/

#ifndef BCHP_SM_H__
#define BCHP_SM_H__

/***************************************************************************
 *SM - Soft Modem Registers
 ***************************************************************************/
#define BCHP_SM_DEVICE_CTL                       0x00403000 /* Device Control Register */
#define BCHP_SM_IRQ_CSR                          0x00403004 /* Interrupt Service Register */
#define BCHP_SM_EXT_DAA_CMD                      0x00403008 /* External DAA Command Register */
#define BCHP_SM_EXT_DAA_STAT                     0x0040300c /* External DAA Status Register */
#define BCHP_SM_GP_TIMER_CFG                     0x00403010 /* General Purpose Timer Configuration Register */
#define BCHP_SM_GP_TIMER_STAT                    0x00403014 /* General Purpose Timer Down Counter Status Register */
#define BCHP_SM_OH_TIMER_DIAG                    0x00403018 /* Off Hook Timer Diagnostic Register */
#define BCHP_SM_DIAG_CFG                         0x0040301c /* Diagnostic Configuration Register */
#define BCHP_SM_REV                              0x00403020 /* Soft Modem Interface Revision Register */
#define BCHP_SM_DAA_FIELD_SEL                    0x00403024 /* DAA Polling Field Selection Register */

/***************************************************************************
 *DEVICE_CTL - Device Control Register
 ***************************************************************************/
/* SM :: DEVICE_CTL :: MAX_FS_TIME [31:16] */
#define BCHP_SM_DEVICE_CTL_MAX_FS_TIME_MASK                        0xffff0000
#define BCHP_SM_DEVICE_CTL_MAX_FS_TIME_SHIFT                       16

/* SM :: DEVICE_CTL :: L_END [15:15] */
#define BCHP_SM_DEVICE_CTL_L_END_MASK                              0x00008000
#define BCHP_SM_DEVICE_CTL_L_END_SHIFT                             15

/* SM :: DEVICE_CTL :: reserved0 [14:14] */
#define BCHP_SM_DEVICE_CTL_reserved0_MASK                          0x00004000
#define BCHP_SM_DEVICE_CTL_reserved0_SHIFT                         14

/* union - case Si3021_mode [13:13] */
/* SM :: DEVICE_CTL :: Si3021_mode :: POLL_LINK [13:13] */
#define BCHP_SM_DEVICE_CTL_Si3021_mode_POLL_LINK_MASK              0x00002000
#define BCHP_SM_DEVICE_CTL_Si3021_mode_POLL_LINK_SHIFT             13

/* union - case GP_DAA_mode [13:13] */
/* SM :: DEVICE_CTL :: GP_DAA_mode :: reserved0 [13:13] */
#define BCHP_SM_DEVICE_CTL_GP_DAA_mode_reserved0_MASK              0x00002000
#define BCHP_SM_DEVICE_CTL_GP_DAA_mode_reserved0_SHIFT             13

/* SM :: DEVICE_CTL :: CNT_PCK [12:12] */
#define BCHP_SM_DEVICE_CTL_CNT_PCK_MASK                            0x00001000
#define BCHP_SM_DEVICE_CTL_CNT_PCK_SHIFT                           12

/* SM :: DEVICE_CTL :: LOOP [11:11] */
#define BCHP_SM_DEVICE_CTL_LOOP_MASK                               0x00000800
#define BCHP_SM_DEVICE_CTL_LOOP_SHIFT                              11

/* SM :: DEVICE_CTL :: TIME_SF [10:09] */
#define BCHP_SM_DEVICE_CTL_TIME_SF_MASK                            0x00000600
#define BCHP_SM_DEVICE_CTL_TIME_SF_SHIFT                           9

/* SM :: DEVICE_CTL :: reserved1 [08:03] */
#define BCHP_SM_DEVICE_CTL_reserved1_MASK                          0x000001f8
#define BCHP_SM_DEVICE_CTL_reserved1_SHIFT                         3

/* SM :: DEVICE_CTL :: TX_FLUSH [02:02] */
#define BCHP_SM_DEVICE_CTL_TX_FLUSH_MASK                           0x00000004
#define BCHP_SM_DEVICE_CTL_TX_FLUSH_SHIFT                          2

/* SM :: DEVICE_CTL :: RX_FLUSH [01:01] */
#define BCHP_SM_DEVICE_CTL_RX_FLUSH_MASK                           0x00000002
#define BCHP_SM_DEVICE_CTL_RX_FLUSH_SHIFT                          1

/* SM :: DEVICE_CTL :: S_RST [00:00] */
#define BCHP_SM_DEVICE_CTL_S_RST_MASK                              0x00000001
#define BCHP_SM_DEVICE_CTL_S_RST_SHIFT                             0

/***************************************************************************
 *IRQ_CSR - Interrupt Service Register
 ***************************************************************************/
/* SM :: IRQ_CSR :: TIME [31:31] */
#define BCHP_SM_IRQ_CSR_TIME_MASK                                  0x80000000
#define BCHP_SM_IRQ_CSR_TIME_SHIFT                                 31

/* SM :: IRQ_CSR :: IO_DONE [30:30] */
#define BCHP_SM_IRQ_CSR_IO_DONE_MASK                               0x40000000
#define BCHP_SM_IRQ_CSR_IO_DONE_SHIFT                              30

/* SM :: IRQ_CSR :: OH_TIMEOUT [29:29] */
#define BCHP_SM_IRQ_CSR_OH_TIMEOUT_MASK                            0x20000000
#define BCHP_SM_IRQ_CSR_OH_TIMEOUT_SHIFT                           29

/* SM :: IRQ_CSR :: RNG_HK_VALID [28:28] */
#define BCHP_SM_IRQ_CSR_RNG_HK_VALID_MASK                          0x10000000
#define BCHP_SM_IRQ_CSR_RNG_HK_VALID_SHIFT                         28

/* SM :: IRQ_CSR :: OFF_Hook [27:27] */
#define BCHP_SM_IRQ_CSR_OFF_Hook_MASK                              0x08000000
#define BCHP_SM_IRQ_CSR_OFF_Hook_SHIFT                             27

/* SM :: IRQ_CSR :: Ring_Detect [26:26] */
#define BCHP_SM_IRQ_CSR_Ring_Detect_MASK                           0x04000000
#define BCHP_SM_IRQ_CSR_Ring_Detect_SHIFT                          26

/* SM :: IRQ_CSR :: LINK_ERR [25:25] */
#define BCHP_SM_IRQ_CSR_LINK_ERR_MASK                              0x02000000
#define BCHP_SM_IRQ_CSR_LINK_ERR_SHIFT                             25

/* SM :: IRQ_CSR :: reserved0 [24:24] */
#define BCHP_SM_IRQ_CSR_reserved0_MASK                             0x01000000
#define BCHP_SM_IRQ_CSR_reserved0_SHIFT                            24

/* SM :: IRQ_CSR :: TX_OE [23:23] */
#define BCHP_SM_IRQ_CSR_TX_OE_MASK                                 0x00800000
#define BCHP_SM_IRQ_CSR_TX_OE_SHIFT                                23

/* SM :: IRQ_CSR :: TX_UE [22:22] */
#define BCHP_SM_IRQ_CSR_TX_UE_MASK                                 0x00400000
#define BCHP_SM_IRQ_CSR_TX_UE_SHIFT                                22

/* SM :: IRQ_CSR :: reserved1 [21:20] */
#define BCHP_SM_IRQ_CSR_reserved1_MASK                             0x00300000
#define BCHP_SM_IRQ_CSR_reserved1_SHIFT                            20

/* SM :: IRQ_CSR :: RX_OE [19:19] */
#define BCHP_SM_IRQ_CSR_RX_OE_MASK                                 0x00080000
#define BCHP_SM_IRQ_CSR_RX_OE_SHIFT                                19

/* SM :: IRQ_CSR :: RX_UE [18:18] */
#define BCHP_SM_IRQ_CSR_RX_UE_MASK                                 0x00040000
#define BCHP_SM_IRQ_CSR_RX_UE_SHIFT                                18

/* SM :: IRQ_CSR :: reserved2 [17:16] */
#define BCHP_SM_IRQ_CSR_reserved2_MASK                             0x00030000
#define BCHP_SM_IRQ_CSR_reserved2_SHIFT                            16

/* SM :: IRQ_CSR :: TIME_EN [15:15] */
#define BCHP_SM_IRQ_CSR_TIME_EN_MASK                               0x00008000
#define BCHP_SM_IRQ_CSR_TIME_EN_SHIFT                              15

/* SM :: IRQ_CSR :: IO_DONE_EN [14:14] */
#define BCHP_SM_IRQ_CSR_IO_DONE_EN_MASK                            0x00004000
#define BCHP_SM_IRQ_CSR_IO_DONE_EN_SHIFT                           14

/* SM :: IRQ_CSR :: OH_TO_EN [13:13] */
#define BCHP_SM_IRQ_CSR_OH_TO_EN_MASK                              0x00002000
#define BCHP_SM_IRQ_CSR_OH_TO_EN_SHIFT                             13

/* SM :: IRQ_CSR :: HANG_UP_EN [12:12] */
#define BCHP_SM_IRQ_CSR_HANG_UP_EN_MASK                            0x00001000
#define BCHP_SM_IRQ_CSR_HANG_UP_EN_SHIFT                           12

/* SM :: IRQ_CSR :: RING_1_EN [11:11] */
#define BCHP_SM_IRQ_CSR_RING_1_EN_MASK                             0x00000800
#define BCHP_SM_IRQ_CSR_RING_1_EN_SHIFT                            11

/* SM :: IRQ_CSR :: RING_0_EN [10:10] */
#define BCHP_SM_IRQ_CSR_RING_0_EN_MASK                             0x00000400
#define BCHP_SM_IRQ_CSR_RING_0_EN_SHIFT                            10

/* SM :: IRQ_CSR :: LINK_ERR_EN [09:09] */
#define BCHP_SM_IRQ_CSR_LINK_ERR_EN_MASK                           0x00000200
#define BCHP_SM_IRQ_CSR_LINK_ERR_EN_SHIFT                          9

/* SM :: IRQ_CSR :: reserved3 [08:08] */
#define BCHP_SM_IRQ_CSR_reserved3_MASK                             0x00000100
#define BCHP_SM_IRQ_CSR_reserved3_SHIFT                            8

/* SM :: IRQ_CSR :: TOE_EN [07:07] */
#define BCHP_SM_IRQ_CSR_TOE_EN_MASK                                0x00000080
#define BCHP_SM_IRQ_CSR_TOE_EN_SHIFT                               7

/* SM :: IRQ_CSR :: TUE_EN [06:06] */
#define BCHP_SM_IRQ_CSR_TUE_EN_MASK                                0x00000040
#define BCHP_SM_IRQ_CSR_TUE_EN_SHIFT                               6

/* SM :: IRQ_CSR :: TAE_EN [05:05] */
#define BCHP_SM_IRQ_CSR_TAE_EN_MASK                                0x00000020
#define BCHP_SM_IRQ_CSR_TAE_EN_SHIFT                               5

/* SM :: IRQ_CSR :: TDE_EN [04:04] */
#define BCHP_SM_IRQ_CSR_TDE_EN_MASK                                0x00000010
#define BCHP_SM_IRQ_CSR_TDE_EN_SHIFT                               4

/* SM :: IRQ_CSR :: ROE_EN [03:03] */
#define BCHP_SM_IRQ_CSR_ROE_EN_MASK                                0x00000008
#define BCHP_SM_IRQ_CSR_ROE_EN_SHIFT                               3

/* SM :: IRQ_CSR :: RUE_EN [02:02] */
#define BCHP_SM_IRQ_CSR_RUE_EN_MASK                                0x00000004
#define BCHP_SM_IRQ_CSR_RUE_EN_SHIFT                               2

/* SM :: IRQ_CSR :: RAE_EN [01:01] */
#define BCHP_SM_IRQ_CSR_RAE_EN_MASK                                0x00000002
#define BCHP_SM_IRQ_CSR_RAE_EN_SHIFT                               1

/* SM :: IRQ_CSR :: RDE_EN [00:00] */
#define BCHP_SM_IRQ_CSR_RDE_EN_MASK                                0x00000001
#define BCHP_SM_IRQ_CSR_RDE_EN_SHIFT                               0

/***************************************************************************
 *EXT_DAA_CMD - External DAA Command Register
 ***************************************************************************/
/* union - case Si3021_mode [31:00] */
/* SM :: EXT_DAA_CMD :: Si3021_mode :: reserved0 [31:14] */
#define BCHP_SM_EXT_DAA_CMD_Si3021_mode_reserved0_MASK             0xffffc000
#define BCHP_SM_EXT_DAA_CMD_Si3021_mode_reserved0_SHIFT            14

/* SM :: EXT_DAA_CMD :: Si3021_mode :: READ [13:13] */
#define BCHP_SM_EXT_DAA_CMD_Si3021_mode_READ_MASK                  0x00002000
#define BCHP_SM_EXT_DAA_CMD_Si3021_mode_READ_SHIFT                 13

/* SM :: EXT_DAA_CMD :: Si3021_mode :: ADDRESS [12:08] */
#define BCHP_SM_EXT_DAA_CMD_Si3021_mode_ADDRESS_MASK               0x00001f00
#define BCHP_SM_EXT_DAA_CMD_Si3021_mode_ADDRESS_SHIFT              8

/* SM :: EXT_DAA_CMD :: Si3021_mode :: DATA [07:00] */
#define BCHP_SM_EXT_DAA_CMD_Si3021_mode_DATA_MASK                  0x000000ff
#define BCHP_SM_EXT_DAA_CMD_Si3021_mode_DATA_SHIFT                 0

/* union - case GP_DAA_mode [31:00] */
/* SM :: EXT_DAA_CMD :: GP_DAA_mode :: BUSY [31:31] */
#define BCHP_SM_EXT_DAA_CMD_GP_DAA_mode_BUSY_MASK                  0x80000000
#define BCHP_SM_EXT_DAA_CMD_GP_DAA_mode_BUSY_SHIFT                 31

/* SM :: EXT_DAA_CMD :: GP_DAA_mode :: reserved0 [30:19] */
#define BCHP_SM_EXT_DAA_CMD_GP_DAA_mode_reserved0_MASK             0x7ff80000
#define BCHP_SM_EXT_DAA_CMD_GP_DAA_mode_reserved0_SHIFT            19

/* SM :: EXT_DAA_CMD :: GP_DAA_mode :: IO_FN [18:17] */
#define BCHP_SM_EXT_DAA_CMD_GP_DAA_mode_IO_FN_MASK                 0x00060000
#define BCHP_SM_EXT_DAA_CMD_GP_DAA_mode_IO_FN_SHIFT                17

/* SM :: EXT_DAA_CMD :: GP_DAA_mode :: DLY_BSY [16:16] */
#define BCHP_SM_EXT_DAA_CMD_GP_DAA_mode_DLY_BSY_MASK               0x00010000
#define BCHP_SM_EXT_DAA_CMD_GP_DAA_mode_DLY_BSY_SHIFT              16

/* SM :: EXT_DAA_CMD :: GP_DAA_mode :: DAA_CMD [15:00] */
#define BCHP_SM_EXT_DAA_CMD_GP_DAA_mode_DAA_CMD_MASK               0x0000ffff
#define BCHP_SM_EXT_DAA_CMD_GP_DAA_mode_DAA_CMD_SHIFT              0

/***************************************************************************
 *EXT_DAA_STAT - External DAA Status Register
 ***************************************************************************/
/* union - case Si3021_mode [31:00] */
/* SM :: EXT_DAA_STAT :: Si3021_mode :: reserved0 [31:16] */
#define BCHP_SM_EXT_DAA_STAT_Si3021_mode_reserved0_MASK            0xffff0000
#define BCHP_SM_EXT_DAA_STAT_Si3021_mode_reserved0_SHIFT           16

/* SM :: EXT_DAA_STAT :: Si3021_mode :: BUSY [15:15] */
#define BCHP_SM_EXT_DAA_STAT_Si3021_mode_BUSY_MASK                 0x00008000
#define BCHP_SM_EXT_DAA_STAT_Si3021_mode_BUSY_SHIFT                15

/* SM :: EXT_DAA_STAT :: Si3021_mode :: reserved1 [14:08] */
#define BCHP_SM_EXT_DAA_STAT_Si3021_mode_reserved1_MASK            0x00007f00
#define BCHP_SM_EXT_DAA_STAT_Si3021_mode_reserved1_SHIFT           8

/* SM :: EXT_DAA_STAT :: Si3021_mode :: DAA_RSP [07:00] */
#define BCHP_SM_EXT_DAA_STAT_Si3021_mode_DAA_RSP_MASK              0x000000ff
#define BCHP_SM_EXT_DAA_STAT_Si3021_mode_DAA_RSP_SHIFT             0

/* union - case GP_DAA_mode [31:00] */
/* SM :: EXT_DAA_STAT :: GP_DAA_mode :: BUSY [31:31] */
#define BCHP_SM_EXT_DAA_STAT_GP_DAA_mode_BUSY_MASK                 0x80000000
#define BCHP_SM_EXT_DAA_STAT_GP_DAA_mode_BUSY_SHIFT                31

/* SM :: EXT_DAA_STAT :: GP_DAA_mode :: reserved0 [30:16] */
#define BCHP_SM_EXT_DAA_STAT_GP_DAA_mode_reserved0_MASK            0x7fff0000
#define BCHP_SM_EXT_DAA_STAT_GP_DAA_mode_reserved0_SHIFT           16

/* SM :: EXT_DAA_STAT :: GP_DAA_mode :: DAA_RSP [15:00] */
#define BCHP_SM_EXT_DAA_STAT_GP_DAA_mode_DAA_RSP_MASK              0x0000ffff
#define BCHP_SM_EXT_DAA_STAT_GP_DAA_mode_DAA_RSP_SHIFT             0

/***************************************************************************
 *GP_TIMER_CFG - General Purpose Timer Configuration Register
 ***************************************************************************/
/* SM :: GP_TIMER_CFG :: GP_TIMER_RELOAD [31:00] */
#define BCHP_SM_GP_TIMER_CFG_GP_TIMER_RELOAD_MASK                  0xffffffff
#define BCHP_SM_GP_TIMER_CFG_GP_TIMER_RELOAD_SHIFT                 0

/***************************************************************************
 *GP_TIMER_STAT - General Purpose Timer Down Counter Status Register
 ***************************************************************************/
/* SM :: GP_TIMER_STAT :: GP_TIME_COUNT [31:00] */
#define BCHP_SM_GP_TIMER_STAT_GP_TIME_COUNT_MASK                   0xffffffff
#define BCHP_SM_GP_TIMER_STAT_GP_TIME_COUNT_SHIFT                  0

/***************************************************************************
 *OH_TIMER_DIAG - Off Hook Timer Diagnostic Register
 ***************************************************************************/
/* SM :: OH_TIMER_DIAG :: CNT_PB_CLK [31:31] */
#define BCHP_SM_OH_TIMER_DIAG_CNT_PB_CLK_MASK                      0x80000000
#define BCHP_SM_OH_TIMER_DIAG_CNT_PB_CLK_SHIFT                     31

/* SM :: OH_TIMER_DIAG :: reserved0 [30:13] */
#define BCHP_SM_OH_TIMER_DIAG_reserved0_MASK                       0x7fffe000
#define BCHP_SM_OH_TIMER_DIAG_reserved0_SHIFT                      13

/* SM :: OH_TIMER_DIAG :: OH_TIMER [12:00] */
#define BCHP_SM_OH_TIMER_DIAG_OH_TIMER_MASK                        0x00001fff
#define BCHP_SM_OH_TIMER_DIAG_OH_TIMER_SHIFT                       0

/***************************************************************************
 *DIAG_CFG - Diagnostic Configuration Register
 ***************************************************************************/
/* SM :: DIAG_CFG :: reserved0 [31:05] */
#define BCHP_SM_DIAG_CFG_reserved0_MASK                            0xffffffe0
#define BCHP_SM_DIAG_CFG_reserved0_SHIFT                           5

/* SM :: DIAG_CFG :: TST_PT_SEL [04:00] */
#define BCHP_SM_DIAG_CFG_TST_PT_SEL_MASK                           0x0000001f
#define BCHP_SM_DIAG_CFG_TST_PT_SEL_SHIFT                          0

/***************************************************************************
 *REV - Soft Modem Interface Revision Register
 ***************************************************************************/
/* SM :: REV :: IF_MODE [31:31] */
#define BCHP_SM_REV_IF_MODE_MASK                                   0x80000000
#define BCHP_SM_REV_IF_MODE_SHIFT                                  31
#define BCHP_SM_REV_IF_MODE_Si3021_mode                            0
#define BCHP_SM_REV_IF_MODE_GP_DAA_mode                            1

/* SM :: REV :: reserved0 [30:08] */
#define BCHP_SM_REV_reserved0_MASK                                 0x7fffff00
#define BCHP_SM_REV_reserved0_SHIFT                                8

/* SM :: REV :: REVISION [07:00] */
#define BCHP_SM_REV_REVISION_MASK                                  0x000000ff
#define BCHP_SM_REV_REVISION_SHIFT                                 0

/***************************************************************************
 *DAA_FIELD_SEL - DAA Polling Field Selection Register
 ***************************************************************************/
/* union - case Si3021_mode [31:00] */
/* SM :: DAA_FIELD_SEL :: Si3021_mode :: reserved0 [31:00] */
#define BCHP_SM_DAA_FIELD_SEL_Si3021_mode_reserved0_MASK           0xffffffff
#define BCHP_SM_DAA_FIELD_SEL_Si3021_mode_reserved0_SHIFT          0

/* union - case GP_DAA_mode [31:00] */
/* SM :: DAA_FIELD_SEL :: GP_DAA_mode :: SELECT_BITS [31:16] */
#define BCHP_SM_DAA_FIELD_SEL_GP_DAA_mode_SELECT_BITS_MASK         0xffff0000
#define BCHP_SM_DAA_FIELD_SEL_GP_DAA_mode_SELECT_BITS_SHIFT        16

/* SM :: DAA_FIELD_SEL :: GP_DAA_mode :: INVERT_BITS [15:00] */
#define BCHP_SM_DAA_FIELD_SEL_GP_DAA_mode_INVERT_BITS_MASK         0x0000ffff
#define BCHP_SM_DAA_FIELD_SEL_GP_DAA_mode_INVERT_BITS_SHIFT        0

#endif /* #ifndef BCHP_SM_H__ */

/* End of File */
