/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Mar 20 13:01:33 2009
 *                 MD5 Checksum         4f0509cfa0b8fc4589050694b4a3e234
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7340/rdb/a0/bchp_tpcap.h $
 * 
 * Hydra_Software_Devel/1   3/22/09 9:15p yuxiaz
 * PR53430: Initial version of header files.
 *
 ***************************************************************************/

#ifndef BCHP_TPCAP_H__
#define BCHP_TPCAP_H__

/***************************************************************************
 *TPCAP - Registers for the Testport Capture block
 ***************************************************************************/
#define BCHP_TPCAP_CONTROL                       0x00401400 /* Capture Control Register */
#define BCHP_TPCAP_BLOCK_SELECT                  0x00401404 /* Functional Block select Register */
#define BCHP_TPCAP_DEST_ADDR                     0x00401408 /* Destination address Register */
#define BCHP_TPCAP_SIZE                          0x0040140c /* Capture size Register */
#define BCHP_TPCAP_SIZE_STATUS                   0x00401410 /* Capture size Status Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0            0x00401414 /* Input Mux Select 0 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1            0x00401418 /* Input Mux Select 1 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2            0x0040141c /* Input Mux Select 2 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3            0x00401420 /* Input Mux Select 3 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4            0x00401424 /* Input Mux Select 4 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5            0x00401428 /* Input Mux Select 5 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6            0x0040142c /* Input Mux Select 6 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7            0x00401430 /* Input Mux Select 7 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8            0x00401434 /* Input Mux Select 8 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9            0x00401438 /* Input Mux Select 9 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10           0x0040143c /* Input Mux Select 10 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11           0x00401440 /* Input Mux Select 11 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12           0x00401444 /* Input Mux Select 12 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13           0x00401448 /* Input Mux Select 13 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14           0x0040144c /* Input Mux Select 14 Register */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15           0x00401450 /* Input Mux Select 15 Register */
#define BCHP_TPCAP_START_TRIGGER_MASK_HI         0x00401454 /* Start Trigger Mask High */
#define BCHP_TPCAP_START_TRIGGER_MASK_LO         0x00401458 /* Start Trigger Mask Low */
#define BCHP_TPCAP_START_TRIGGER_VALUE_HI        0x0040145c /* Start Trigger Value High */
#define BCHP_TPCAP_START_TRIGGER_VALUE_LO        0x00401460 /* Start Trigger Value Low */
#define BCHP_TPCAP_STOP_TRIGGER_MASK_HI          0x00401464 /* Stop Trigger Mask High */
#define BCHP_TPCAP_STOP_TRIGGER_MASK_LO          0x00401468 /* Stop Trigger Mask Low */
#define BCHP_TPCAP_STOP_TRIGGER_VALUE_HI         0x0040146c /* Stop Trigger Value High */
#define BCHP_TPCAP_STOP_TRIGGER_VALUE_LO         0x00401470 /* Stop Trigger Value Low */
#define BCHP_TPCAP_CLKEN_MASK_HI                 0x00401474 /* Clock Enable Mask High */
#define BCHP_TPCAP_CLKEN_MASK_LO                 0x00401478 /* Clock Enable Mask Low */
#define BCHP_TPCAP_CLKEN_VALUE_HI                0x0040147c /* Clock Enable Value High */
#define BCHP_TPCAP_CLKEN_VALUE_LO                0x00401480 /* Clock Enable Value Low */

/***************************************************************************
 *CONTROL - Capture Control Register
 ***************************************************************************/
/* TPCAP :: CONTROL :: reserved0 [31:15] */
#define BCHP_TPCAP_CONTROL_reserved0_MASK                          0xffff8000
#define BCHP_TPCAP_CONTROL_reserved0_SHIFT                         15

/* TPCAP :: CONTROL :: DEMUX_MODE [14:12] */
#define BCHP_TPCAP_CONTROL_DEMUX_MODE_MASK                         0x00007000
#define BCHP_TPCAP_CONTROL_DEMUX_MODE_SHIFT                        12

/* TPCAP :: CONTROL :: reserved1 [11:10] */
#define BCHP_TPCAP_CONTROL_reserved1_MASK                          0x00000c00
#define BCHP_TPCAP_CONTROL_reserved1_SHIFT                         10

/* TPCAP :: CONTROL :: CAPT_WIDTH [09:08] */
#define BCHP_TPCAP_CONTROL_CAPT_WIDTH_MASK                         0x00000300
#define BCHP_TPCAP_CONTROL_CAPT_WIDTH_SHIFT                        8

/* TPCAP :: CONTROL :: LITTLE_ENDIAN [07:07] */
#define BCHP_TPCAP_CONTROL_LITTLE_ENDIAN_MASK                      0x00000080
#define BCHP_TPCAP_CONTROL_LITTLE_ENDIAN_SHIFT                     7

/* TPCAP :: CONTROL :: ENA_PTRN_STOP_TRIGGER [06:06] */
#define BCHP_TPCAP_CONTROL_ENA_PTRN_STOP_TRIGGER_MASK              0x00000040
#define BCHP_TPCAP_CONTROL_ENA_PTRN_STOP_TRIGGER_SHIFT             6

/* TPCAP :: CONTROL :: ENA_CTRL_STOP_TRIGGER [05:05] */
#define BCHP_TPCAP_CONTROL_ENA_CTRL_STOP_TRIGGER_MASK              0x00000020
#define BCHP_TPCAP_CONTROL_ENA_CTRL_STOP_TRIGGER_SHIFT             5

/* TPCAP :: CONTROL :: ENA_PTRN_START_TRIGGER [04:04] */
#define BCHP_TPCAP_CONTROL_ENA_PTRN_START_TRIGGER_MASK             0x00000010
#define BCHP_TPCAP_CONTROL_ENA_PTRN_START_TRIGGER_SHIFT            4

/* TPCAP :: CONTROL :: ENA_CTRL_START_TRIGGER [03:03] */
#define BCHP_TPCAP_CONTROL_ENA_CTRL_START_TRIGGER_MASK             0x00000008
#define BCHP_TPCAP_CONTROL_ENA_CTRL_START_TRIGGER_SHIFT            3

/* TPCAP :: CONTROL :: ENA_PTRN_CLK_ENA [02:02] */
#define BCHP_TPCAP_CONTROL_ENA_PTRN_CLK_ENA_MASK                   0x00000004
#define BCHP_TPCAP_CONTROL_ENA_PTRN_CLK_ENA_SHIFT                  2

/* TPCAP :: CONTROL :: ENA_CTRL_CLK_ENA [01:01] */
#define BCHP_TPCAP_CONTROL_ENA_CTRL_CLK_ENA_MASK                   0x00000002
#define BCHP_TPCAP_CONTROL_ENA_CTRL_CLK_ENA_SHIFT                  1

/* TPCAP :: CONTROL :: CAPT_ENABLE [00:00] */
#define BCHP_TPCAP_CONTROL_CAPT_ENABLE_MASK                        0x00000001
#define BCHP_TPCAP_CONTROL_CAPT_ENABLE_SHIFT                       0

/***************************************************************************
 *BLOCK_SELECT - Functional Block select Register
 ***************************************************************************/
/* TPCAP :: BLOCK_SELECT :: reserved0 [31:03] */
#define BCHP_TPCAP_BLOCK_SELECT_reserved0_MASK                     0xfffffff8
#define BCHP_TPCAP_BLOCK_SELECT_reserved0_SHIFT                    3

/* TPCAP :: BLOCK_SELECT :: encoded_tpcap_en [02:00] */
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_MASK              0x00000007
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_SHIFT             0
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_MOCA              0
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_UNUSED_1          1
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_UNUSED_2          2
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_UNUSED_3          3
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_UNUSED_4          4
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_UNUSED_5          5
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_UNUSED_6          6
#define BCHP_TPCAP_BLOCK_SELECT_encoded_tpcap_en_UNUSED_7          7

/***************************************************************************
 *DEST_ADDR - Destination address Register
 ***************************************************************************/
/* TPCAP :: DEST_ADDR :: DEST_ADDR [31:05] */
#define BCHP_TPCAP_DEST_ADDR_DEST_ADDR_MASK                        0xffffffe0
#define BCHP_TPCAP_DEST_ADDR_DEST_ADDR_SHIFT                       5

/* TPCAP :: DEST_ADDR :: reserved0 [04:00] */
#define BCHP_TPCAP_DEST_ADDR_reserved0_MASK                        0x0000001f
#define BCHP_TPCAP_DEST_ADDR_reserved0_SHIFT                       0

/***************************************************************************
 *SIZE - Capture size Register
 ***************************************************************************/
/* TPCAP :: SIZE :: CAPT_SIZE [31:00] */
#define BCHP_TPCAP_SIZE_CAPT_SIZE_MASK                             0xffffffff
#define BCHP_TPCAP_SIZE_CAPT_SIZE_SHIFT                            0

/***************************************************************************
 *SIZE_STATUS - Capture size Status Register
 ***************************************************************************/
/* TPCAP :: SIZE_STATUS :: CAPT_SIZE_STATUS [31:00] */
#define BCHP_TPCAP_SIZE_STATUS_CAPT_SIZE_STATUS_MASK               0xffffffff
#define BCHP_TPCAP_SIZE_STATUS_CAPT_SIZE_STATUS_SHIFT              0

/***************************************************************************
 *INPUT_MUX_SELECT_0 - Input Mux Select 0 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_0 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_0 :: MUX_DATA_3 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_3_MASK              0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_3_SHIFT             24

/* TPCAP :: INPUT_MUX_SELECT_0 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_0 :: MUX_DATA_2 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_2_MASK              0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_2_SHIFT             16

/* TPCAP :: INPUT_MUX_SELECT_0 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_0 :: MUX_DATA_1 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_1_MASK              0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_1_SHIFT             8

/* TPCAP :: INPUT_MUX_SELECT_0 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_0 :: MUX_DATA_0 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_0_MASK              0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_0_MUX_DATA_0_SHIFT             0

/***************************************************************************
 *INPUT_MUX_SELECT_1 - Input Mux Select 1 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_1 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_1 :: MUX_DATA_7 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_7_MASK              0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_7_SHIFT             24

/* TPCAP :: INPUT_MUX_SELECT_1 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_1 :: MUX_DATA_6 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_6_MASK              0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_6_SHIFT             16

/* TPCAP :: INPUT_MUX_SELECT_1 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_1 :: MUX_DATA_5 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_5_MASK              0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_5_SHIFT             8

/* TPCAP :: INPUT_MUX_SELECT_1 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_1 :: MUX_DATA_4 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_4_MASK              0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_1_MUX_DATA_4_SHIFT             0

/***************************************************************************
 *INPUT_MUX_SELECT_2 - Input Mux Select 2 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_2 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_2 :: MUX_DATA_11 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_11_MASK             0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_11_SHIFT            24

/* TPCAP :: INPUT_MUX_SELECT_2 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_2 :: MUX_DATA_10 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_10_MASK             0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_10_SHIFT            16

/* TPCAP :: INPUT_MUX_SELECT_2 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_2 :: MUX_DATA_9 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_9_MASK              0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_9_SHIFT             8

/* TPCAP :: INPUT_MUX_SELECT_2 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_2 :: MUX_DATA_8 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_8_MASK              0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_2_MUX_DATA_8_SHIFT             0

/***************************************************************************
 *INPUT_MUX_SELECT_3 - Input Mux Select 3 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_3 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_3 :: MUX_DATA_15 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_15_MASK             0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_15_SHIFT            24

/* TPCAP :: INPUT_MUX_SELECT_3 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_3 :: MUX_DATA_14 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_14_MASK             0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_14_SHIFT            16

/* TPCAP :: INPUT_MUX_SELECT_3 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_3 :: MUX_DATA_13 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_13_MASK             0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_13_SHIFT            8

/* TPCAP :: INPUT_MUX_SELECT_3 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_3 :: MUX_DATA_12 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_12_MASK             0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_3_MUX_DATA_12_SHIFT            0

/***************************************************************************
 *INPUT_MUX_SELECT_4 - Input Mux Select 4 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_4 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_4 :: MUX_DATA_19 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_19_MASK             0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_19_SHIFT            24

/* TPCAP :: INPUT_MUX_SELECT_4 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_4 :: MUX_DATA_18 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_18_MASK             0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_18_SHIFT            16

/* TPCAP :: INPUT_MUX_SELECT_4 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_4 :: MUX_DATA_17 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_17_MASK             0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_17_SHIFT            8

/* TPCAP :: INPUT_MUX_SELECT_4 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_4 :: MUX_DATA_16 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_16_MASK             0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_4_MUX_DATA_16_SHIFT            0

/***************************************************************************
 *INPUT_MUX_SELECT_5 - Input Mux Select 5 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_5 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_5 :: MUX_DATA_23 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_23_MASK             0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_23_SHIFT            24

/* TPCAP :: INPUT_MUX_SELECT_5 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_5 :: MUX_DATA_22 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_22_MASK             0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_22_SHIFT            16

/* TPCAP :: INPUT_MUX_SELECT_5 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_5 :: MUX_DATA_21 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_21_MASK             0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_21_SHIFT            8

/* TPCAP :: INPUT_MUX_SELECT_5 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_5 :: MUX_DATA_20 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_20_MASK             0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_5_MUX_DATA_20_SHIFT            0

/***************************************************************************
 *INPUT_MUX_SELECT_6 - Input Mux Select 6 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_6 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_6 :: MUX_DATA_27 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_27_MASK             0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_27_SHIFT            24

/* TPCAP :: INPUT_MUX_SELECT_6 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_6 :: MUX_DATA_26 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_26_MASK             0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_26_SHIFT            16

/* TPCAP :: INPUT_MUX_SELECT_6 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_6 :: MUX_DATA_25 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_25_MASK             0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_25_SHIFT            8

/* TPCAP :: INPUT_MUX_SELECT_6 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_6 :: MUX_DATA_24 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_24_MASK             0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_6_MUX_DATA_24_SHIFT            0

/***************************************************************************
 *INPUT_MUX_SELECT_7 - Input Mux Select 7 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_7 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_7 :: MUX_DATA_31 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_31_MASK             0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_31_SHIFT            24

/* TPCAP :: INPUT_MUX_SELECT_7 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_7 :: MUX_DATA_30 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_30_MASK             0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_30_SHIFT            16

/* TPCAP :: INPUT_MUX_SELECT_7 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_7 :: MUX_DATA_29 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_29_MASK             0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_29_SHIFT            8

/* TPCAP :: INPUT_MUX_SELECT_7 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_7 :: MUX_DATA_28 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_28_MASK             0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_7_MUX_DATA_28_SHIFT            0

/***************************************************************************
 *INPUT_MUX_SELECT_8 - Input Mux Select 8 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_8 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_8 :: MUX_DATA_35 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_35_MASK             0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_35_SHIFT            24

/* TPCAP :: INPUT_MUX_SELECT_8 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_8 :: MUX_DATA_34 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_34_MASK             0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_34_SHIFT            16

/* TPCAP :: INPUT_MUX_SELECT_8 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_8 :: MUX_DATA_33 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_33_MASK             0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_33_SHIFT            8

/* TPCAP :: INPUT_MUX_SELECT_8 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_8 :: MUX_DATA_32 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_32_MASK             0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_8_MUX_DATA_32_SHIFT            0

/***************************************************************************
 *INPUT_MUX_SELECT_9 - Input Mux Select 9 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_9 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_reserved0_MASK               0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_reserved0_SHIFT              30

/* TPCAP :: INPUT_MUX_SELECT_9 :: MUX_DATA_39 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_39_MASK             0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_39_SHIFT            24

/* TPCAP :: INPUT_MUX_SELECT_9 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_reserved1_MASK               0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_reserved1_SHIFT              22

/* TPCAP :: INPUT_MUX_SELECT_9 :: MUX_DATA_38 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_38_MASK             0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_38_SHIFT            16

/* TPCAP :: INPUT_MUX_SELECT_9 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_reserved2_MASK               0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_reserved2_SHIFT              14

/* TPCAP :: INPUT_MUX_SELECT_9 :: MUX_DATA_37 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_37_MASK             0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_37_SHIFT            8

/* TPCAP :: INPUT_MUX_SELECT_9 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_reserved3_MASK               0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_reserved3_SHIFT              6

/* TPCAP :: INPUT_MUX_SELECT_9 :: MUX_DATA_36 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_36_MASK             0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_9_MUX_DATA_36_SHIFT            0

/***************************************************************************
 *INPUT_MUX_SELECT_10 - Input Mux Select 10 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_10 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_reserved0_MASK              0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_reserved0_SHIFT             30

/* TPCAP :: INPUT_MUX_SELECT_10 :: MUX_DATA_43 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_43_MASK            0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_43_SHIFT           24

/* TPCAP :: INPUT_MUX_SELECT_10 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_reserved1_MASK              0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_reserved1_SHIFT             22

/* TPCAP :: INPUT_MUX_SELECT_10 :: MUX_DATA_42 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_42_MASK            0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_42_SHIFT           16

/* TPCAP :: INPUT_MUX_SELECT_10 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_reserved2_MASK              0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_reserved2_SHIFT             14

/* TPCAP :: INPUT_MUX_SELECT_10 :: MUX_DATA_41 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_41_MASK            0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_41_SHIFT           8

/* TPCAP :: INPUT_MUX_SELECT_10 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_reserved3_MASK              0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_reserved3_SHIFT             6

/* TPCAP :: INPUT_MUX_SELECT_10 :: MUX_DATA_40 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_40_MASK            0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_10_MUX_DATA_40_SHIFT           0

/***************************************************************************
 *INPUT_MUX_SELECT_11 - Input Mux Select 11 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_11 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_reserved0_MASK              0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_reserved0_SHIFT             30

/* TPCAP :: INPUT_MUX_SELECT_11 :: MUX_DATA_47 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_47_MASK            0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_47_SHIFT           24

/* TPCAP :: INPUT_MUX_SELECT_11 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_reserved1_MASK              0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_reserved1_SHIFT             22

/* TPCAP :: INPUT_MUX_SELECT_11 :: MUX_DATA_46 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_46_MASK            0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_46_SHIFT           16

/* TPCAP :: INPUT_MUX_SELECT_11 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_reserved2_MASK              0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_reserved2_SHIFT             14

/* TPCAP :: INPUT_MUX_SELECT_11 :: MUX_DATA_45 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_45_MASK            0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_45_SHIFT           8

/* TPCAP :: INPUT_MUX_SELECT_11 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_reserved3_MASK              0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_reserved3_SHIFT             6

/* TPCAP :: INPUT_MUX_SELECT_11 :: MUX_DATA_44 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_44_MASK            0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_11_MUX_DATA_44_SHIFT           0

/***************************************************************************
 *INPUT_MUX_SELECT_12 - Input Mux Select 12 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_12 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_reserved0_MASK              0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_reserved0_SHIFT             30

/* TPCAP :: INPUT_MUX_SELECT_12 :: MUX_DATA_51 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_51_MASK            0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_51_SHIFT           24

/* TPCAP :: INPUT_MUX_SELECT_12 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_reserved1_MASK              0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_reserved1_SHIFT             22

/* TPCAP :: INPUT_MUX_SELECT_12 :: MUX_DATA_50 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_50_MASK            0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_50_SHIFT           16

/* TPCAP :: INPUT_MUX_SELECT_12 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_reserved2_MASK              0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_reserved2_SHIFT             14

/* TPCAP :: INPUT_MUX_SELECT_12 :: MUX_DATA_49 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_49_MASK            0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_49_SHIFT           8

/* TPCAP :: INPUT_MUX_SELECT_12 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_reserved3_MASK              0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_reserved3_SHIFT             6

/* TPCAP :: INPUT_MUX_SELECT_12 :: MUX_DATA_48 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_48_MASK            0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_12_MUX_DATA_48_SHIFT           0

/***************************************************************************
 *INPUT_MUX_SELECT_13 - Input Mux Select 13 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_13 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_reserved0_MASK              0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_reserved0_SHIFT             30

/* TPCAP :: INPUT_MUX_SELECT_13 :: MUX_DATA_55 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_55_MASK            0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_55_SHIFT           24

/* TPCAP :: INPUT_MUX_SELECT_13 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_reserved1_MASK              0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_reserved1_SHIFT             22

/* TPCAP :: INPUT_MUX_SELECT_13 :: MUX_DATA_54 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_54_MASK            0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_54_SHIFT           16

/* TPCAP :: INPUT_MUX_SELECT_13 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_reserved2_MASK              0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_reserved2_SHIFT             14

/* TPCAP :: INPUT_MUX_SELECT_13 :: MUX_DATA_53 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_53_MASK            0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_53_SHIFT           8

/* TPCAP :: INPUT_MUX_SELECT_13 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_reserved3_MASK              0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_reserved3_SHIFT             6

/* TPCAP :: INPUT_MUX_SELECT_13 :: MUX_DATA_52 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_52_MASK            0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_13_MUX_DATA_52_SHIFT           0

/***************************************************************************
 *INPUT_MUX_SELECT_14 - Input Mux Select 14 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_14 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_reserved0_MASK              0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_reserved0_SHIFT             30

/* TPCAP :: INPUT_MUX_SELECT_14 :: MUX_DATA_59 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_59_MASK            0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_59_SHIFT           24

/* TPCAP :: INPUT_MUX_SELECT_14 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_reserved1_MASK              0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_reserved1_SHIFT             22

/* TPCAP :: INPUT_MUX_SELECT_14 :: MUX_DATA_58 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_58_MASK            0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_58_SHIFT           16

/* TPCAP :: INPUT_MUX_SELECT_14 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_reserved2_MASK              0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_reserved2_SHIFT             14

/* TPCAP :: INPUT_MUX_SELECT_14 :: MUX_DATA_57 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_57_MASK            0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_57_SHIFT           8

/* TPCAP :: INPUT_MUX_SELECT_14 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_reserved3_MASK              0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_reserved3_SHIFT             6

/* TPCAP :: INPUT_MUX_SELECT_14 :: MUX_DATA_56 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_56_MASK            0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_14_MUX_DATA_56_SHIFT           0

/***************************************************************************
 *INPUT_MUX_SELECT_15 - Input Mux Select 15 Register
 ***************************************************************************/
/* TPCAP :: INPUT_MUX_SELECT_15 :: reserved0 [31:30] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_reserved0_MASK              0xc0000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_reserved0_SHIFT             30

/* TPCAP :: INPUT_MUX_SELECT_15 :: MUX_DATA_63 [29:24] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_63_MASK            0x3f000000
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_63_SHIFT           24

/* TPCAP :: INPUT_MUX_SELECT_15 :: reserved1 [23:22] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_reserved1_MASK              0x00c00000
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_reserved1_SHIFT             22

/* TPCAP :: INPUT_MUX_SELECT_15 :: MUX_DATA_62 [21:16] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_62_MASK            0x003f0000
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_62_SHIFT           16

/* TPCAP :: INPUT_MUX_SELECT_15 :: reserved2 [15:14] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_reserved2_MASK              0x0000c000
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_reserved2_SHIFT             14

/* TPCAP :: INPUT_MUX_SELECT_15 :: MUX_DATA_61 [13:08] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_61_MASK            0x00003f00
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_61_SHIFT           8

/* TPCAP :: INPUT_MUX_SELECT_15 :: reserved3 [07:06] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_reserved3_MASK              0x000000c0
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_reserved3_SHIFT             6

/* TPCAP :: INPUT_MUX_SELECT_15 :: MUX_DATA_60 [05:00] */
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_60_MASK            0x0000003f
#define BCHP_TPCAP_INPUT_MUX_SELECT_15_MUX_DATA_60_SHIFT           0

/***************************************************************************
 *START_TRIGGER_MASK_HI - Start Trigger Mask High
 ***************************************************************************/
/* TPCAP :: START_TRIGGER_MASK_HI :: START_TRIGGER_MASK_HI [31:00] */
#define BCHP_TPCAP_START_TRIGGER_MASK_HI_START_TRIGGER_MASK_HI_MASK 0xffffffff
#define BCHP_TPCAP_START_TRIGGER_MASK_HI_START_TRIGGER_MASK_HI_SHIFT 0

/***************************************************************************
 *START_TRIGGER_MASK_LO - Start Trigger Mask Low
 ***************************************************************************/
/* TPCAP :: START_TRIGGER_MASK_LO :: START_TRIGGER_MASK_LO [31:00] */
#define BCHP_TPCAP_START_TRIGGER_MASK_LO_START_TRIGGER_MASK_LO_MASK 0xffffffff
#define BCHP_TPCAP_START_TRIGGER_MASK_LO_START_TRIGGER_MASK_LO_SHIFT 0

/***************************************************************************
 *START_TRIGGER_VALUE_HI - Start Trigger Value High
 ***************************************************************************/
/* TPCAP :: START_TRIGGER_VALUE_HI :: START_TRIGGER_VALUE_HI [31:00] */
#define BCHP_TPCAP_START_TRIGGER_VALUE_HI_START_TRIGGER_VALUE_HI_MASK 0xffffffff
#define BCHP_TPCAP_START_TRIGGER_VALUE_HI_START_TRIGGER_VALUE_HI_SHIFT 0

/***************************************************************************
 *START_TRIGGER_VALUE_LO - Start Trigger Value Low
 ***************************************************************************/
/* TPCAP :: START_TRIGGER_VALUE_LO :: START_TRIGGER_VALUE_LO [31:00] */
#define BCHP_TPCAP_START_TRIGGER_VALUE_LO_START_TRIGGER_VALUE_LO_MASK 0xffffffff
#define BCHP_TPCAP_START_TRIGGER_VALUE_LO_START_TRIGGER_VALUE_LO_SHIFT 0

/***************************************************************************
 *STOP_TRIGGER_MASK_HI - Stop Trigger Mask High
 ***************************************************************************/
/* TPCAP :: STOP_TRIGGER_MASK_HI :: STOP_TRIGGER_MASK_HI [31:00] */
#define BCHP_TPCAP_STOP_TRIGGER_MASK_HI_STOP_TRIGGER_MASK_HI_MASK  0xffffffff
#define BCHP_TPCAP_STOP_TRIGGER_MASK_HI_STOP_TRIGGER_MASK_HI_SHIFT 0

/***************************************************************************
 *STOP_TRIGGER_MASK_LO - Stop Trigger Mask Low
 ***************************************************************************/
/* TPCAP :: STOP_TRIGGER_MASK_LO :: STOP_TRIGGER_MASK_LO [31:00] */
#define BCHP_TPCAP_STOP_TRIGGER_MASK_LO_STOP_TRIGGER_MASK_LO_MASK  0xffffffff
#define BCHP_TPCAP_STOP_TRIGGER_MASK_LO_STOP_TRIGGER_MASK_LO_SHIFT 0

/***************************************************************************
 *STOP_TRIGGER_VALUE_HI - Stop Trigger Value High
 ***************************************************************************/
/* TPCAP :: STOP_TRIGGER_VALUE_HI :: STOP_TRIGGER_VALUE_HI [31:00] */
#define BCHP_TPCAP_STOP_TRIGGER_VALUE_HI_STOP_TRIGGER_VALUE_HI_MASK 0xffffffff
#define BCHP_TPCAP_STOP_TRIGGER_VALUE_HI_STOP_TRIGGER_VALUE_HI_SHIFT 0

/***************************************************************************
 *STOP_TRIGGER_VALUE_LO - Stop Trigger Value Low
 ***************************************************************************/
/* TPCAP :: STOP_TRIGGER_VALUE_LO :: STOP_TRIGGER_VALUE_LO [31:00] */
#define BCHP_TPCAP_STOP_TRIGGER_VALUE_LO_STOP_TRIGGER_VALUE_LO_MASK 0xffffffff
#define BCHP_TPCAP_STOP_TRIGGER_VALUE_LO_STOP_TRIGGER_VALUE_LO_SHIFT 0

/***************************************************************************
 *CLKEN_MASK_HI - Clock Enable Mask High
 ***************************************************************************/
/* TPCAP :: CLKEN_MASK_HI :: CLKEN_MASK_HI [31:00] */
#define BCHP_TPCAP_CLKEN_MASK_HI_CLKEN_MASK_HI_MASK                0xffffffff
#define BCHP_TPCAP_CLKEN_MASK_HI_CLKEN_MASK_HI_SHIFT               0

/***************************************************************************
 *CLKEN_MASK_LO - Clock Enable Mask Low
 ***************************************************************************/
/* TPCAP :: CLKEN_MASK_LO :: CLKEN_MASK_LO [31:00] */
#define BCHP_TPCAP_CLKEN_MASK_LO_CLKEN_MASK_LO_MASK                0xffffffff
#define BCHP_TPCAP_CLKEN_MASK_LO_CLKEN_MASK_LO_SHIFT               0

/***************************************************************************
 *CLKEN_VALUE_HI - Clock Enable Value High
 ***************************************************************************/
/* TPCAP :: CLKEN_VALUE_HI :: CLKEN_VALUE_HI [31:00] */
#define BCHP_TPCAP_CLKEN_VALUE_HI_CLKEN_VALUE_HI_MASK              0xffffffff
#define BCHP_TPCAP_CLKEN_VALUE_HI_CLKEN_VALUE_HI_SHIFT             0

/***************************************************************************
 *CLKEN_VALUE_LO - Clock Enable Value Low
 ***************************************************************************/
/* TPCAP :: CLKEN_VALUE_LO :: CLKEN_VALUE_LO [31:00] */
#define BCHP_TPCAP_CLKEN_VALUE_LO_CLKEN_VALUE_LO_MASK              0xffffffff
#define BCHP_TPCAP_CLKEN_VALUE_LO_CLKEN_VALUE_LO_SHIFT             0

#endif /* #ifndef BCHP_TPCAP_H__ */

/* End of File */
