/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Mar 20 13:02:28 2009
 *                 MD5 Checksum         4f0509cfa0b8fc4589050694b4a3e234
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7340/rdb/a0/bchp_secam_0.h $
 * 
 * Hydra_Software_Devel/1   3/22/09 9:08p yuxiaz
 * PR53430: Initial version of header files.
 *
 ***************************************************************************/

#ifndef BCHP_SECAM_0_H__
#define BCHP_SECAM_0_H__

/***************************************************************************
 *SECAM_0 - Secam Signal Processor SECAM_0
 ***************************************************************************/
#define BCHP_SECAM_0_SECAM_REV_ID                0x00183600 /* REVISION ID REGISTER */
#define BCHP_SECAM_0_FM_CONTROL                  0x00183604 /* FM Control Register */
#define BCHP_SECAM_0_FM_FMAMP                    0x00183608 /* FM AMP Register */
#define BCHP_SECAM_0_FM_SHAPER                   0x0018360c /* FM Shaper Register */
#define BCHP_SECAM_0_FM_SC_FREQ                  0x00183610 /* FM Base Sub-carrier Frequency */

/***************************************************************************
 *SECAM_REV_ID - REVISION ID REGISTER
 ***************************************************************************/
/* SECAM_0 :: SECAM_REV_ID :: reserved0 [31:16] */
#define BCHP_SECAM_0_SECAM_REV_ID_reserved0_MASK                   0xffff0000
#define BCHP_SECAM_0_SECAM_REV_ID_reserved0_SHIFT                  16

/* SECAM_0 :: SECAM_REV_ID :: REVISION_ID [15:00] */
#define BCHP_SECAM_0_SECAM_REV_ID_REVISION_ID_MASK                 0x0000ffff
#define BCHP_SECAM_0_SECAM_REV_ID_REVISION_ID_SHIFT                0

/***************************************************************************
 *FM_CONTROL - FM Control Register
 ***************************************************************************/
/* SECAM_0 :: FM_CONTROL :: reserved_for_eco0 [31:19] */
#define BCHP_SECAM_0_FM_CONTROL_reserved_for_eco0_MASK             0xfff80000
#define BCHP_SECAM_0_FM_CONTROL_reserved_for_eco0_SHIFT            19

/* SECAM_0 :: FM_CONTROL :: FINE_LUMA_DELAY [18:17] */
#define BCHP_SECAM_0_FM_CONTROL_FINE_LUMA_DELAY_MASK               0x00060000
#define BCHP_SECAM_0_FM_CONTROL_FINE_LUMA_DELAY_SHIFT              17

/* SECAM_0 :: FM_CONTROL :: reserved1 [16:15] */
#define BCHP_SECAM_0_FM_CONTROL_reserved1_MASK                     0x00018000
#define BCHP_SECAM_0_FM_CONTROL_reserved1_SHIFT                    15

/* SECAM_0 :: FM_CONTROL :: GROSS_LUMA_DELAY [14:10] */
#define BCHP_SECAM_0_FM_CONTROL_GROSS_LUMA_DELAY_MASK              0x00007c00
#define BCHP_SECAM_0_FM_CONTROL_GROSS_LUMA_DELAY_SHIFT             10

/* SECAM_0 :: FM_CONTROL :: FINE_SC_DELAY [09:08] */
#define BCHP_SECAM_0_FM_CONTROL_FINE_SC_DELAY_MASK                 0x00000300
#define BCHP_SECAM_0_FM_CONTROL_FINE_SC_DELAY_SHIFT                8

/* SECAM_0 :: FM_CONTROL :: reserved2 [07:06] */
#define BCHP_SECAM_0_FM_CONTROL_reserved2_MASK                     0x000000c0
#define BCHP_SECAM_0_FM_CONTROL_reserved2_SHIFT                    6

/* SECAM_0 :: FM_CONTROL :: GROSS_SC_DELAY [05:01] */
#define BCHP_SECAM_0_FM_CONTROL_GROSS_SC_DELAY_MASK                0x0000003e
#define BCHP_SECAM_0_FM_CONTROL_GROSS_SC_DELAY_SHIFT               1

/* SECAM_0 :: FM_CONTROL :: ENABLE [00:00] */
#define BCHP_SECAM_0_FM_CONTROL_ENABLE_MASK                        0x00000001
#define BCHP_SECAM_0_FM_CONTROL_ENABLE_SHIFT                       0
#define BCHP_SECAM_0_FM_CONTROL_ENABLE_ON                          1
#define BCHP_SECAM_0_FM_CONTROL_ENABLE_OFF                         0

/***************************************************************************
 *FM_FMAMP - FM AMP Register
 ***************************************************************************/
/* SECAM_0 :: FM_FMAMP :: reserved0 [31:26] */
#define BCHP_SECAM_0_FM_FMAMP_reserved0_MASK                       0xfc000000
#define BCHP_SECAM_0_FM_FMAMP_reserved0_SHIFT                      26

/* SECAM_0 :: FM_FMAMP :: LOWER_LIMIT [25:18] */
#define BCHP_SECAM_0_FM_FMAMP_LOWER_LIMIT_MASK                     0x03fc0000
#define BCHP_SECAM_0_FM_FMAMP_LOWER_LIMIT_SHIFT                    18

/* SECAM_0 :: FM_FMAMP :: UPPER_LIMIT [17:10] */
#define BCHP_SECAM_0_FM_FMAMP_UPPER_LIMIT_MASK                     0x0003fc00
#define BCHP_SECAM_0_FM_FMAMP_UPPER_LIMIT_SHIFT                    10

/* SECAM_0 :: FM_FMAMP :: SLOPE_ADJUST [09:07] */
#define BCHP_SECAM_0_FM_FMAMP_SLOPE_ADJUST_MASK                    0x00000380
#define BCHP_SECAM_0_FM_FMAMP_SLOPE_ADJUST_SHIFT                   7

/* SECAM_0 :: FM_FMAMP :: SCALE [06:00] */
#define BCHP_SECAM_0_FM_FMAMP_SCALE_MASK                           0x0000007f
#define BCHP_SECAM_0_FM_FMAMP_SCALE_SHIFT                          0

/***************************************************************************
 *FM_SHAPER - FM Shaper Register
 ***************************************************************************/
/* SECAM_0 :: FM_SHAPER :: reserved0 [31:16] */
#define BCHP_SECAM_0_FM_SHAPER_reserved0_MASK                      0xffff0000
#define BCHP_SECAM_0_FM_SHAPER_reserved0_SHIFT                     16

/* SECAM_0 :: FM_SHAPER :: FMAMP_COEFF1 [15:08] */
#define BCHP_SECAM_0_FM_SHAPER_FMAMP_COEFF1_MASK                   0x0000ff00
#define BCHP_SECAM_0_FM_SHAPER_FMAMP_COEFF1_SHIFT                  8

/* SECAM_0 :: FM_SHAPER :: FMAMP_COEFF0 [07:00] */
#define BCHP_SECAM_0_FM_SHAPER_FMAMP_COEFF0_MASK                   0x000000ff
#define BCHP_SECAM_0_FM_SHAPER_FMAMP_COEFF0_SHIFT                  0

/***************************************************************************
 *FM_SC_FREQ - FM Base Sub-carrier Frequency
 ***************************************************************************/
/* SECAM_0 :: FM_SC_FREQ :: MIN_FREQ_CLAMP [31:21] */
#define BCHP_SECAM_0_FM_SC_FREQ_MIN_FREQ_CLAMP_MASK                0xffe00000
#define BCHP_SECAM_0_FM_SC_FREQ_MIN_FREQ_CLAMP_SHIFT               21

/* SECAM_0 :: FM_SC_FREQ :: MAX_FREQ_CLAMP [20:10] */
#define BCHP_SECAM_0_FM_SC_FREQ_MAX_FREQ_CLAMP_MASK                0x001ffc00
#define BCHP_SECAM_0_FM_SC_FREQ_MAX_FREQ_CLAMP_SHIFT               10

/* SECAM_0 :: FM_SC_FREQ :: FREQ_DIFF [09:00] */
#define BCHP_SECAM_0_FM_SC_FREQ_FREQ_DIFF_MASK                     0x000003ff
#define BCHP_SECAM_0_FM_SC_FREQ_FREQ_DIFF_SHIFT                    0

#endif /* #ifndef BCHP_SECAM_0_H__ */

/* End of File */
