/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Fri Mar 20 13:06:39 2009
 *                 MD5 Checksum         4f0509cfa0b8fc4589050694b4a3e234
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7340/rdb/a0/bchp_sm_l2.h $
 * 
 * Hydra_Software_Devel/1   3/22/09 9:11p yuxiaz
 * PR53430: Initial version of header files.
 *
 ***************************************************************************/

#ifndef BCHP_SM_L2_H__
#define BCHP_SM_L2_H__

/***************************************************************************
 *SM_L2 - Registers for the soft modem block's L2 interrupt controller
 ***************************************************************************/
#define BCHP_SM_L2_CPU_STATUS                    0x00402000 /* CPU interrupt Status Register */
#define BCHP_SM_L2_CPU_SET                       0x00402004 /* CPU interrupt Set Register */
#define BCHP_SM_L2_CPU_CLEAR                     0x00402008 /* CPU interrupt Clear Register */
#define BCHP_SM_L2_CPU_MASK_STATUS               0x0040200c /* CPU interrupt Mask Status Register */
#define BCHP_SM_L2_CPU_MASK_SET                  0x00402010 /* CPU interrupt Mask Set Register */
#define BCHP_SM_L2_CPU_MASK_CLEAR                0x00402014 /* CPU interrupt Mask Clear Register */
#define BCHP_SM_L2_PCI_STATUS                    0x00402018 /* PCI interrupt Status Register */
#define BCHP_SM_L2_PCI_SET                       0x0040201c /* PCI interrupt Set Register */
#define BCHP_SM_L2_PCI_CLEAR                     0x00402020 /* PCI interrupt Clear Register */
#define BCHP_SM_L2_PCI_MASK_STATUS               0x00402024 /* PCI interrupt Mask Status Register */
#define BCHP_SM_L2_PCI_MASK_SET                  0x00402028 /* PCI interrupt Mask Set Register */
#define BCHP_SM_L2_PCI_MASK_CLEAR                0x0040202c /* PCI interrupt Mask Clear Register */

/***************************************************************************
 *CPU_STATUS - CPU interrupt Status Register
 ***************************************************************************/
/* SM_L2 :: CPU_STATUS :: reserved0 [31:05] */
#define BCHP_SM_L2_CPU_STATUS_reserved0_MASK                       0xffffffe0
#define BCHP_SM_L2_CPU_STATUS_reserved0_SHIFT                      5

/* SM_L2 :: CPU_STATUS :: DAA_RGDT_INTR [04:04] */
#define BCHP_SM_L2_CPU_STATUS_DAA_RGDT_INTR_MASK                   0x00000010
#define BCHP_SM_L2_CPU_STATUS_DAA_RGDT_INTR_SHIFT                  4

/* SM_L2 :: CPU_STATUS :: DAA_INTR [03:03] */
#define BCHP_SM_L2_CPU_STATUS_DAA_INTR_MASK                        0x00000008
#define BCHP_SM_L2_CPU_STATUS_DAA_INTR_SHIFT                       3

/* SM_L2 :: CPU_STATUS :: SM_IRQ [02:02] */
#define BCHP_SM_L2_CPU_STATUS_SM_IRQ_MASK                          0x00000004
#define BCHP_SM_L2_CPU_STATUS_SM_IRQ_SHIFT                         2

/* SM_L2 :: CPU_STATUS :: SM_RX_FIFO_INTR [01:01] */
#define BCHP_SM_L2_CPU_STATUS_SM_RX_FIFO_INTR_MASK                 0x00000002
#define BCHP_SM_L2_CPU_STATUS_SM_RX_FIFO_INTR_SHIFT                1

/* SM_L2 :: CPU_STATUS :: SM_TX_FIFO_INTR [00:00] */
#define BCHP_SM_L2_CPU_STATUS_SM_TX_FIFO_INTR_MASK                 0x00000001
#define BCHP_SM_L2_CPU_STATUS_SM_TX_FIFO_INTR_SHIFT                0

/***************************************************************************
 *CPU_SET - CPU interrupt Set Register
 ***************************************************************************/
/* SM_L2 :: CPU_SET :: reserved0 [31:05] */
#define BCHP_SM_L2_CPU_SET_reserved0_MASK                          0xffffffe0
#define BCHP_SM_L2_CPU_SET_reserved0_SHIFT                         5

/* SM_L2 :: CPU_SET :: DAA_RGDT_INTR [04:04] */
#define BCHP_SM_L2_CPU_SET_DAA_RGDT_INTR_MASK                      0x00000010
#define BCHP_SM_L2_CPU_SET_DAA_RGDT_INTR_SHIFT                     4

/* SM_L2 :: CPU_SET :: DAA_INTR [03:03] */
#define BCHP_SM_L2_CPU_SET_DAA_INTR_MASK                           0x00000008
#define BCHP_SM_L2_CPU_SET_DAA_INTR_SHIFT                          3

/* SM_L2 :: CPU_SET :: SM_IRQ [02:02] */
#define BCHP_SM_L2_CPU_SET_SM_IRQ_MASK                             0x00000004
#define BCHP_SM_L2_CPU_SET_SM_IRQ_SHIFT                            2

/* SM_L2 :: CPU_SET :: SM_RX_FIFO_INTR [01:01] */
#define BCHP_SM_L2_CPU_SET_SM_RX_FIFO_INTR_MASK                    0x00000002
#define BCHP_SM_L2_CPU_SET_SM_RX_FIFO_INTR_SHIFT                   1

/* SM_L2 :: CPU_SET :: SM_TX_FIFO_INTR [00:00] */
#define BCHP_SM_L2_CPU_SET_SM_TX_FIFO_INTR_MASK                    0x00000001
#define BCHP_SM_L2_CPU_SET_SM_TX_FIFO_INTR_SHIFT                   0

/***************************************************************************
 *CPU_CLEAR - CPU interrupt Clear Register
 ***************************************************************************/
/* SM_L2 :: CPU_CLEAR :: reserved0 [31:05] */
#define BCHP_SM_L2_CPU_CLEAR_reserved0_MASK                        0xffffffe0
#define BCHP_SM_L2_CPU_CLEAR_reserved0_SHIFT                       5

/* SM_L2 :: CPU_CLEAR :: DAA_RGDT_INTR [04:04] */
#define BCHP_SM_L2_CPU_CLEAR_DAA_RGDT_INTR_MASK                    0x00000010
#define BCHP_SM_L2_CPU_CLEAR_DAA_RGDT_INTR_SHIFT                   4

/* SM_L2 :: CPU_CLEAR :: DAA_INTR [03:03] */
#define BCHP_SM_L2_CPU_CLEAR_DAA_INTR_MASK                         0x00000008
#define BCHP_SM_L2_CPU_CLEAR_DAA_INTR_SHIFT                        3

/* SM_L2 :: CPU_CLEAR :: SM_IRQ [02:02] */
#define BCHP_SM_L2_CPU_CLEAR_SM_IRQ_MASK                           0x00000004
#define BCHP_SM_L2_CPU_CLEAR_SM_IRQ_SHIFT                          2

/* SM_L2 :: CPU_CLEAR :: SM_RX_FIFO_INTR [01:01] */
#define BCHP_SM_L2_CPU_CLEAR_SM_RX_FIFO_INTR_MASK                  0x00000002
#define BCHP_SM_L2_CPU_CLEAR_SM_RX_FIFO_INTR_SHIFT                 1

/* SM_L2 :: CPU_CLEAR :: SM_TX_FIFO_INTR [00:00] */
#define BCHP_SM_L2_CPU_CLEAR_SM_TX_FIFO_INTR_MASK                  0x00000001
#define BCHP_SM_L2_CPU_CLEAR_SM_TX_FIFO_INTR_SHIFT                 0

/***************************************************************************
 *CPU_MASK_STATUS - CPU interrupt Mask Status Register
 ***************************************************************************/
/* SM_L2 :: CPU_MASK_STATUS :: reserved0 [31:05] */
#define BCHP_SM_L2_CPU_MASK_STATUS_reserved0_MASK                  0xffffffe0
#define BCHP_SM_L2_CPU_MASK_STATUS_reserved0_SHIFT                 5

/* SM_L2 :: CPU_MASK_STATUS :: DAA_RGDT_INTR [04:04] */
#define BCHP_SM_L2_CPU_MASK_STATUS_DAA_RGDT_INTR_MASK              0x00000010
#define BCHP_SM_L2_CPU_MASK_STATUS_DAA_RGDT_INTR_SHIFT             4

/* SM_L2 :: CPU_MASK_STATUS :: DAA_INTR [03:03] */
#define BCHP_SM_L2_CPU_MASK_STATUS_DAA_INTR_MASK                   0x00000008
#define BCHP_SM_L2_CPU_MASK_STATUS_DAA_INTR_SHIFT                  3

/* SM_L2 :: CPU_MASK_STATUS :: SM_IRQ [02:02] */
#define BCHP_SM_L2_CPU_MASK_STATUS_SM_IRQ_MASK                     0x00000004
#define BCHP_SM_L2_CPU_MASK_STATUS_SM_IRQ_SHIFT                    2

/* SM_L2 :: CPU_MASK_STATUS :: SM_RX_FIFO_INTR [01:01] */
#define BCHP_SM_L2_CPU_MASK_STATUS_SM_RX_FIFO_INTR_MASK            0x00000002
#define BCHP_SM_L2_CPU_MASK_STATUS_SM_RX_FIFO_INTR_SHIFT           1

/* SM_L2 :: CPU_MASK_STATUS :: SM_TX_FIFO_INTR [00:00] */
#define BCHP_SM_L2_CPU_MASK_STATUS_SM_TX_FIFO_INTR_MASK            0x00000001
#define BCHP_SM_L2_CPU_MASK_STATUS_SM_TX_FIFO_INTR_SHIFT           0

/***************************************************************************
 *CPU_MASK_SET - CPU interrupt Mask Set Register
 ***************************************************************************/
/* SM_L2 :: CPU_MASK_SET :: reserved0 [31:05] */
#define BCHP_SM_L2_CPU_MASK_SET_reserved0_MASK                     0xffffffe0
#define BCHP_SM_L2_CPU_MASK_SET_reserved0_SHIFT                    5

/* SM_L2 :: CPU_MASK_SET :: DAA_RGDT_INTR [04:04] */
#define BCHP_SM_L2_CPU_MASK_SET_DAA_RGDT_INTR_MASK                 0x00000010
#define BCHP_SM_L2_CPU_MASK_SET_DAA_RGDT_INTR_SHIFT                4

/* SM_L2 :: CPU_MASK_SET :: DAA_INTR [03:03] */
#define BCHP_SM_L2_CPU_MASK_SET_DAA_INTR_MASK                      0x00000008
#define BCHP_SM_L2_CPU_MASK_SET_DAA_INTR_SHIFT                     3

/* SM_L2 :: CPU_MASK_SET :: SM_IRQ [02:02] */
#define BCHP_SM_L2_CPU_MASK_SET_SM_IRQ_MASK                        0x00000004
#define BCHP_SM_L2_CPU_MASK_SET_SM_IRQ_SHIFT                       2

/* SM_L2 :: CPU_MASK_SET :: SM_RX_FIFO_INTR [01:01] */
#define BCHP_SM_L2_CPU_MASK_SET_SM_RX_FIFO_INTR_MASK               0x00000002
#define BCHP_SM_L2_CPU_MASK_SET_SM_RX_FIFO_INTR_SHIFT              1

/* SM_L2 :: CPU_MASK_SET :: SM_TX_FIFO_INTR [00:00] */
#define BCHP_SM_L2_CPU_MASK_SET_SM_TX_FIFO_INTR_MASK               0x00000001
#define BCHP_SM_L2_CPU_MASK_SET_SM_TX_FIFO_INTR_SHIFT              0

/***************************************************************************
 *CPU_MASK_CLEAR - CPU interrupt Mask Clear Register
 ***************************************************************************/
/* SM_L2 :: CPU_MASK_CLEAR :: reserved0 [31:05] */
#define BCHP_SM_L2_CPU_MASK_CLEAR_reserved0_MASK                   0xffffffe0
#define BCHP_SM_L2_CPU_MASK_CLEAR_reserved0_SHIFT                  5

/* SM_L2 :: CPU_MASK_CLEAR :: DAA_RGDT_INTR [04:04] */
#define BCHP_SM_L2_CPU_MASK_CLEAR_DAA_RGDT_INTR_MASK               0x00000010
#define BCHP_SM_L2_CPU_MASK_CLEAR_DAA_RGDT_INTR_SHIFT              4

/* SM_L2 :: CPU_MASK_CLEAR :: DAA_INTR [03:03] */
#define BCHP_SM_L2_CPU_MASK_CLEAR_DAA_INTR_MASK                    0x00000008
#define BCHP_SM_L2_CPU_MASK_CLEAR_DAA_INTR_SHIFT                   3

/* SM_L2 :: CPU_MASK_CLEAR :: SM_IRQ [02:02] */
#define BCHP_SM_L2_CPU_MASK_CLEAR_SM_IRQ_MASK                      0x00000004
#define BCHP_SM_L2_CPU_MASK_CLEAR_SM_IRQ_SHIFT                     2

/* SM_L2 :: CPU_MASK_CLEAR :: SM_RX_FIFO_INTR [01:01] */
#define BCHP_SM_L2_CPU_MASK_CLEAR_SM_RX_FIFO_INTR_MASK             0x00000002
#define BCHP_SM_L2_CPU_MASK_CLEAR_SM_RX_FIFO_INTR_SHIFT            1

/* SM_L2 :: CPU_MASK_CLEAR :: SM_TX_FIFO_INTR [00:00] */
#define BCHP_SM_L2_CPU_MASK_CLEAR_SM_TX_FIFO_INTR_MASK             0x00000001
#define BCHP_SM_L2_CPU_MASK_CLEAR_SM_TX_FIFO_INTR_SHIFT            0

/***************************************************************************
 *PCI_STATUS - PCI interrupt Status Register
 ***************************************************************************/
/* SM_L2 :: PCI_STATUS :: reserved0 [31:05] */
#define BCHP_SM_L2_PCI_STATUS_reserved0_MASK                       0xffffffe0
#define BCHP_SM_L2_PCI_STATUS_reserved0_SHIFT                      5

/* SM_L2 :: PCI_STATUS :: DAA_RGDT_INTR [04:04] */
#define BCHP_SM_L2_PCI_STATUS_DAA_RGDT_INTR_MASK                   0x00000010
#define BCHP_SM_L2_PCI_STATUS_DAA_RGDT_INTR_SHIFT                  4

/* SM_L2 :: PCI_STATUS :: DAA_INTR [03:03] */
#define BCHP_SM_L2_PCI_STATUS_DAA_INTR_MASK                        0x00000008
#define BCHP_SM_L2_PCI_STATUS_DAA_INTR_SHIFT                       3

/* SM_L2 :: PCI_STATUS :: SM_IRQ [02:02] */
#define BCHP_SM_L2_PCI_STATUS_SM_IRQ_MASK                          0x00000004
#define BCHP_SM_L2_PCI_STATUS_SM_IRQ_SHIFT                         2

/* SM_L2 :: PCI_STATUS :: SM_RX_FIFO_INTR [01:01] */
#define BCHP_SM_L2_PCI_STATUS_SM_RX_FIFO_INTR_MASK                 0x00000002
#define BCHP_SM_L2_PCI_STATUS_SM_RX_FIFO_INTR_SHIFT                1

/* SM_L2 :: PCI_STATUS :: SM_TX_FIFO_INTR [00:00] */
#define BCHP_SM_L2_PCI_STATUS_SM_TX_FIFO_INTR_MASK                 0x00000001
#define BCHP_SM_L2_PCI_STATUS_SM_TX_FIFO_INTR_SHIFT                0

/***************************************************************************
 *PCI_SET - PCI interrupt Set Register
 ***************************************************************************/
/* SM_L2 :: PCI_SET :: reserved0 [31:05] */
#define BCHP_SM_L2_PCI_SET_reserved0_MASK                          0xffffffe0
#define BCHP_SM_L2_PCI_SET_reserved0_SHIFT                         5

/* SM_L2 :: PCI_SET :: DAA_RGDT_INTR [04:04] */
#define BCHP_SM_L2_PCI_SET_DAA_RGDT_INTR_MASK                      0x00000010
#define BCHP_SM_L2_PCI_SET_DAA_RGDT_INTR_SHIFT                     4

/* SM_L2 :: PCI_SET :: DAA_INTR [03:03] */
#define BCHP_SM_L2_PCI_SET_DAA_INTR_MASK                           0x00000008
#define BCHP_SM_L2_PCI_SET_DAA_INTR_SHIFT                          3

/* SM_L2 :: PCI_SET :: SM_IRQ [02:02] */
#define BCHP_SM_L2_PCI_SET_SM_IRQ_MASK                             0x00000004
#define BCHP_SM_L2_PCI_SET_SM_IRQ_SHIFT                            2

/* SM_L2 :: PCI_SET :: SM_RX_FIFO_INTR [01:01] */
#define BCHP_SM_L2_PCI_SET_SM_RX_FIFO_INTR_MASK                    0x00000002
#define BCHP_SM_L2_PCI_SET_SM_RX_FIFO_INTR_SHIFT                   1

/* SM_L2 :: PCI_SET :: SM_TX_FIFO_INTR [00:00] */
#define BCHP_SM_L2_PCI_SET_SM_TX_FIFO_INTR_MASK                    0x00000001
#define BCHP_SM_L2_PCI_SET_SM_TX_FIFO_INTR_SHIFT                   0

/***************************************************************************
 *PCI_CLEAR - PCI interrupt Clear Register
 ***************************************************************************/
/* SM_L2 :: PCI_CLEAR :: reserved0 [31:05] */
#define BCHP_SM_L2_PCI_CLEAR_reserved0_MASK                        0xffffffe0
#define BCHP_SM_L2_PCI_CLEAR_reserved0_SHIFT                       5

/* SM_L2 :: PCI_CLEAR :: DAA_RGDT_INTR [04:04] */
#define BCHP_SM_L2_PCI_CLEAR_DAA_RGDT_INTR_MASK                    0x00000010
#define BCHP_SM_L2_PCI_CLEAR_DAA_RGDT_INTR_SHIFT                   4

/* SM_L2 :: PCI_CLEAR :: DAA_INTR [03:03] */
#define BCHP_SM_L2_PCI_CLEAR_DAA_INTR_MASK                         0x00000008
#define BCHP_SM_L2_PCI_CLEAR_DAA_INTR_SHIFT                        3

/* SM_L2 :: PCI_CLEAR :: SM_IRQ [02:02] */
#define BCHP_SM_L2_PCI_CLEAR_SM_IRQ_MASK                           0x00000004
#define BCHP_SM_L2_PCI_CLEAR_SM_IRQ_SHIFT                          2

/* SM_L2 :: PCI_CLEAR :: SM_RX_FIFO_INTR [01:01] */
#define BCHP_SM_L2_PCI_CLEAR_SM_RX_FIFO_INTR_MASK                  0x00000002
#define BCHP_SM_L2_PCI_CLEAR_SM_RX_FIFO_INTR_SHIFT                 1

/* SM_L2 :: PCI_CLEAR :: SM_TX_FIFO_INTR [00:00] */
#define BCHP_SM_L2_PCI_CLEAR_SM_TX_FIFO_INTR_MASK                  0x00000001
#define BCHP_SM_L2_PCI_CLEAR_SM_TX_FIFO_INTR_SHIFT                 0

/***************************************************************************
 *PCI_MASK_STATUS - PCI interrupt Mask Status Register
 ***************************************************************************/
/* SM_L2 :: PCI_MASK_STATUS :: reserved0 [31:05] */
#define BCHP_SM_L2_PCI_MASK_STATUS_reserved0_MASK                  0xffffffe0
#define BCHP_SM_L2_PCI_MASK_STATUS_reserved0_SHIFT                 5

/* SM_L2 :: PCI_MASK_STATUS :: DAA_RGDT_INTR [04:04] */
#define BCHP_SM_L2_PCI_MASK_STATUS_DAA_RGDT_INTR_MASK              0x00000010
#define BCHP_SM_L2_PCI_MASK_STATUS_DAA_RGDT_INTR_SHIFT             4

/* SM_L2 :: PCI_MASK_STATUS :: DAA_INTR [03:03] */
#define BCHP_SM_L2_PCI_MASK_STATUS_DAA_INTR_MASK                   0x00000008
#define BCHP_SM_L2_PCI_MASK_STATUS_DAA_INTR_SHIFT                  3

/* SM_L2 :: PCI_MASK_STATUS :: SM_IRQ [02:02] */
#define BCHP_SM_L2_PCI_MASK_STATUS_SM_IRQ_MASK                     0x00000004
#define BCHP_SM_L2_PCI_MASK_STATUS_SM_IRQ_SHIFT                    2

/* SM_L2 :: PCI_MASK_STATUS :: SM_RX_FIFO_INTR [01:01] */
#define BCHP_SM_L2_PCI_MASK_STATUS_SM_RX_FIFO_INTR_MASK            0x00000002
#define BCHP_SM_L2_PCI_MASK_STATUS_SM_RX_FIFO_INTR_SHIFT           1

/* SM_L2 :: PCI_MASK_STATUS :: SM_TX_FIFO_INTR [00:00] */
#define BCHP_SM_L2_PCI_MASK_STATUS_SM_TX_FIFO_INTR_MASK            0x00000001
#define BCHP_SM_L2_PCI_MASK_STATUS_SM_TX_FIFO_INTR_SHIFT           0

/***************************************************************************
 *PCI_MASK_SET - PCI interrupt Mask Set Register
 ***************************************************************************/
/* SM_L2 :: PCI_MASK_SET :: reserved0 [31:05] */
#define BCHP_SM_L2_PCI_MASK_SET_reserved0_MASK                     0xffffffe0
#define BCHP_SM_L2_PCI_MASK_SET_reserved0_SHIFT                    5

/* SM_L2 :: PCI_MASK_SET :: DAA_RGDT_INTR [04:04] */
#define BCHP_SM_L2_PCI_MASK_SET_DAA_RGDT_INTR_MASK                 0x00000010
#define BCHP_SM_L2_PCI_MASK_SET_DAA_RGDT_INTR_SHIFT                4

/* SM_L2 :: PCI_MASK_SET :: DAA_INTR [03:03] */
#define BCHP_SM_L2_PCI_MASK_SET_DAA_INTR_MASK                      0x00000008
#define BCHP_SM_L2_PCI_MASK_SET_DAA_INTR_SHIFT                     3

/* SM_L2 :: PCI_MASK_SET :: SM_IRQ [02:02] */
#define BCHP_SM_L2_PCI_MASK_SET_SM_IRQ_MASK                        0x00000004
#define BCHP_SM_L2_PCI_MASK_SET_SM_IRQ_SHIFT                       2

/* SM_L2 :: PCI_MASK_SET :: SM_RX_FIFO_INTR [01:01] */
#define BCHP_SM_L2_PCI_MASK_SET_SM_RX_FIFO_INTR_MASK               0x00000002
#define BCHP_SM_L2_PCI_MASK_SET_SM_RX_FIFO_INTR_SHIFT              1

/* SM_L2 :: PCI_MASK_SET :: SM_TX_FIFO_INTR [00:00] */
#define BCHP_SM_L2_PCI_MASK_SET_SM_TX_FIFO_INTR_MASK               0x00000001
#define BCHP_SM_L2_PCI_MASK_SET_SM_TX_FIFO_INTR_SHIFT              0

/***************************************************************************
 *PCI_MASK_CLEAR - PCI interrupt Mask Clear Register
 ***************************************************************************/
/* SM_L2 :: PCI_MASK_CLEAR :: reserved0 [31:05] */
#define BCHP_SM_L2_PCI_MASK_CLEAR_reserved0_MASK                   0xffffffe0
#define BCHP_SM_L2_PCI_MASK_CLEAR_reserved0_SHIFT                  5

/* SM_L2 :: PCI_MASK_CLEAR :: DAA_RGDT_INTR [04:04] */
#define BCHP_SM_L2_PCI_MASK_CLEAR_DAA_RGDT_INTR_MASK               0x00000010
#define BCHP_SM_L2_PCI_MASK_CLEAR_DAA_RGDT_INTR_SHIFT              4

/* SM_L2 :: PCI_MASK_CLEAR :: DAA_INTR [03:03] */
#define BCHP_SM_L2_PCI_MASK_CLEAR_DAA_INTR_MASK                    0x00000008
#define BCHP_SM_L2_PCI_MASK_CLEAR_DAA_INTR_SHIFT                   3

/* SM_L2 :: PCI_MASK_CLEAR :: SM_IRQ [02:02] */
#define BCHP_SM_L2_PCI_MASK_CLEAR_SM_IRQ_MASK                      0x00000004
#define BCHP_SM_L2_PCI_MASK_CLEAR_SM_IRQ_SHIFT                     2

/* SM_L2 :: PCI_MASK_CLEAR :: SM_RX_FIFO_INTR [01:01] */
#define BCHP_SM_L2_PCI_MASK_CLEAR_SM_RX_FIFO_INTR_MASK             0x00000002
#define BCHP_SM_L2_PCI_MASK_CLEAR_SM_RX_FIFO_INTR_SHIFT            1

/* SM_L2 :: PCI_MASK_CLEAR :: SM_TX_FIFO_INTR [00:00] */
#define BCHP_SM_L2_PCI_MASK_CLEAR_SM_TX_FIFO_INTR_MASK             0x00000001
#define BCHP_SM_L2_PCI_MASK_CLEAR_SM_TX_FIFO_INTR_SHIFT            0

#endif /* #ifndef BCHP_SM_L2_H__ */

/* End of File */
